### ISSUE TITLE
[Bug Report] Problem with select in table slot append

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#6046] opened 2017-07-24 14:16 UTC
### Element UI version
1.4.0

### OS/Browsers version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Vue version
2.4.2

### Reproduction Link
[https://codepen.io/anon/pen/gxOeQr](https://codepen.io/anon/pen/gxOeQr)

### Steps to reproduce
Create a table with an append slot and place a select inside there followed by another HTML element

### What is Expected?
The select should set v-model and emit a change event as soon as the value changes

### What is actually happening?
Nothing changes when you select a new value from the select. However, if you then resize the browser causing the table to be recalculated, the change event of the select fires and the value is updated.

**Comment by wacky6** [comment] 2017-07-24 14:35
change event may be fixed in https://github.com/ElemeFE/element/issues/5790

**Comment by smares** [comment] 2017-07-24 15:00
But apparently only if it's followed by something. https://codepen.io/anon/pen/PKoeMe is fine without the trailing `span`.

**Comment by smares** [comment] 2017-08-09 08:29
Just checked 1.4.2 and the problem is still present: https://codepen.io/anon/pen/LjybPG

**Comment by Leopoldthecoder** [comment] 2017-08-09 09:38
@smares We haven't fixed it yet.

This is indeed a very strange bug, and Select is not the only component that goes wrong when nested in this slot.

**Comment by huanguolin** [comment] 2017-08-23 03:26
Very strange,  this slot lost all vue's power.[https://codepen.io/alvinhuang/pen/rzKOOj?editors=1010](https://codepen.io/alvinhuang/pen/rzKOOj?editors=1010)

**Comment by jochen42** [comment] 2017-09-19 10:41
i had a simular issue (slots within table-columns). but since a npm update today, everything works again...

**Comment by smares** [comment] 2017-09-19 11:46
Is this the same issue @jochen42 ? The problem here is not with slots within table-columns, but with the append slot within table.

**Comment by jochen42** [comment] 2017-09-19 12:52
You are right @smares, i did'nt used an append, it is another issue.

**Comment by asypost** [comment] 2018-05-07 10:10
So can it be fixed?It's waiting so long.

**Comment by elfman** [comment] 2018-11-02 08:00
This bug seems to be fixed, I can't reproduce it now.
https://jsfiddle.net/HarlanLuo/Lsf7eug1/

**Closed** 2019-07-01 07:31 UTC
Labels: type: bug
