### ISSUE TITLE
[Bug Report] DatePicker, pop, and pop inside DatePicker, open the window, suggesting that non-unique ID # browser console. It should be that ID has no value.

### ISSUE THREAD

**Issue by xiaofengleiyu** [ElemeFE/element#9601] opened 2018-02-01 04:51 UTC
### Element UI version
2.1.0

### OS/Browsers version
WIN7/Google Chrome 版本 63.0.3239.132（正式版本） 

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/258/](https://jsfiddle.net/mmx38qxw/258/)

### Steps to reproduce
重现链接重现不了！
重现链接重现不了！
重现链接重现不了！

做一个弹窗，弹窗里面有多个Datepicker，然后打开弹窗，浏览器控制台报错：
Found 2 elements with non-unique id #: (More info: https://goo.gl/9p2vKq) <input autocomplete=​"off" placeholder=​"选择日期" size name id type=​"text" rows=​"2" prefixicon=​"el-icon-date" class=​"el-input__inner">​ <input autocomplete=​"off" placeholder=​"选择日期" size name id type=​"text" rows=​"2" prefixicon=​"el-icon-date" class=​"el-input__inner">​

### What is Expected?
弹窗后浏览器不报错

### What is actually happening?
弹窗后浏览器报错（有在代码手动设置id的不会报错）

**Comment by Leopoldthecoder** [comment] 2018-02-01 11:09
Duplicate of #8907

**Closed by Leopoldthecoder** 2018-02-01 11:09 UTC
