### ISSUE TITLE
[Bug Report] the table fixed div(el-table__fixed) cover x-scrollbar of the table when no table data

### ISSUE THREAD

**Issue by Imjw** [ElemeFE/element#13681] opened 2018-12-06 09:32 UTC
### Element UI version
2.4.11

### OS/Browsers version
all os / chrome 70

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/helloimjw/sofjrLpu/](https://jsfiddle.net/helloimjw/sofjrLpu/)

### Steps to reproduce
1. create a el-table with 10 columns
2. make the first column and second column to be fixed
3. make mouse focus on scroll bar of the fixed columns bottom
4. can not drag the scroll bar 

### What is Expected?
when no table data, the scroll bar of table fixed div bottom don't be covered

### What is actually happening?
the table fixed div is covering the scroll bar of table fixed div bottom , I can't drag the scroll bar

**Comment by LilyWakana** [comment] 2018-12-10 15:31
same as #12666

**Comment by ziyoung** [comment] 2018-12-29 06:50
Duplicate of #12666

**Closed by ziyoung** 2018-12-29 06:50 UTC
