### ISSUE TITLE
[Bug Report] can not add transition animation to el-tab tl-tab-pane

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/element#13171] opened 2018-10-25 08:55 UTC
### Element UI version
2.4.8

### OS/Browsers version
mac

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/Yanni_Jia/813afkc9/](https://jsfiddle.net/Yanni_Jia/813afkc9/)

### Steps to reproduce
add transition to el-tab-pane, not work

### What is Expected?
hope to add transition animation to tab-pane content when switch el-tabs

### What is actually happening?
transition animation not work

**Comment by ziyoung** [comment] 2018-10-25 11:51
Duplicate of #12762

**Closed** 2018-10-25 11:52 UTC
