### ISSUE TITLE
[Feature Request] Be able to set input name for DatePicker

### ISSUE THREAD

**Issue by ShaneXie** [ElemeFE/element#7156] opened 2017-09-21 16:01 UTC
### Existing Component
Yes

### Component Name
DatePicker

### Description
Add a new prop that set name of input element, so the picker can be used in a form.

**Comment by ShaneXie** [comment] 2017-09-21 16:55
created a PR, please review
https://github.com/ElemeFE/element/pull/7159

**Comment by Leopoldthecoder** [comment] 2017-09-22 02:11
Duplicate of #7151

**Closed by Leopoldthecoder** 2017-09-22 02:11 UTC
