### ISSUE TITLE
[Bug Report] element ui SSR virtual DOM not matching

### ISSUE THREAD

**Issue by care100** [ElemeFE/element#4622] opened 2017-05-03 06:22 UTC
### Element UI version
1.2.9

### OS/Browsers version
mac10.12/chrome58

### Vue version
2.3.0

### Reproduction Link
[https://github.com/care100/ssr-element-bug.git](https://github.com/care100/ssr-element-bug.git)

### Steps to reproduce
npm install;
npm run dev;
visit 127.0.0.1:8080

### What is Expected?
Server side render component correctly. el-select has right data.
Client has no warn, and after client javascript execute, render component correctly.

### What is actually happening?
when refresh:
el-select has wrong data in server side render.

Client has warn: virtual DOM not matching.And after client javascript execute, el-select is missing.
([Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.)

If el-form is before el-select, it is missing too.

**Comment by Leopoldthecoder** [comment] 2017-05-03 06:34
Please try updating Element to 1.3.0-beta.2 and see if this problem still exists.

**Comment by care100** [comment] 2017-05-04 01:03
Unfortunately, it still exists.(1.3.0-beta.3)

**Comment by Leopoldthecoder** [comment] 2017-05-07 13:11
Did a little test and found that vue-server-renderer @2.2.4 works fine with element-ui @1.3.x but vue-server-renderer @2.3.0 doesn't. Looks like this is a bug on vue-server-renderer's end.

**Comment by Leopoldthecoder** [comment] 2017-05-07 13:41
It has been confirmed: https://github.com/vuejs/vue/issues/5592

So this will be fixed in the next vue / vue-server-renderer release.

**Closed by Leopoldthecoder** 2017-05-07 13:41 UTC

**Comment by care100** [comment] 2017-05-08 01:21
Thanks a lot
