### ISSUE TITLE
[Bug Report] el-table highlights a clicked row on sort

### ISSUE THREAD

**Issue by whitecat** [ElemeFE/element#11634] opened 2018-06-14 15:48 UTC
### Element UI version
2.4.0

### OS/Browsers version
Mac OS High Sierra 10.13.4 (17E199) / Firefox 61.0b12 (64-bit) / Version 67.0.3396.87 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/fqbc2xcr/65/](https://jsfiddle.net/fqbc2xcr/65/)

### Steps to reproduce
Click on the row with the name `Brady` (the row should not be highlighted)
Click on `Date` column title to sort the table
The row with the name `Brady` becomes highlighted

### What is Expected?
Expect the table to be sorted with no highlighting.

### What is actually happening?
The row that was clicked on becomes highlighted, even though `highlight-current-row` is by default false. Sorting seems to make a row highlighted

**Comment by jikkai** [comment] 2018-06-14 16:47
Duplicate of #11560

**Comment by whitecat** [comment] 2018-06-20 23:10
This commit does not seem to fix the bug. The error is still occurring on any table that has sort functionality on deploy preview: https://deploy-preview-11563--element.netlify.com.

**Closed** 2018-06-21 08:14 UTC
Labels: component: table, type: bug
