### ISSUE TITLE
[Feature Request] Add disabled state feature for pagination

### ISSUE THREAD

**Issue by kfeng0806** [ElemeFE/element#5654] opened 2017-07-01 09:21 UTC
### Existing Component
Yes

### Component Name
Pagination

### Description
Add disabled state for pagination component, same as like on button component.
<el-pagination :disabled="true"></el-pagination>

**Comment by Leopoldthecoder** [comment] 2017-08-06 07:20
Duplicate of #6219

**Closed by Leopoldthecoder** 2017-08-06 07:20 UTC
