### ISSUE TITLE
[Bug Report] When you use select on a form, a drop-down item jitter occurs

### ISSUE THREAD

**Issue by coder666666** [ElemeFE/element#15755] opened 2019-05-28 08:33 UTC
### Element UI version
2.4.11

### OS/Browsers version
Windows  10

### Vue version
2.5.2

### Reproduction Link
https://codepen.io/anon/pen/eajBeo?&editable=true

### Steps to reproduce
Click select on the form

### What is Expected?
There is no jitter

### What is actually happening?
There's a lot of shaking

**Comment by island205** [comment] 2019-07-24 10:28
Duplicate of #15501

**Closed by island205** 2019-07-24 10:28 UTC
