### ISSUE TITLE
[Feature Request] Scrollbar component is very easy to use. Why not describe it in the document?

### ISSUE THREAD

**Issue by axetroy** [ElemeFE/element#12783] opened 2018-09-17 02:32 UTC
### Existing Component
是

### Component Name
Scrollbar

### Description
Scrollbar 组件很好用，怎么不在文档中描述？

写个文档加上 ``scollbar.d.ts`` 就能用了

**Comment by ziyoung** [comment] 2018-09-17 03:36
Duplicate of #8495

**Closed** 2018-09-17 03:37 UTC
