### ISSUE TITLE
[Bug Report] When the DatePicker component adds the placeholder attribute，asynchronously updating data at the same time.There is no updated date values displayed under IE browsers.

### ISSUE THREAD

**Issue by su1924** [ElemeFE/element#8647] opened 2017-12-04 08:01 UTC
### Element UI version
2.0.7

### OS/Browsers version
win10 / ie11

### Vue version
2.5.9

### Reproduction Link
[http://jsbin.com/sefetaj/edit?html,js,output](http://jsbin.com/sefetaj/edit?html,js,output)

### Steps to reproduce
1.Adds the placeholder attribute to the DatePicker component
2.Asynchronously updating data
3.There is no updated date value displayed under IE browsers.

### What is Expected?
Show the updated date vaule under IE browsers.

### What is actually happening?
There is no updated date values displayed under IE browsers.

**Comment by Leopoldthecoder** [comment] 2017-12-04 08:08
Duplicate of #8548

**Closed by Leopoldthecoder** 2017-12-04 08:08 UTC

**Comment by zero7u** [comment] 2018-01-03 06:46
怎么解决的？8548也没有解决方案啊，两个都关掉了(:

**Comment by fabin5** [comment] 2018-03-20 04:43
该问题没有解决，现在依然存在。

**Comment by Leopoldthecoder** [comment] 2018-03-20 05:38
@zero7u #8548 从来没关过

**Comment by Leopoldthecoder** [comment] 2018-03-20 05:38
@fabin5 请关注 #8548

**Comment by jerry7723** [comment] 2018-03-30 08:08
我也遇到相同问题，设置了placeholder以后就无法更新，在ie10，ie edge上。ie9没问题
