### ISSUE TITLE
el-image request twice

### ISSUE THREAD

**Issue by zhaoyongsheng1990** [ElemeFE/element#19661] opened 2020-06-17 03:52 UTC
on the demo url：
https://element.eleme.cn/#/zh-CN/component/image
open dev tools you can see same image request twice
in my project also like this

---------------------------------------------------------------------------------------------
https://elementui.github.io/issue-generator/#/zh-CN  not work because always tips：
请填写正确的重现链接

**Comment by cs1707** [comment] 2021-01-04 12:37
Duplicate of #19712

**Closed by cs1707** 2021-01-04 12:37 UTC

**Comment by cying314** [comment] 2024-05-17 12:19
> ![image](https://private-user-images.githubusercontent.com/71744921/252195836-a064e2ab-2630-4635-8d26-380e88a8d0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDg1NTAsIm5iZiI6MTcxNTk0ODI1MCwicGF0aCI6Ii83MTc0NDkyMS8yNTIxOTU4MzYtYTA2NGUyYWItMjYzMC00NjM1LThkMjYtMzgwZTg4YThkMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEyMTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZmVhOTU3MDRiNzA0ZTQ3MzY2MGVkNzEyODYyZWNjNzlmZjcyZDAxYjhkY2YwMWRiYjE4YzRlZjIxNmEyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vfSMzGOmMPHflqoMgtci216KhJ9rpxOT9umaNqtLfL8) 确实会复现，但是只出现在，打开禁止使用缓存的情况下

我们有些图片需要实时动态生成，不能缓存，比如工作流预览图片，因为加载比较慢才加的图片loading，但是反而导致了加载两次
