### ISSUE TITLE
[Feature Request] Hide checkbox in selection column 

### ISSUE THREAD

**Issue by xilibro** [ElemeFE/element#11661] opened 2018-06-19 01:25 UTC
### Existing Component
Yes

### Component Name
el-column

### Description
There is a selection column, when some columns is not fit any condition, i want to hide the checkbox instead of unable it.

**Comment by jikkai** [comment] 2018-06-19 02:14
Duplicate of #11579

**Closed by jikkai** 2018-06-19 02:14 UTC
