### ISSUE TITLE
[Bug Report] multiple select component can not show default text currently

### ISSUE THREAD

**Issue by snovey** [ElemeFE/element#12736] opened 2018-09-12 13:38 UTC
### Element UI version
2.4.6

### OS/Browsers version
OS X Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/4j9e1y2a/](https://jsfiddle.net/4j9e1y2a/)

### Steps to reproduce
Set muliple true, set options empty, set select value not empty.

Please refer to [jsfiddle](https://jsfiddle.net/4j9e1y2a/) for details.

### What is Expected?
Show default select text.

### What is actually happening?
Can not show text.

Consider a situation like this:  
Multiple select components have default values, and user want to search other and choose value from remote, so default options is empty.  
This will cause the page to fail to properly render the default value of the component when initialized.

**Comment by ziyoung** [comment] 2018-09-17 08:11
Duplicate of #12713

**Closed by ziyoung** 2018-09-17 08:11 UTC
