### ISSUE TITLE
[Feature Request] Is it possible integrate Treeselect Components

### ISSUE THREAD

**Issue by richwxd** [ElemeFE/element#15142] opened 2019-04-16 14:02 UTC
### Existing Component
No

### Component Name
treeselect

### Description
集成的功能如https://github.com/riophae/vue-treeselect 或 https://vue.ant.design/components/tree-select/，element-ui里边缺少这个组件，自己用相关组件组合的真的很丑，不是很匹配需求。在vue-ant-design中存在这个组件，但是一个VUE界面来说，集成两套UI组件，不值得。希望增加这个组件变成element-ui的原生组件。

You know there are some ui frameworks have the similar component tree-select. But if the main framework is based on element-ui, who want to integrate another UI components? That is what I want to say, is it possible to elemeFE team to integrate the features into element-ui? 
The features could be from https://github.com/riophae/vue-treeselect and https://vue.ant.design/components/tree-select/

**Comment by ayiaq1** [comment] 2019-04-30 01:32
https://github.com/ayiaq1/el-tree-select

**Comment by ziyoung** [comment] 2019-05-08 03:35
Duplicate of #11795

**Closed by ziyoung** 2019-05-08 03:35 UTC
