### ISSUE TITLE
The [Bug Report] select component is set to search and cannot be retrieved by clicking the arrow in the multiple (filter) drop-down box.

### ISSUE THREAD

**Issue by NorthSeacoder** [ElemeFE/element#13137] opened 2018-10-23 12:39 UTC
### Element UI version
2.4.8

### OS/Browsers version
win10

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/NorthSeacoder/mte4xa82/6/](https://jsfiddle.net/NorthSeacoder/mte4xa82/6/)

### Steps to reproduce
只是添加这俩属性

### What is Expected?
可以正常收起

### What is actually happening?
select组件设置可搜索且为多选时（multiple，filterable）下拉框点击箭头无法收起，并且点击外部收起下拉框后再次点击展开时第一次点击无法打开

**Comment by coffeeyen** [comment] 2018-10-24 01:29
好像只要有filterable的el-select都无法点击箭头收起

**Comment by ziyoung** [comment] 2018-10-26 09:01
https://github.com/ElemeFE/element/issues/13140#issuecomment-433279443

**Comment by ziyoung** [comment] 2018-10-26 09:01
Duplicate of #13140

**Closed by ziyoung** 2018-10-26 09:01 UTC
