### ISSUE TITLE
[Bug Report] el-table when using the fixed and show-summary at the same time, the horizontal scroll bar under the fixed column cannot be used.

### ISSUE THREAD

**Issue by skiller008** [ElemeFE/element#12105] opened 2018-07-24 09:35 UTC
### Element UI version
2.4.4

### OS/Browsers version
IE/Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[http://jsfiddle.net/1djypwg0/](http://jsfiddle.net/1djypwg0/)

### Steps to reproduce
1.If the horizontal scroll bar does not appear, adjust the column size or container size to make the horizontal scroll bar appear.
2.Drag the scroll bar below the fixed column on either side of the table or click the scroll bar on both sides.

### What is Expected?
Normally drag and control the scroll bar.

### What is actually happening?
The scroll bar is actually fixed by a fixed column and cannot be clicked or dragged.

**Comment by jikkai** [comment] 2018-07-30 06:32
Duplicate of #5415

**Closed by jikkai** 2018-07-30 06:32 UTC
