### ISSUE TITLE
[Feature Request] how to set half checked keys with tree component?

### ISSUE THREAD

**Issue by mrleex** [ElemeFE/element#13503] opened 2018-11-21 03:39 UTC
### Existing Component
是

### Component Name
tree

### Description
Hello, I have a organization tree with lazy load, when someone choose what they want to manage, save it, and then reopen the tree, I want to keep checked status, however, I can set checked keys with setChecked method, but there is not half checked status, is there any way to set half checked keys?  :)

**Comment by ziyoung** [comment] 2018-11-21 04:11
Duplicate of #13500

**Closed by ziyoung** 2018-11-21 04:11 UTC

**Comment by imyoursazhou** [comment] 2018-12-27 02:44
i have same issue with you,do you have any answer now?
