### ISSUE TITLE
[Feature Request] vue3版本的什么时候会上~~

### ISSUE THREAD

**Issue by 86driver** [ElemeFE/element#19269] opened 2020-04-26 02:58 UTC
### Existing Component
否

### Component Name
vue-next

### Description
vue3 beta已经发了， element 还会远吗

**Comment by zazzaz** [comment] 2020-08-20 10:49
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by 86driver** [comment] 2020-08-24 12:12
> YES!  Element Plus - A Vue.js 3.0 UI library 
> 
> [element-plus/element-plus#147](https://github.com/element-plus/element-plus/issues/147)

nice job

**Comment by cs1707** [comment] 2020-12-26 04:56
Duplicate of #20375

**Closed by cs1707** 2020-12-26 04:56 UTC
