### ISSUE TITLE
[Feature Request] Bullet Window in Full Screen Mode

### ISSUE THREAD

**Issue by xinjiangyuangit** [ElemeFE/element#14608] opened 2019-03-07 01:13 UTC
### Existing Component
Yes

### Component Name
Message

### Description
After full-screen DOM, the message pop-up window is still stitched under Body, hoping that Message can customize the insertion location of $EL.

**Comment by island205** [comment] 2019-03-09 02:14
Duplicate of #12872

**Closed by island205** 2019-03-09 02:14 UTC
