### ISSUE TITLE
[Feature Request] Is there a plan for vue3 compatibility and support?

### ISSUE THREAD

**Issue by tobemaster56** [ElemeFE/element#19904] opened 2020-07-22 07:21 UTC
### Existing Component
否

### Component Name
vue3 compatibility and support

### Description
Element, is it just a maintenance phase now? Do you have plans for compatibility and support of vue3?

**Comment by zazzaz** [comment] 2020-08-20 10:43
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment] 2020-12-26 04:58
Duplicate of #20375

**Closed by cs1707** 2020-12-26 04:58 UTC
