### ISSUE TITLE
[Bug Report] When "remote search" Select gets focus using TAB, then child Input inside remains readonly

### ISSUE THREAD

**Issue by lauri911** [ElemeFE/element#10465] opened 2018-03-29 13:19 UTC
### Element UI version
2.3.2

### OS/Browsers version
65.0.3325.181 (Official Build) (64-bit)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1113/](https://jsfiddle.net/mmx38qxw/1113/)

### Steps to reproduce
Use TAB to focus Select component --- and then you can not type for search because Input element inside Select is "readonly" .

Using mouse to focus Select component works as expected.

### What is Expected?
When Select component get focus, then Input component inside cant be "read only".

### What is actually happening?
Focusing with TAB, Input component inside Select remains "readonly"

**Comment by Leopoldthecoder** [comment] 2018-03-30 06:23
Duplicate of #10469

**Closed by Leopoldthecoder** 2018-03-30 06:23 UTC
