### ISSUE TITLE
[Bug Report] key not handled by el-upload

### ISSUE THREAD

**Issue by steffanhalv** [ElemeFE/element#5922] opened 2017-07-18 21:02 UTC
### Element UI version
1.3.7

### OS/Browsers version
latest chrome

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
```
<el-upload
             ref="upload"
             drag
             accept=".jpg, .jpeg, .gif, .bmp, .png"
             action="#"
             :http-request="upload"
             multiple>
    <div class="el-upload__text" style="font-size: 11px;">Drop or <em>click to upload</em></div>
  </el-upload>
```

### What is Expected?
handle keys automatically

### What is actually happening?
vue throws error:

[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

**Comment by Leopoldthecoder** [comment] 2017-07-19 01:57
Duplicate of #5868

**Closed by Leopoldthecoder** 2017-07-19 01:57 UTC
