### ISSUE TITLE
The highlight-current-row attribute of [Bug Report] table component has no effect. No settings will be highlighted after clicking.

### ISSUE THREAD

**Issue by pkwdzc** [ElemeFE/element#11719] opened 2018-06-22 11:27 UTC
### Element UI version
2.4.1

### OS/Browsers version
win7 / chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/pkwdzc/8wLq2y4f/](https://jsfiddle.net/pkwdzc/8wLq2y4f/)

### Steps to reproduce
1、table组件highlight-current-row属性默认是false，意味着不高亮选中行
2、不设置highlight-current-row属性，点击table里任意一行，当前行高亮
3、事实上在官网的所有table的demo里都有这个问题，无论是否设置highlight-current-row属性，点击任意一行均会高亮当前行

### What is Expected?
table组件不设置highlight-current-row属性时，点击不会高亮当前选中行。只有设置了highlight-current-row为true，才会在点击时高亮row

### What is actually happening?
无论是否设置highlight-current-row属性，点击任意一行均会高亮当前行

**Comment by jikkai** [comment] 2018-06-22 11:37
Duplicate of #11560

**Closed by jikkai** 2018-06-22 11:37 UTC
