### ISSUE TITLE
[Bug Report] DatePicker range can't work normally in QQBrowser v9.6.5

### ISSUE THREAD

**Issue by xovel** [ElemeFE/element#7864] opened 2017-10-30 14:36 UTC
### Element UI version
2.0.1

### OS/Browsers version
Win10/QQBrowser v9.6.5

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/xovel/fypa6a6z/](https://jsfiddle.net/xovel/fypa6a6z/)

### Steps to reproduce
http://element-cn.eleme.io/2.0/#/zh-CN/component/date-picker#xuan-ze-ri-qi-fan-wei

Can't select a date range.

### What is Expected?
Select a range correctly.

### What is actually happening?
NaN

**Comment by xovel** [comment] 2017-10-30 14:38
The `Reproduction Link` above is just a placeholder, 'cause it banned by `element-bot` automatically.

**Comment by Leopoldthecoder** [comment] 2017-10-31 02:07
Duplicate of https://github.com/ElemeFE/element/issues/7539

**Closed by Leopoldthecoder** 2017-10-31 02:07 UTC
