### ISSUE TITLE
[Bug Report] Tap-Pane Loading Issue

### ISSUE THREAD

**Issue by FruityDeath** [ElemeFE/element#14509] opened 2019-02-27 11:20 UTC
### Element UI version
2.5.4

### OS/Browsers version
Windows 10 / Chrome 72.0.3626.109

### Vue version
2.6.7

### Reproduction Link
[https://jsfiddle.net/64hbf1js/](https://jsfiddle.net/64hbf1js/)

### Steps to reproduce
https://jsfiddle.net/64hbf1js/

### What is Expected?
Tab User should display a loading spinner

### What is actually happening?
Tab User doesnt display a loading spinner

**Comment by ziyoung** [comment] 2019-03-05 08:31
Duplicate of #14351

**Closed by ziyoung** 2019-03-05 08:31 UTC
Labels: component: tabs, type: bug
