### ISSUE TITLE
[Bug Report] can not display value value in DatePicker in IE.

### ISSUE THREAD

**Issue by vonweb** [ElemeFE/element#11571] opened 2018-06-11 07:10 UTC
### Element UI version
2.4.1

### OS/Browsers version
win10 1803/ IE 11.48.17134.0

### Vue version
2.5.16

### Reproduction Link
[http://jsbin.com/mafemewomi/5/edit?html,js,output](http://jsbin.com/mafemewomi/5/edit?html,js,output)

### Steps to reproduce
1、el-date-picker设置了placeholder属性
2、value值延后设置
3、在IE打开项目文件

### What is Expected?
DatePicker显示value值

### What is actually happening?
DatePicker显示placeholder

**Comment by Leopoldthecoder** [comment] 2018-06-11 07:53
Duplicate of #8548

**Closed by Leopoldthecoder** 2018-06-11 07:53 UTC
