### ISSUE TITLE
When [Bug Report] paging data total is 0, go to [page input input defocus between 0 and 1.

### ISSUE THREAD

**Issue by wangtengfei1002** [ElemeFE/element#12702] opened 2018-09-11 08:52 UTC
### Element UI version
2.4.6

### OS/Browsers version
google

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1 分页组件上 设置  :total="0" 
2 点击前往页面input，之后点击外部
3 该input 值从 1 变为0
4 再次重复该动作，又从0变为1

### What is Expected?
前往页面input 里的值保持不变

### What is actually happening?
前往页面input 里的值不停1/0/1/0。。。。。。。。。。。

**Comment by ziyoung** [comment] 2018-09-11 11:35
请提供一个正确的链接。

**Comment by jikkai** [comment] 2018-09-11 11:55
Duplicate of #12422 , and maybe already fixed in #12525

**Closed** 2018-09-14 02:49 UTC
Labels: need: repro
