### ISSUE TITLE
[Bug Report]  if there is an overflow css the el-menu component collapsed does not show the child menu when mouse hover

### ISSUE THREAD

**Issue by jerry9022** [ElemeFE/element#6261] opened 2017-08-03 04:28 UTC
### Element UI version
1.4.1

### OS/Browsers version
mac OS/chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/7mmn4ra5/](https://jsfiddle.net/7mmn4ra5/)

### Steps to reproduce
1. when the left side menu  collapsed, move mouse over one menu,the floating child  menu can not show
2. if I remove the css "overflow-y:auto", the floating child  menu can show, but I can't see the over-long menu,because there is no scroll.

### What is Expected?
 if there is an overflow css the el-menu component collapsed can show the floating child menu when mouse hover.

### What is actually happening?
 if there is an overflow css the el-menu component collapsed can't show the floating child menu when mouse hover.

**Comment by Leopoldthecoder** [comment] 2017-08-03 05:54
Duplicate of #6227

**Closed by Leopoldthecoder** 2017-08-03 05:54 UTC
