### ISSUE TITLE
[Feature Request] suggests adding a component, the timeline component, TimeLine

### ISSUE THREAD

**Issue by Undefined123456789** [ElemeFE/element#5560] opened 2017-06-26 13:19 UTC
### Existing Component
否

### Component Name
TimeLine

### Description
就想更新日志里的那条时间线组件；

**Comment by Leopoldthecoder** [comment] 2017-06-26 14:00
Duplicate of #3404

**Closed by Leopoldthecoder** 2017-06-26 14:00 UTC

**Comment by ibufu** [comment] 2017-08-23 03:08
need timeline.
