### ISSUE TITLE
[Feature Request] input number: emit focus and blur events

### ISSUE THREAD

**Issue by Lazac92** [ElemeFE/element#5043] opened 2017-05-24 10:54 UTC
### Existing Component
Yes

### Component Name
el-input-number

### Description
Problem: There is no focus and blur event for el-input-number.

Expected behaviour: There IS a focus and blur for this element.

Issue explained: I wanted to create a unique looking field, where I have an el-input and el-input-number next to each other and they look like one field. They are wrapped inside a div, so I wanted to create a focus, hover and blur effect for this div. However the el-input-number does not have these events, so I cannot create this unique result. I think these events should be implemented to the el-input-number field as well.

Possible solution: The el-input-number should emit the inner el-input's events.

Example: https://jsfiddle.net/z900yyby/

**Comment by Leopoldthecoder** [comment] 2017-05-29 03:30
In plan. Duplicate of #2544.

**Closed by Leopoldthecoder** 2017-05-29 03:30 UTC
