### ISSUE TITLE
[bug report] the select component has both filterable and multiple components. Click the shrink button and it doesn't take effect

### ISSUE THREAD

**Issue by mashedpotato2018** [ElemeFE/element#21059] opened 2021-06-10 02:26 UTC
### Element UI version
2.15.2

### OS/Browsers version
window10/chorme

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/mashedpotato2018/pen/BaWOzgy

### Steps to reproduce
展开下拉选项，点击收缩按钮无效

### What is Expected?
收缩下拉选项

### What is actually happening?
没有任何行为

**Comment by cs1707** [comment] 2021-09-26 07:48
Duplicate of #21117

**Closed by cs1707** 2021-09-26 07:48 UTC
