### ISSUE TITLE
[Feature Request] Vue3 Composition API support?

### ISSUE THREAD

**Issue by georgyfarniev** [ElemeFE/element#17634] opened 2019-10-08 02:16 UTC
### Existing Component
Yes

### Component Name
All

### Description
Hello, is there any plan for migration to composition API as soon as it releases? I may participate in it.

**Comment by lynzz** [comment] 2020-06-03 03:03
用 Composition API ，el-table-column 函数类型的属性，会不生效

**Comment by zazzaz** [comment] 2020-08-20 10:50
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment] 2020-12-26 05:00
Duplicate of #20375

**Closed by cs1707** 2020-12-26 05:00 UTC
