### ISSUE TITLE
After the [Bug Report] webpack is packaged, check the mailbox in the form. If there is an uppercase letter, the check does not pass

### ISSUE THREAD

**Issue by zfdai** [ElemeFE/element#4989] opened 2017-05-22 09:08 UTC
### Element UI version
1.3.3

### OS/Browsers version
chrome 最新

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
重现链接 是没有用的，问题是打包之后出现的问题
  :rules="[
           { required: true, message: '请输入邮箱地址！', trigger: 'blur' },
           { type: 'email', message: '请输入正确的邮箱地址！', trigger: 'blur' }
  ]"
表单中添加type:'email' 在开发环境中  邮箱中大写字母可以通过，但npm run build之后，邮箱中有大写字母校验失败！

### What is Expected?
表单  type: 'email' 在webpack打包之后，邮箱中有大写字母可以通过

### What is actually happening?
表单  type: 'email' 在webpack打包之后，邮箱中有大写字母不能通过

**Comment by Leopoldthecoder** [comment] 2017-05-29 06:40
Emails with capital letters failing form validation is an old bug of `async-validator`, and it's fixed in `async-validator@1.6.9`. Element 1.3.0 updated dependency versions to reflect this fix, so your problem is caused by inconsistent Element versions in dev and prod environments. Make sure your prod environment has Element 1.3.0+ installed.

**Closed by Leopoldthecoder** 2017-05-29 06:40 UTC
