### ISSUE TITLE
[Bug Report] DatePicker can not be used in the <td> label below the append template of ElTable.

### ISSUE THREAD

**Issue by asypost** [ElemeFE/element#11038] opened 2018-05-07 08:36 UTC
### Element UI version
1.4.13

### OS/Browsers version
Windows 10/Firefox 59

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/asypost/dmpfb5x4/17/](https://jsfiddle.net/asypost/dmpfb5x4/17/)

### Steps to reproduce
1、将DatePicker放入ElTable append slot的td里面；
2、选择一个新日期；
3、发现新日期不显示在控件里。

### What is Expected?
选择日期后，输入框显示选择的日期

### What is actually happening?
日期选择控件输入框无显示

**Comment by Leopoldthecoder** [comment] 2018-05-07 09:09
Duplicate of https://github.com/ElemeFE/element/issues/6046

**Closed by Leopoldthecoder** 2018-05-07 09:09 UTC
