### ISSUE TITLE
[Bug Report] The popover doesn't follow the target in scroll view

### ISSUE THREAD

**Issue by snowffer** [ElemeFE/element#8883] opened 2017-12-18 16:32 UTC
### Element UI version
2.0.8

### OS/Browsers version
Mac OSX 10.13.1 (17B1003) / Chrome 63.0.3239.108 (Official Build) (64-bit)

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/snowell/s1no2kc6/7/](https://jsfiddle.net/snowell/s1no2kc6/7/)

### Steps to reproduce
1. Click the DOM "click me" to trigger the popover
2. Scroll up the view which contains "click me"

### What is Expected?
The popover should follow the "click me" in scroll view

### What is actually happening?
The popover stays right the place where it generates.

**Comment by snowffer** [comment] 2017-12-20 10:20
Any response?

**Comment by Leopoldthecoder** [comment] 2017-12-20 13:12
Duplicate of #7098. This doesn't seems to be easy to fix, so you're welcome to help us if you're interested.

**Closed by Leopoldthecoder** 2017-12-20 13:12 UTC

**Comment by snowffer** [comment] 2017-12-20 15:54
@Leopoldthecoder Is there any way to avoid this issue? 

It seems that the popover is always added in body directly. That would causes this issue easily. Another UI kit iView can avoid this problem by a property called 'transfer' which decide to put it in body or not.

**Comment by yuanhuanwebfront** [comment] 2021-09-15 07:51
It seems like not solved . when i use a popover in el-drawer with scroll bar, the popover doesn‘t scroll with drawer. @Leopoldthecoder
