### ISSUE TITLE
[Bug Report] date-picker in 'daterange' type,  startDate miss class "start-date"

### ISSUE THREAD

**Issue by jyjunyz** [ElemeFE/element#5215] opened 2017-06-06 08:45 UTC
### Element UI version
1.3.5

### OS/Browsers version
58.0.3029.110 (64-bit)

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/jyjunyz/edebc1f9/](https://jsfiddle.net/jyjunyz/edebc1f9/)

### Steps to reproduce
input any date range, start date miss class "start-date"

### What is Expected?
input any date range, start date has class "start-date"

### What is actually happening?
input any date range, start date miss class "start-date"

**Comment by jyjunyz** [comment] 2017-06-06 08:47
I think this bug cause by this [commit](https://github.com/ElemeFE/element/commit/6563a3a8049cf9c6e395d52cc966b1870797fc15)

**Comment by Leopoldthecoder** [comment] 2017-06-06 14:27
You're right. Duplicate of #5199

**Closed by Leopoldthecoder** 2017-06-06 14:27 UTC
