### ISSUE TITLE
[Feature Request] [question] how to combine el-menu components? 

### ISSUE THREAD

**Issue by yesworld** [ElemeFE/element#13554] opened 2018-11-25 18:14 UTC
### Existing Component
Yes

### Component Name
el-menu

### Description
I have two el-menu components, how to combine them together? So that when you click on one of the elements(el-menu-item) of one menu, the class "is-active" disappears in another menu.

**Comment by georgyfarniev** [comment] 2018-11-26 03:51
Probably duplicate of https://github.com/ElemeFE/element/issues/13300

**Comment by yesworld** [comment] 2018-11-26 07:31
@georgyfarniev Yes, it is.

**Comment by ziyoung** [comment] 2018-11-26 10:10
Duplicate of #13300

**Closed by ziyoung** 2018-11-26 10:10 UTC
