### ISSUE TITLE
The combination of [Feature Request] el-scrollbar and el-table makes tbody roll.

### ISSUE THREAD

**Issue by zhanlijian** [ElemeFE/element#12372] opened 2018-08-15 05:53 UTC
### Existing Component
是

### Component Name
el-table

### Description
el-table 适配时滚动条能不能自带，或者el-scrollbar怎么结合使用

**Comment by jikkai** [comment] 2018-08-15 06:09
Duplicate of #11208

**Closed by jikkai** 2018-08-15 06:09 UTC

**Comment by zhanlijian** [comment] 2018-08-15 07:10
ok
