### ISSUE TITLE
The content of the password box in the [Bug Report] Form will display the content directly

### ISSUE THREAD

**Issue by 383366204** [ElemeFE/element#10426] opened 2018-03-28 14:06 UTC
### Element UI version
2.3.0

### OS/Browsers version
win10/chrome firefox

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1065/](https://jsfiddle.net/mmx38qxw/1065/)

### Steps to reproduce
在Form中的密码输入框中输入内容

### What is Expected?
密码框不应该显示输入的内容，应该用黑点来代替

### What is actually happening?
直接显示了输入的内容

**Comment by GOODLFC** [comment] 2018-03-28 14:29
我也遇到了这个情况，e-input 的 type="password" 失效，直接显示出输入的密码

**Comment by jwenjian** [comment] 2018-03-28 14:36
移步#10407，已经修复，等新的release吧

**Comment by vanstolyaroff** [comment] 2018-03-28 14:51
same issue here, can you comment it in English?)

**Comment by SohrabZ** [comment] 2018-03-28 15:11
I think this will probably fix it: https://github.com/ElemeFE/element/commit/3a086ee51595bb661440862a8883c7bc8b32cabf

**Comment by wolfdong7** [comment] 2018-03-29 00:38
我也遇到了这个情况，e-input 的 type="password" 失效，直接显示出输入的密码

**Comment by Leopoldthecoder** [comment] 2018-03-29 02:27
Duplicate of #10407 . Will release a patch soon.

**Closed by Leopoldthecoder** 2018-03-29 02:27 UTC

**Comment by Leopoldthecoder** [comment] 2018-03-29 03:19
Just released 2.3.1
