### ISSUE TITLE
[Bug Report] The select selector is displayed at different resolutions and is misaligned (the select selector is displaced at different resolutions)

### ISSUE THREAD

**Issue by jiangangzou** [ElemeFE/element#13259] opened 2018-11-01 05:37 UTC
_

![](https://static.dingtalk.com/media/lALPDgQ9qUURY1bNApfNAtw_732_663.png_620x10000q90g.jpg)

### Element UI version
2.4.2

### OS/Browsers version
win10/chorme  69.0.3497.92 (64位)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xxndsy/j8q4x1gt/](https://jsfiddle.net/xxndsy/j8q4x1gt/)

### Steps to reproduce
1. Start the project normally and introduce the select component （正常启动项目，并引入select组件）
 2.Use chorme 69.0.3497.92 (64-bit) browsing effect （使用chorme  69.0.3497.92 (64位)浏览效果）
3.se the select component under the Windows 10 operating system resolution of 1600*1024 （在win10 操作系统 分辨率为1600*1024下用select组件）
4.The box is out of place（选项框出现错位）

### What is Expected?
A selection box pops up above or below the selector 译文：在选择器上方或者下方弹出选择框
![image](https://user-images.githubusercontent.com/38418733/47834599-141fba00-dddb-11e8-82c1-b15a51eb605b.png)

### What is actually happening?
A selection box appears at the remote location of the deviation selector 译文：在偏离选择器较偏远得位置出现选择框
![image](https://user-images.githubusercontent.com/38418733/47834629-39142d00-dddb-11e8-91f6-c3a6793e9478.png)

**Comment by ziyoung** [comment] 2018-11-02 04:10
Duplicate of #13037

**Comment by ziyoung** [comment] 2018-11-02 04:10
可以先试试这个方案。https://github.com/ElemeFE/element/issues/13037#issuecomment-429768387

**Closed by ziyoung** 2018-11-02 04:10 UTC
