### ISSUE TITLE
[Bug Report] Input not work after ElementUI 2.5.0

### ISSUE THREAD

**Issue by somebugs** [ElemeFE/element#14361] opened 2019-02-14 01:30 UTC
### Element UI version
2.5.4

### OS/Browsers version
win10, macOS, chrome, firefox, edge

### Vue version
2.6.6

### Reproduction Link
[https://jsfiddle.net/85276k1c/1/](https://jsfiddle.net/85276k1c/1/)

### Steps to reproduce

In the previous version, when processing form data, you don't need to initialize the value of input. If the new version is not initialized, you can't enter it.

### What is Expected?
It is work fine like elementUI 2.4.11, [demo](https://jsfiddle.net/9schgmwn/1/)

### What is actually happening?
Can't enter it. [demo](https://jsfiddle.net/85276k1c/1/)

**Comment by somebugs** [comment] 2019-02-14 01:34
Because of this pr
[pr #113471](https://github.com/ElemeFE/element/pull/13471)

[source code](https://github.com/ElemeFE/element/pull/13471/commits/211bb3c977af9dde7b2e4c7cbc6bd6974d19b73d)

**Comment by mallardduck** [comment] 2019-02-14 17:42
Having the same issues as well.

**Comment by mallardduck** [comment] 2019-02-21 13:56
Not that it's going to be a solution for everyone, but I was able to work around this issue.

Instead of using `:value` change it to `v-model` and it may work for you. Here's a fiddle with the working version.

https://jsfiddle.net/rp3o84ct/1/

**Comment by iamkun** [comment] 2019-03-05 07:07
@mallardduck thanks

**Comment by ziyoung** [comment] 2019-03-05 07:08
Duplicate of #11689

**Closed by ziyoung** 2019-03-05 07:08 UTC
