### ISSUE TITLE
When [Feature Request] INPUT components or other form components are disabled when disabled is disable, rule validation should not take effect on the disabled components, or it will be troublesome to set up empty checks by themselves.

### ISSUE THREAD

**Issue by dongsuju** [ElemeFE/element#12124] opened 2018-07-25 08:41 UTC
### Existing Component
是

### Component Name
Form

### Description
INPUT组件或其他表单组件在disabled禁用后rule验证就不应该对已经禁用的组件生效，不然还得自己去设置空校验 很麻烦。希望能支持此case，有好几个人提这个了，谢谢，

**Comment by jikkai** [comment] 2018-07-25 08:52
Duplicate of #6927

**Closed by jikkai** 2018-07-25 08:52 UTC
