### ISSUE TITLE
The [Feature Request] tree component returns through the data request, and then executes the selected event. At this time, no effect is selected and settomeout is needed.

### ISSUE THREAD

**Issue by janxy** [ElemeFE/element#11877] opened 2018-07-05 07:15 UTC
### Existing Component
是

### Component Name
tree

### Description
tree组件通过数据请求回来，然后在执行选中事件，这时选中无效果，需要settomeout才可以。

**Comment by ziyoung** [comment] 2018-07-05 07:35
Duplicate of #11876

**Closed** 2018-07-05 07:38 UTC
