### ISSUE TITLE
Vue3.0 color selector style bug

### ISSUE THREAD

**Issue by LiuShuo-git** [ElemeFE/element#20616] opened 2020-12-25 08:37 UTC
颜色选择器 透明度和选择默认颜色的显示有bug [](url)
![Snipaste_2020-12-25_16-35-50](https://user-images.githubusercontent.com/44434777/103128214-62852680-46cf-11eb-93b0-8574cadcca3b.png)

**Comment by cs1707** [comment] 2020-12-26 04:52
Duplicate of #20375

**Closed by cs1707** 2020-12-26 04:52 UTC
