### ISSUE TITLE
[Feature Request] Can you add the active-background-color property to the el-menu component?

### ISSUE THREAD

**Issue by zhongyue2332** [ElemeFE/element#10413] opened 2018-03-28 09:27 UTC
### Existing Component
是

### Component Name
el-menu

### Description
Most of the time, the background color that is activated is the color of the designer's tune.Since active-text-color has all, why does active-background-color have no?

**Comment by Leopoldthecoder** [comment] 2018-03-28 09:31
Duplicate of #7686

**Closed by Leopoldthecoder** 2018-03-28 09:31 UTC
