### ISSUE TITLE
[Bug Report] async-validator digital verification error

### ISSUE THREAD

**Issue by arkfang** [ElemeFE/element#7678] opened 2017-10-24 09:01 UTC
### Element UI version
2.0.0-beta.1

### OS/Browsers version
版本 61.0.3163.100（正式版本） （64 位）

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/p6phbg2p/](https://jsfiddle.net/p6phbg2p/)

### Steps to reproduce
输入框输入 12。32，点击提交

### What is Expected?
提交失败，错误提示alert

### What is actually happening?
验证通过

**Comment by Leopoldthecoder** [comment] 2017-10-24 09:26
Duplicate of #7629

**Closed by Leopoldthecoder** 2017-10-24 09:26 UTC
