### ISSUE TITLE
[Bug Report] table Style problems

### ISSUE THREAD

**Issue by shenzhirong** [ElemeFE/element#8939] opened 2017-12-21 08:40 UTC
### Element UI version
2.0.8

### OS/Browsers version
Google Chrome 63.0.3239.84

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/126/](https://jsfiddle.net/mmx38qxw/126/)

### Steps to reproduce
1.Set multi-column head
2.Rightmost fixed 1 column

### What is Expected?
A border appears

### What is actually happening?
The border disappeared

**Comment by baiyaaaaa** [comment] 2018-01-11 07:33
Duplicate of #8591

**Closed by baiyaaaaa** 2018-01-11 07:33 UTC
