### ISSUE TITLE
[Bug Report] El-autocomplete should highlight first suggestion on input. Pressing "Enter" should select it.

### ISSUE THREAD

**Issue by iabdulin** [ElemeFE/element#6925] opened 2017-09-08 03:39 UTC
### Element UI version
1.4.4

### OS/Browsers version
Mac, latest Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/559/](https://jsfiddle.net/pj71jkyw/559/)

### Steps to reproduce
1) Enter "1", press Enter — nothing happens

### What is Expected?
1) It should select "111"

### What is actually happening?
Nothing

**Comment by Leopoldthecoder** [comment] 2017-09-08 13:53
Duplicate of #6411

**Closed by Leopoldthecoder** 2017-09-08 13:53 UTC
