### ISSUE TITLE
[Code Improvement] sort method uses incorrect return values

### ISSUE THREAD

**Issue by ffxsam** [ElemeFE/element#7366] opened 2017-10-05 17:56 UTC
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
N/A

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/no](https://jsfiddle.net/no)

### Steps to reproduce
https://github.com/ElemeFE/element/blob/0966662dc057d64b8f2e27e82c514ba5df4af0e4/packages/table/src/util.js#L31

Array's `sort` should actually return either -1, 0, or 1, not true/false.

### What is Expected?
Example of a basic sort:

```js
myArray.sort((a, b) => {
  if (a > b) return 1;
  else if (a < b) return -1;
  return 0;
});
```

### What is actually happening?
sortMethod is documented that it should return a true/false value.

**Comment by Leopoldthecoder** [comment] 2017-10-06 03:04
Duplicate of #6444. It will be taken care of before the final 2.0.0.

**Closed by Leopoldthecoder** 2017-10-06 03:04 UTC
