### ISSUE TITLE
[Feature Request] add tree select component please

### ISSUE THREAD

**Issue by see311** [ElemeFE/element#12005] opened 2018-07-16 04:27 UTC
### Existing Component
否

### Component Name
tree select

### Description
add tree select component please.  
example: 
* [antd treeSelect](https://ant.design/components/tree-select-cn/)
* [vue-treeselect.js](https://vue-treeselect.js.org/)

**Comment by jikkai** [comment] 2018-07-16 05:01
Duplicate of #11795

**Closed by jikkai** 2018-07-16 05:01 UTC
