### ISSUE TITLE
[Bug Report] table [fixed column] and [show-summary] lead to layout disorder

### ISSUE THREAD

**Issue by CodeTrouble** [ElemeFE/element#6825] opened 2017-09-02 08:05 UTC
### Element UI version
1.4.3

### OS/Browsers version
windows10 Chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/khmnLtsu/](https://jsfiddle.net/khmnLtsu/)

### Steps to reproduce
set table attributes[show-summary] and table-column attributes[fixed column]  exist at the same time
lead to layout disorder

### What is Expected?
fix table layout disorder

### What is actually happening?
...

**Comment by Leopoldthecoder** [comment] 2017-09-02 12:26
Duplicate of #5415

**Closed by Leopoldthecoder** 2017-09-02 12:26 UTC
