### ISSUE TITLE
[Bug Report] el-tree in Docs,custom node content delete-button is invalid

### ISSUE THREAD

**Issue by wanghanzhen** [ElemeFE/element#12527] opened 2018-08-28 07:22 UTC
### Element UI version
2.4.6

### OS/Browsers version
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

### Vue version
2.5.17

### Reproduction Link
[http://element-cn.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong](http://element-cn.eleme.io/#/zh-CN/component/tree#zi-ding-yi-jie-dian-nei-rong)

### Steps to reproduce
i

### What is Expected?
fix it

### What is actually happening?
文档的删除按钮不行 实际上也不行

**Comment by jikkai** [comment] 2018-08-28 07:42
Duplicate of #12421

**Closed by jikkai** 2018-08-28 07:42 UTC
