### ISSUE TITLE
[Bug Report] select sometimes open twice

### ISSUE THREAD

**Issue by Bombay** [ElemeFE/element#16062] opened 2019-06-14 06:59 UTC
### Element UI version
2.2.1

### OS/Browsers version
Chorme 74.0.3729.169

### Vue version
2.5.21

### Reproduction Link
https://jsfiddle.net/2b3e8zxL/

### Steps to reproduce
open el-select

### What is Expected?
select is opened naturally

### What is actually happening?
sometimes select is opened twice

![blink](https://user-images.githubusercontent.com/9034302/59489521-5ce53880-8ebd-11e9-8678-f70b732ee417.gif)

**Comment by websanova** [comment] 2019-06-15 10:15
I have the same issue

**Comment by island205** [comment] 2019-07-08 09:37
Duplicate of #15501

**Closed by island205** 2019-07-08 09:37 UTC
