### ISSUE TITLE
[Bug Report] el-select space not working within el-menu

### ISSUE THREAD

**Issue by meta0102** [ElemeFE/element#10362] opened 2018-03-26 06:09 UTC
### Element UI version
2.2.2

### OS/Browsers version
win10 chrome

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/915/](https://jsfiddle.net/mmx38qxw/915/)

### Steps to reproduce
try to enter a space in el-select within el-menu

### What is Expected?
a space in el-select

### What is actually happening?
space is not working in el-select within el-menu
space is working outside el-menu

**Comment by Leopoldthecoder** [comment] 2018-03-26 08:16
Duplicate of #8812

**Closed by Leopoldthecoder** 2018-03-26 08:16 UTC
