### ISSUE TITLE
[Feature Request] expose $index when row-dblclick in Table

### ISSUE THREAD

**Issue by L-x-C** [ElemeFE/element#12919] opened 2018-09-28 02:27 UTC
### Existing Component
Yes

### Component Name
Table

### Description
expose $index when row-dblclick in Table
![image](https://user-images.githubusercontent.com/4329120/46184681-4ab07380-c309-11e8-9cd1-a523ec21475f.png)

**Comment by ziyoung** [comment] 2018-09-29 07:39
Duplicate of #7031

**Closed by ziyoung** 2018-09-29 07:39 UTC
