### ISSUE TITLE
The [Bug Report] Table component has left fixed columns and table-tail aggregate rows, and the scroll bar is blocked

### ISSUE THREAD

**Issue by Zhang-Yida** [ElemeFE/element#14853] opened 2019-03-27 01:30 UTC
### Element UI version
2.6.3

### OS/Browsers version
Ubuntu18.04/Google Chrome Version 73.0.3683.75 (Official Build) (64-bit)

### Vue version
2.5.19

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
为列表设置左侧多个固定列
为列表设置合计行
使固定列的整体列宽大于横向滚动条的长度

### What is Expected?
能够在固定列的区域进行横向拖动滚动条

### What is actually happening?
在固定列区域不能横向拖动滚动条，对非固定列进行横向滚动

![image](https://user-images.githubusercontent.com/17022452/55043833-ea5d7d00-5072-11e9-8dbf-ad0aaf66a8a8.png)

**Comment by ziyoung** [comment] 2019-04-04 07:03
Duplicate of #5415

**Closed by ziyoung** 2019-04-04 07:03 UTC
