### ISSUE TITLE
[Bug Report] tree component can not delete node

### ISSUE THREAD

**Issue by khty2000** [ElemeFE/element#12688] opened 2018-09-10 08:19 UTC
### Element UI version
2.4.6

### OS/Browsers version
chrome  65.0.3325.181 (64bit)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/8ousnvj4/](https://jsfiddle.net/8ousnvj4/)

### Steps to reproduce
clike delete button

### What is Expected?
the node should be deleted

### What is actually happening?
 the node is not deleted

**Comment by ziyoung** [comment] 2018-09-10 09:59
Duplicate of #12664

**Closed by ziyoung** 2018-09-10 09:59 UTC
