### ISSUE TITLE
[Bug Report] Table components enable fixed columns, drag and drop horizontal scroll bars, table expansion line display is incorrect

### ISSUE THREAD

**Issue by lky5230** [ElemeFE/element#9976] opened 2018-03-02 08:45 UTC
### Element UI version
2.2.0

### OS/Browsers version
win32/google chrome v64

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/bububu123321/ap4uywLs/7/](https://jsfiddle.net/bububu123321/ap4uywLs/7/)

### Steps to reproduce
1、Expand the table in one line
2、Drag and drag the lateral scroll bar to the right
3、The expansion area of the fixed column area covers the expansion area on the left

### What is Expected?
The expansion area is clearly visible

### What is actually happening?
The fixed column area shielded the open area

**Comment by Leopoldthecoder** [comment] 2018-03-02 10:07
Duplicate of #7311

**Closed by Leopoldthecoder** 2018-03-02 10:07 UTC
Labels: component: table
