### ISSUE TITLE
[Bug Report] table height ignores CSS variable expression

### ISSUE THREAD

**Issue by ScorpioX** [ElemeFE/element#15829] opened 2019-05-31 10:50 UTC
### Element UI version
2.9.1

### OS/Browsers version
Mac Chrome v74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/PvxdaX

### Steps to reproduce
- 在2.8版本中表格高度写成【height="calc(90vh - 280px)"】可以正常显示 滚动
- 升级到2.9之后表格高度变成自动，console显示 [Element Warn][ElTable]invalid height and it will be ignored.
- 改写成【style="height:calc(90vh - 280px);overflow-y:auto"】就又正常了，但滚动时表头也跟着滚跑了

### What is Expected?
Table文档描述：如果 height 为 string 类型，则这个高度会设置为 Table 的 style.height 的值。
calc(90vh - 280px)属于合法的CSS计算表达式，应该被当成string设置成style.height

### What is actually happening?
string类型的height貌似引入了合法性检查，导致CSS计算表达式被忽略。强制把height改成style，还需要处理滚动问题

**Comment by seymoe** [comment] 2019-06-03 12:03
+1

**Comment by ScorpioX** [comment] 2019-06-04 12:29
Just found a similar issue,【height="100%"】 is rendered as 【style="height:100px"】, please fix ASAP since this bug has caused dozens of issues in my application.

**Comment by mohankonyala** [comment] 2019-06-08 14:37
+1

**Comment by recursion123** [comment] 2019-06-11 02:20
+1

**Comment by ziyoung** [comment] 2019-06-12 06:35
Duplicate of #15806

**Closed by ziyoung** 2019-06-12 06:35 UTC
Labels: component: table
