### ISSUE TITLE
When trigger is added to the [Bug Report] form value type verification, the required rule verification can not pass

### ISSUE THREAD

**Issue by zsedcbm** [ElemeFE/element#8415] opened 2017-11-21 08:32 UTC
### Element UI version
1.4.10

### OS/Browsers version
win10/chrome 55

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/wukon/s0fuq8j4/](https://jsfiddle.net/wukon/s0fuq8j4/)

### Steps to reproduce
表单中有两个字段,age 和 age2,
age中的rule没有trigger
age2中的rule中包含trigger
当文本框中填入数字后,第一个验证通过,第二个提示"请输入排序号"

### What is Expected?
rule中设置trigger 不影响number类型的验证

### What is actually happening?
rule中设置trigger:"blur"时,输入数值的时候,required判断条件验证失败.

**Comment by Leopoldthecoder** [comment] 2017-11-21 09:53
Duplicate of #8386

**Closed by Leopoldthecoder** 2017-11-21 09:53 UTC
