### ISSUE TITLE
[Bug Report] After max-height is used to get the data, the height of the table cannot be automatically opened.

### ISSUE THREAD

**Issue by anick-xs** [ElemeFE/element#15485] opened 2019-05-09 09:00 UTC
### Element UI version
2.8.2

### OS/Browsers version
windows

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anick-xs/pen/QRyNzx

### Steps to reproduce
setting max-height

### What is Expected?
Automatic opening

### What is actually happening?
Not open

**Comment by YangYmimi** [comment] 2019-05-13 02:25
Same bug I met

**Comment by moonflyer** [comment] 2019-05-14 04:05
i mei the same bug!

**Comment by moonflyer** [comment] 2019-05-14 04:06
i met the same bug!

**Comment by moonflyer** [comment] 2019-05-14 04:07
> i met the same bug!

#15521 doesn't work for this problem

**Comment by liupl** [comment] 2019-05-14 08:08
> > i met the same bug!
> 
> #15521 doesn't work for this problem

Why? I think it can work normally here.

**Comment by moonflyer** [comment] 2019-05-16 08:33
> > > i met the same bug!
> > 
> > 
> > #15521 doesn't work for this problem
> 
> Why? I think it can work normally here.

Maybe the way i use to update my element is not right.
I just update the file node_modules/element-ui/packages/table/src/table.vue,then rebuild my nuxt job by `nuxt run generate`.Nothing changed at result.

**Comment by zdd2018** [comment] 2019-05-22 02:22
I have the same problem. Is there a solution?

**Comment by ziyoung** [comment] 2019-05-27 11:20
Duplicate of #15436

**Closed by ziyoung** 2019-05-27 11:20 UTC
