### ISSUE TITLE
[Bug Report] On Safari, when ElTable's inner content has scrollBar and ElButton in table row, table header columns are misaligned.

### ISSUE THREAD

**Issue by suyi91** [ElemeFE/element#11918] opened 2018-07-09 15:50 UTC
### Element UI version
2.4.3

### OS/Browsers version
MacOS 10.13.5 Safari Version 11.1.1 (13605.2.8)

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/p2wkmo4z/18/](https://jsfiddle.net/p2wkmo4z/18/)

### Steps to reproduce
1. Table's given height is smaller than the real height (=> there's vertical scrollbar in table)
2. ElButton in row.

### What is Expected?
All table header columns are not misaligned.

### What is actually happening?
All table header columns are misaligned.

The option header column is 80px but the option body column is 79.703125px(78.703125   1)

**Comment by jikkai** [comment] 2018-07-10 02:55
Duplicate of #11871

**Closed by jikkai** 2018-07-10 02:55 UTC
