### ISSUE TITLE
[Feature Request] Please add new component Control Sidebar

### ISSUE THREAD

**Issue by a0902m51** [ElemeFE/element#15304] opened 2019-04-27 16:47 UTC
### Existing Component
No

### Component Name
Control Sidebar

### Description
Like this: http://prntscr.com/nhn1y4
Thank Team!
Sorry if my request is excessive.

**Comment by troy351** [comment] 2019-04-28 02:49
I assume you need this https://www.iviewui.com/components/drawer

**Comment by ziyoung** [comment] 2019-05-07 07:52
Duplicate of #15030

**Closed by ziyoung** 2019-05-07 07:52 UTC
