### ISSUE TITLE
[Bug Report] Nested messagebox crashes in Safari

### ISSUE THREAD

**Issue by Bikkel007** [ElemeFE/element#11365] opened 2018-05-27 16:25 UTC
### Element UI version
2.3.9

### OS/Browsers version
macOS High Sierra 10.13.4 / Safari 11.1 (13605.1.33.1.2)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/b9zdhjkf/](https://jsfiddle.net/b9zdhjkf/)

### Steps to reproduce
1) Open the Fiddle in Safari: https://jsfiddle.net/b9zdhjkf/
2) Open the first MessageBox by clicking "Show"
3) Click on "Yes"

This problem was reported on mobile as well: https://github.com/ElemeFE/element/issues/11344?_pjax=%23js-repo-pjax-container

### What is Expected?
The second MessageBox should be shown until the user closes it.

### What is actually happening?
The second MessageBox appears briefly and then disappears while the rest of the page remains inactive.

**Comment by Leopoldthecoder** [comment] 2018-05-28 02:45
Duplicate of #10839

**Closed by Leopoldthecoder** 2018-05-28 02:45 UTC
