### ISSUE TITLE
1.0.0 switch 组件在form中文字不对齐

### ISSUE THREAD

**Issue by cyy0418** [ElemeFE/element#987] opened 2016-11-11 03:08 UTC
### ElementUI version
1.0.0
### OS/Browers version
 macOS/Chrome 54

### Vue version
2.0.0

### Reproduction Link
http://jsfiddle.net/cyy0418/mx02djte/

![image](https://cloud.githubusercontent.com/assets/2883079/20203044/1f03e4b4-a7ff-11e6-9111-94c5d7963731.png)

**Comment by Leopoldthecoder** [comment] 2016-11-11 03:18
Duplicate of #967

**Closed by Leopoldthecoder** 2016-11-11 03:18 UTC
