### ISSUE TITLE
[Bug Report] Select component randomly launch an "Uncaught TypeError: str.replace is not a function"

### ISSUE THREAD

**Issue by ReynerHL** [ElemeFE/element#7784] opened 2017-10-27 06:09 UTC
### Element UI version
2.0.0

### OS/Browsers version
Windows 10 / Version 62.0.3202.62 (Official Build) (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
This one is very hard to reproduce. Using your own example for the select component (https://jsfiddle.net/api/post/library/pure/) you can try switch in random order (I could not find an specific order but the bug appears after some attemps) and in at least 10 different selections, the bug should rise.

### What is Expected?
The select should allow us to switch no matter how many times we change it.

### What is actually happening?
After some randomly changes, it launches the following error:

Uncaught TypeError: str.replace is not a function
    at Object.trim (cs.js:34)
    at Object.getText (cs.js:128)
    at HTMLDocument.mousedown (cs.js:60)

The cs.js:34 has this code with the offending line:
ret = str.replace(/(^\s*)/, "");

**Comment by Leopoldthecoder** [comment] 2017-10-27 08:24
`cs.js` doesn't seem to be part of Element. Could you turn off all browser extensions and see if this error continues?

**Comment by ReynerHL** [comment] 2017-10-27 10:09
Thanks @Leopoldthecoder for take a look into this. I can confirm that the error does not appear in other browsers (Firefox and Edge). But after turning off all my extensions in chrome, it still showing on randomly. If you have already tested it (please give it more than 5 changes randomly) in chrome, and you can't reproduce the error, please feel free to close this ticket. Thanks again for your time.

**Comment by Leopoldthecoder** [comment] 2017-10-28 03:23
I tested again in Chrome and didn't reproduce the error, so perhaps this is not caused by Element. Closing this issue now.

**Closed by Leopoldthecoder** 2017-10-28 03:23 UTC

**Comment by wacky6** [comment] 2017-10-28 05:11
I guess it is caused by missing entries in locale file? cs = Czech language?

**Comment by ReynerHL** [comment] 2017-10-28 05:24
Thanks Jiewei Qian for take a look into it. Did you face the same issue? It
is something that hapens randomly, but if it only hapens in Chrome (I've
tested it in Edge and Firefox without problems), I just have to be agree
with @Leopoldthecoder in this might be caused by an extension, or something
related with my chrome version. Also, I've tested it directly from the
ElementUI examples in jsfiddle and I suppose they do not use any locale
there. In the other hand, I've never loaded any other language but Spanish,
but I suppose the examples didn't loaded it, and they fails in my stack.

Again, thanks for giving it a shot, I just hope it is a local problem, this
project is awesome.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by wacky6** [comment] 2017-10-28 08:19
I did encountered str.replace is undefined previously for missing locale entries. But I take a look at locales directory. There is no cs locale.
