### ISSUE TITLE
DisabledDate in [Bug Report] DateTimePicker can not be restricted by time and seconds.

### ISSUE THREAD

**Issue by liyangibex** [ElemeFE/element#13482] opened 2018-11-20 07:26 UTC
### Element UI version
2.4.2

### OS/Browsers version
win10 / chrome 

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/lyy116/eczfho0t/2/](https://jsfiddle.net/lyy116/eczfho0t/2/)

### Steps to reproduce
点击DateTimePicker 组件，选择日期和时间

在日期选择中设置了小于当前时间不能选择

### What is Expected?
设置disabledDate  之后时分秒也能被限制

### What is actually happening?
实际效果是小于当前日期不能选择，但是时分秒还是可以选择的

**Comment by ziyoung** [comment] 2018-11-20 12:00
Duplicate of #12701

**Closed by ziyoung** 2018-11-20 12:00 UTC
