### ISSUE TITLE
[Bug Report] when el-select close,blur method can't trigger

### ISSUE THREAD

**Issue by qiuyaofan** [ElemeFE/element#12841] opened 2018-09-20 10:37 UTC
### Element UI version
2.4.7

### OS/Browsers version
ios chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6169/](https://jsfiddle.net/mmx38qxw/6169/)

### Steps to reproduce
click to add tag,choose one or just blur,but blur event or method can't trigger,sometime trigger when focus

### What is Expected?
when el-select blur ,or select hide, can trigger the function

### What is actually happening?
can't trigger the function I want it trigger

**Comment by ziyoung** [comment] 2018-09-20 12:07
Duplicate of #12273

**Closed** 2018-09-20 12:08 UTC
