### ISSUE TITLE
[Bug Report] typescript error TS2300: Duplicate identifier'selectWhenUnmatched'

### ISSUE THREAD

**Issue by buckywt** [ElemeFE/element#11510] opened 2018-06-06 09:11 UTC
### Element UI version
2.4.0

### OS/Browsers version
windows / chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
ERROR in D:\work\Etherrum\ethbrowser-ts\node_modules\element-ui\types\autocomplete.d.ts
(60,3): error TS2300: Duplicate identifier 'selectWhenUnmatched'.
直接build编译失败

### What is Expected?
build编译成功

### What is actually happening?
直接build编译失败

**Comment by Leopoldthecoder** [comment] 2018-06-06 09:31
Duplicate of #11459

**Closed by Leopoldthecoder** 2018-06-06 09:31 UTC
