### ISSUE TITLE
[Bug Report] The computed property "fields" is already defined in data.

### ISSUE THREAD

**Issue by congpeijun** [ElemeFE/element#9105] opened 2018-01-03 02:48 UTC
### Element UI version
2.0.10

### OS/Browsers version
MacOS  / Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
使用vue webpack 模板
添加一个el-form组件

### What is Expected?
控制台应该无错误信息

### What is actually happening?
vue.esm.js?efeb:578 [Vue warn]: The computed property "fields" is already defined in data.

found in

---> &lt;ElForm&gt;

**Comment by Leopoldthecoder** [comment] 2018-01-03 05:12
Duplicate of #4720

**Closed by Leopoldthecoder** 2018-01-03 05:12 UTC
