### ISSUE TITLE
[Bug Report] date picker component can't sync value in render function

### ISSUE THREAD

**Issue by fliu2476** [ElemeFE/element#10895] opened 2018-04-26 04:15 UTC
### Element UI version
2.3.6

### OS/Browsers version
win 10 x64

### Vue version
2.5.10

### Reproduction Link
[https://jsfiddle.net/fliu2476/wr81tna0/](https://jsfiddle.net/fliu2476/wr81tna0/)

### Steps to reproduce
1. click button
2. set any value for date-picker

### What is Expected?
date-picker value should change when we select any value

### What is actually happening?
no change

**Comment by Leopoldthecoder** [comment] 2018-04-26 04:45
Duplicate of #8931

**Closed by Leopoldthecoder** 2018-04-26 04:45 UTC

**Comment by fliu2476** [comment] 2018-04-26 06:18
@Leopoldthecoder Is there any solution for this issue?

**Comment by Leopoldthecoder** [comment] 2018-04-26 06:44
Currently no. I suggest using a Dialog in this situation, because MessageBox is really just designed to replace `window.alert`, `window.confirm` and `window.prompt`.
