### ISSUE TITLE
[Bug Report] The table data has changed but Pagination no changed

### ISSUE THREAD

**Issue by xiongyizhu** [ElemeFE/element#11580] opened 2018-06-11 20:26 UTC
### Element UI version
2.3.9

### OS/Browsers version
windows 7 / Chrome/63.0

### Vue version
2.5.2

### Reproduction Link
[https://xiongyizhu.github.io/#/DesignCenter/TableDemo](https://xiongyizhu.github.io/#/DesignCenter/TableDemo)

### Steps to reproduce
1.复制第一行的姓名然后翻到最后一页

2.粘贴姓名到搜索框点击查询，没有查询到数据

1.Copy the  name from first line then go to the last page

2.Paste data to the search box then click query button，but no data    

My English is not good ，sorry

### What is Expected?
表格数据变化导致页码变化，应该触发current-change事件，触发后会再去查询一次

Changes in table data cause page number changes, and current-change events should be triggered then search again

### What is actually happening?
没有触发current-change，也没有改变vue实例中的page number，所以查不到数据

current-change events  was not triggered, and page number in the Vue instance was not changed too，then search no data

**Comment by jikkai** [comment] 2018-06-12 00:59
Duplicate of #11535

**Closed by jikkai** 2018-06-12 00:59 UTC

**Comment by xiongyizhu** [comment] 2018-06-12 02:09
为什么在旧版本中支持呢，比如1.4.13版本中就是支持的
例子：https://jsfiddle.net/mmx38qxw/2163/
点击变成一页按钮就触发了current-change事件，但是新版本不支持
