### ISSUE TITLE
[Bug Report] el-popover will appear repeated Popover on el-table-column with fixed attribute.

### ISSUE THREAD

**Issue by sq580** [ElemeFE/element#12916] opened 2018-09-27 11:46 UTC
### Element UI version
2.3.2

### OS/Browsers version
windows7

### Vue version
2.5.6

### Reproduction Link
[https://jsfiddle.net/1gz8a39j/](https://jsfiddle.net/1gz8a39j/)

### Steps to reproduce
在插槽reference中如果改变popover是否显示，那么popover就出现不了。此示例中，点击“删除”按钮出现了两个重叠的popover，如果去掉fixed=“right”就没问题了，有多少个fixed，popover就重叠多少个

### What is Expected?
在el-column中设置了fixed属性后el-popover能正常显示

### What is actually happening?
显示了多个重叠的el-popover

**Comment by ziyoung** [comment] 2018-09-28 11:16
Duplicate of #10588

**Closed by ziyoung** 2018-09-28 11:16 UTC
