### ISSUE TITLE
[Bug Report] After the build to the server found in the IE11 operating data page can not sync

### ISSUE THREAD

**Issue by tsungche** [ElemeFE/element#8853] opened 2017-12-16 04:09 UTC
### Element UI version
1.4.12

### OS/Browsers version
IE11

### Vue version
2.3.0

### Reproduction Link
[https://elementui.github.io](https://elementui.github.io)

### Steps to reproduce
http://13.113.168.53/alianAdmin

### What is Expected?
IE 11 is not work.

### What is actually happening?
I use npm run build release server, create data and update data can not be automatically synced to the page, chrome is OK and firefox is OK, IE 11 is not work. I found the problem it only called once back end

My web : http://13.113.168.53/alianAdmin

**Comment by Leopoldthecoder** [comment] 2017-12-16 13:15
Duplicate of #8851

**Closed by Leopoldthecoder** 2017-12-16 13:15 UTC
