### ISSUE TITLE
[Bug Report] TimePicker to set the format attribute, the Li element shows dislocation, not vertical center

### ISSUE THREAD

**Issue by mirari** [ElemeFE/element#4813] opened 2017-05-11 09:19 UTC
### Element UI version
1.3.2

### OS/Browsers version
Latest

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/xhb186fg/](https://jsfiddle.net/xhb186fg/)

### Steps to reproduce
Just click

### What is Expected?
正常显示

### What is actually happening?
li元素显示错位，字体没有垂直居中

**Comment by Leopoldthecoder** [comment] 2017-05-11 11:06
![image](https://cloud.githubusercontent.com/assets/10095631/25946253/df84a7f8-367c-11e7-925b-fa1b72ee3718.png)
Looks they are centered. What is your OS and browser?

**Comment by luciy** [comment] 2017-05-12 01:08
确实无法居中。
系统：macOS 10.12.4 
浏览器：chrome： 58.0.3029.110 
![Uploading AE6304E4-53C2-4828-82CF-221F2B73F063.png…]()

@Leopoldthecoder

**Comment by pengchongfu** [comment] 2017-05-12 01:30
![screenshot from 2017-05-12 09-07-49](https://cloud.githubusercontent.com/assets/13997305/25978076/888e8768-36f2-11e7-974f-77d2e8b7d8ad.png)

ubuntu 16.04 / 64 bit, chrome 58.0.3029.110 (64-bit)

I also test in macOS 10.12.4, chrome 58.0.3029.110 (64-bit), but it looks very normal. It is strange.

**Comment by mirari** [comment] 2017-05-12 02:08
@Leopoldthecoder 
Windows 10 1703 64bit
Chrome 58.0.3029.81 (64-bit)
FireFox 52.0.1 (64bit)
Microsoft Edge 40.15063.0.0
These browser got same problem on my os.
![qq 20170512100347](https://cloud.githubusercontent.com/assets/4995159/25979320/568a7f9e-36fa-11e7-9289-6514b3a0841c.jpg)

**Comment by Leopoldthecoder** [comment] 2017-05-13 03:38
I tested in:
- Chrome 58 on macOS 10.12.4
- Safari 10.1 on macOS 10.12.4
- Firefox 53 on macOS 10.12.4
- Chrome 58 on Windows 10
- Microsoft Edge on Windows 10
- Firefox 51 and 53 on Windows 10
- Microsoft IE 11 on Windows 10
and they are all centered. I have no access to ubuntu.

Could you figure out why they are not centered? It looks like a CSS problem. Send us a PR if you can. I really couldn't help because it cannot be reproduced in my machines.

**Comment by pengchongfu** [comment] 2017-05-13 05:35
I have test in:

- Chrome on Ubuntu 16.04
- Chrome on Windows 10
- Edge on Windows 10
- IE on Windows 10

the commit above can fix this problem.

**Comment by Leopoldthecoder** [comment] 2017-05-13 13:26
Hopefully this is fixed in #4847, which will be shipped in 1.3.3 tomorrow.

**Closed** 2017-05-13 13:26 UTC

**Comment by pengchongfu** [comment] 2017-05-13 13:37
I hope so..

**Comment by Leopoldthecoder** [comment] 2017-05-13 13:44
@pengchongfu So you tested that fix on ubuntu and numbers are centered?

**Comment by pengchongfu** [comment] 2017-05-13 14:24
@Leopoldthecoder , yes, It fixed in 4 browsers that I mentioned above. Before changed, the height of div was not `190px` but `175px`, so the number was not centered.

**Comment by Leopoldthecoder** [comment] 2017-05-13 14:31
@pengchongfu OK, thanks.
