### ISSUE TITLE
After the [Bug Report] datePicker component is assigned, the input box can not display the value correctly.

### ISSUE THREAD

**Issue by zhq195** [ElemeFE/element#10872] opened 2018-04-25 04:10 UTC
### Element UI version
2.3.6

### OS/Browsers version
IE10

### Vue version
2.5.0

### Reproduction Link
[https://jsfiddle.net/zhonghaiqing/7bswoaep/4/](https://jsfiddle.net/zhonghaiqing/7bswoaep/4/)

### Steps to reproduce
1、初始值为空，500毫秒之后给它赋值一个日期
2、日期组件输入框是空的
3、点击输入框出现日历表
4、日期组件输入框显示正确的值

### What is Expected?
延迟赋值之后日期组件能正确显示值

### What is actually happening?
延迟赋值之后日期组件不能正确显示值

**Comment by Leopoldthecoder** [comment] 2018-04-25 05:52
Duplicate of https://github.com/ElemeFE/element/issues/8548

**Closed by Leopoldthecoder** 2018-04-25 05:52 UTC
