### ISSUE TITLE
[Feature, Request], el-select, always, request, data, on, remote, setSelected, when, filterable,, and, remote, both, true

### ISSUE THREAD

**Issue by laozhujia** [ElemeFE/element#6384] opened 2017-08-10 02:58 UTC
### Existing Component
是

### Component Name
el-select

### Description
el-select request again after setSelected when remote
select/src/select 

    setSelected() {
        if (!this.multiple) {
          let option = this.getOption(this.value);
          if (option.created) {
            this.createdLabel = option.currentLabel;
            this.createdSelected = true;
          } else {
            this.createdSelected = false;
          }
          this.selectedLabel = option.currentLabel;
          this.selected = option;
          // change line 404 if (this.filterable) this.query = this.selectedLabel;
          if (this.filterable && !this.remote) this.query = this.selectedLabel
          return;
        }
        let result = [];
        if (Array.isArray(this.value)) {
          this.value.forEach(value => {
            result.push(this.getOption(value));
          });
        }
        this.selected = result;
        this.$nextTick(() => {
          this.resetInputHeight();
        });
      },
  
     visible(val) {
        if (!val) {
          this.$refs.reference.$el.querySelector('input').blur();
          this.handleIconHide();
          this.broadcast('ElSelectDropdown', 'destroyPopper');
          if (this.$refs.input) {
            this.$refs.input.blur();
          }
          // line 285  this.query = '';
          if (!this.remote) {
            this.query = '';
          } else if (this.multiple) {
            // hide this.$refs.input
          }
          this.selectedLabel = '';
          this.inputLength = 20;
          this.resetHoverIndex();
          this.$nextTick(() => {
            if (this.$refs.input &&
              this.$refs.input.value === '' &&
              this.selected.length === 0) {
              this.currentPlaceholder = this.cachedPlaceHolder;
            }
          });
          if (!this.multiple) {
            if (this.selected) {
              if (this.filterable && this.allowCreate &&
                this.createdSelected && this.createdOption) {
                this.selectedLabel = this.createdLabel;
              } else {
                this.selectedLabel = this.selected.currentLabel;
              }
              // change  if (this.filterable) this.query = this.selectedLabel; 
              if (this.filterable && !this.remote) this.query = this.selectedLabel;
            }
          }
        } else {
          this.handleIconShow();
          this.broadcast('ElSelectDropdown', 'updatePopper');
          if (this.filterable) {
            // change
            if (!this.remote) {
              this.query = this.selectedLabel;
            } else if (this.multiple) {
              // show this.$refs.input
            }
            if (this.multiple) {
              this.$refs.input.focus();
            } else {
              if (!this.remote) {
                this.broadcast('ElOption', 'queryChange', '');
                this.broadcast('ElOptionGroup', 'queryChange');
              }
              this.broadcast('ElInput', 'inputSelect');
            }
          }
        }
        this.$emit('visible-change', val);
      },

**Comment by Leopoldthecoder** [comment] 2017-08-10 03:01
Duplicate of #2265

**Closed by Leopoldthecoder** 2017-08-10 03:01 UTC
