### ISSUE TITLE
[bug report] navmenu is a recursive component. When navmenu is folded and the mouse floats to submenu, the console will report uncaught rangeerror: maximum call stack size exceeded

### ISSUE THREAD

**Issue by tostack** [ElemeFE/element#21097] opened 2021-06-23 06:29 UTC
### Element UI version
2.15.2

### OS/Browsers version
win10/chrome 91.0.4472.106（正式版本） （64 位）

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/tostack/pen/JjWQGGz

### Steps to reproduce
点击 ‘收起’，然后将鼠标移动到NavMenu中的submenu的位置，F12，查看控制台，你将看到
Uncaught RangeError: Maximum call stack size exceeded.
    at VueComponent.handleMouseenter (index.js:1)
    at invokeWithErrorHandling (vue.js:1872)
    at HTMLLIElement.invoker (vue.js:2197)
    at HTMLLIElement.original._wrapper (vue.js:7591)
    at VueComponent.handleMouseenter (index.js:1)
    at invokeWithErrorHandling (vue.js:1872)
    at HTMLLIElement.invoker (vue.js:2197)
    at HTMLLIElement.original._wrapper (vue.js:7591)
    at VueComponent.handleMouseenter (index.js:1)
    at invokeWithErrorHandling

### What is Expected?
控制台中不再出现 Maximum call stack size exceeded.之类的错误

### What is actually happening?
当点击‘展开’的时候，鼠标移入到submenu或menu-item中时，程序能正常运行，但是点击‘收起’时，鼠标再移动到submenu或menu-item中时，控制台会报错 “Uncaught RangeError: Maximum call stack size exceeded.”，虽然程序能正常交互，但控制台中的错误还是让人有些担心的。

**Comment by tostack** [comment] 2021-06-23 06:33
thank for your any help

**Comment by definiteIymaybe** [comment] 2021-08-01 23:50
Looks like #17960.

**Comment by tostack** [comment] 2021-08-03 01:21
> Looks like #17960.

It does seem so.

**Comment by definiteIymaybe** [comment] 2021-08-14 12:00
> It does seem so.

Then I suggest you close the issue and follow it there, no need to create duplicates.

**Comment by cs1707** [comment] 2021-09-24 08:38
Duplicate of #17960

**Closed by cs1707** 2021-09-24 08:38 UTC
