### ISSUE TITLE
[Feature Request] select component's items size

### ISSUE THREAD

**Issue by movesan** [ElemeFE/element#12511] opened 2018-08-27 03:17 UTC
### Existing Component
是

### Component Name
select

### Description
Here is a issue,If one of the select item is so long,I can't see the other shorter items,So can you do a favor of it?
![select_issue](https://user-images.githubusercontent.com/16206967/44638666-bb066500-a9ea-11e8-86a0-1944942e79dc.png)

**Comment by wacky6** [comment] 2018-08-27 03:34
In this case, you should fix the option that is too long.

**Comment by ziyoung** [comment] 2018-08-27 04:12
Duplicate of #9352

**Closed by ziyoung** 2018-08-27 04:12 UTC
