### ISSUE TITLE
[Bug Report] tabular controls roll tables when rendering large amounts of data.

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/element#13075] opened 2018-10-17 08:15 UTC
### Element UI version
2.4.8

### OS/Browsers version
Chrome

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/rwf79L1h/1/](https://jsfiddle.net/rwf79L1h/1/)

### Steps to reproduce
拖动滚动条

### What is Expected?
丝般顺滑的滚动

### What is actually happening?
十分卡顿

**Comment by LastHeaven** [comment] 2018-10-17 08:17
建议可以参考下这个
https://github.com/lison16/vue-bigdata-table

**Comment by porcelainHeart** [comment] 2018-10-17 08:49
Pagination

**Comment by ziyoung** [comment] 2018-10-26 09:47
使用虚拟列表能有效提升性能。那么大的数据，你还是先分页吧。

**Comment by ziyoung** [comment] 2018-10-26 09:47
Duplicate of #4359

**Closed by ziyoung** 2018-10-26 09:47 UTC
