### ISSUE TITLE
[Bug Report] can't focus on input as expected with tab, requiring tabIndex features.

### ISSUE THREAD

**Issue by onemans-battle** [ElemeFE/element#12862] opened 2018-09-23 10:49 UTC
### Element UI version
2.4.7

### OS/Browsers version
chrome 69.0.3497.100

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/fdxsaSxzs/re065x1g/15/](https://jsfiddle.net/fdxsaSxzs/re065x1g/15/)

### Steps to reproduce
1.点击第一个输入框
2.依次按tab键
3.会聚焦到输入框按钮上

### What is Expected?
tab键只在输入框之间聚焦

### What is actually happening?
tab键会聚焦到输入框中的tooltip和按钮button

**Comment by ziyoung** [comment] 2018-09-25 03:02
Duplicate of #11875

**Closed by ziyoung** 2018-09-25 03:02 UTC
