### ISSUE TITLE
[feature request] form attribute: hide required asterisk Chinese description error

### ISSUE THREAD

**Issue by HuLuoQian** [ElemeFE/element#20951] opened 2021-04-21 06:12 UTC
### Existing Component
是

### Component Name
form

### Description
form 属性：hide-required-asterisk 中文描述为 “是否显示必填字段的标签旁边的红色星号”， 应该是 “是否隐藏必填字段的标签旁边的红色星号”

**Comment by SummerGua** [comment] 2021-04-22 03:25
fixed in pr #20953

**Comment by cs1707** [comment] 2021-06-08 12:09
Duplicate of #21028

**Closed by cs1707** 2021-06-08 12:09 UTC
