### ISSUE TITLE
[Bug Report] Popover does not stay open

### ISSUE THREAD

**Issue by matthagemann** [ElemeFE/element#8193] opened 2017-11-12 23:19 UTC
### Element UI version
2.0.4

### OS/Browsers version
Mac / Chrome 62.0.3202.89

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
Click button "click to activate".

### What is Expected?
Popover is expected to stay open.

### What is actually happening?
Popover does not stay open and closes immediately. Only the 2nd attempt will keep it open.

**Comment by pxljoy** [comment] 2017-11-12 23:56
I have this issue on Chrome with buttons.
It seems the first click "focuses" the button, and any clicks after that _actually_ activate it.

This problem seems to not appear on Safari, I have yet to test it on Firefox.

**Comment by 1550465387** [comment] 2017-11-13 02:11
I've also had this problem, and I hope I'll be able to deal with the first flash bug as quickly as possible. Be consistent with 1.4.9. I just moved around and met a lot of bug. There are tree controls setChecked third parameters set to true subclasses can not choose, hoping to quickly solve. I used a lot of trees.

**Comment by conanliuhuan** [comment] 2017-11-13 03:07
我也遇到了这个BUG，Popover的“点击显示”在首次点击的时候会一闪而过

**Comment by Leopoldthecoder** [comment] 2017-11-13 03:19
Duplicate of #8186

**Closed by Leopoldthecoder** 2017-11-13 03:19 UTC
