### ISSUE TITLE
[Feature Request] Skeleton Screen

### ISSUE THREAD

**Issue by fx1422** [ElemeFE/element#17039] opened 2019-08-15 02:32 UTC
### Existing Component
否

### Component Name
Skeleton Screen

### Description
Can you add a new feature？Skeleton Screen

**Comment by ArtemSyzonenko** [comment] 2019-08-17 16:13
https://github.com/ElemeFE/element/issues/12968

**Comment by ziyoung** [comment] 2019-09-04 02:54
Duplicate of #12968

**Closed** 2019-09-04 02:54 UTC
