### ISSUE TITLE
[Bug Report] Table cells and table headers have misalignment on Safari(Mac OS)

### ISSUE THREAD

**Issue by 07akioni** [ElemeFE/element#12587] opened 2018-09-03 06:18 UTC
### Element UI version
2.4.6

### OS/Browsers version
Mac OS High Serria / Safari 11.1 (13605.1.33.1.4)

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/rcnu9f42/26/](https://jsfiddle.net/rcnu9f42/26/)

### Steps to reproduce
Use Safari to open that link.

### What is Expected?
Table cells' border are aligned with table headers' border

### What is actually happening?
Table cells' border and table headers' border have misalignment.

**Comment by ziyoung** [comment] 2018-09-29 04:38
Duplicate of #10308

**Closed by ziyoung** 2018-09-29 04:38 UTC
Labels: component: table, type: bug
