### ISSUE TITLE
[Bug Report]failed to lint css

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#11657] opened 2018-06-18 09:12 UTC
### Element UI version
the newest

### OS/Browsers version
all

### Vue version
the newest

### Reproduction Link
none

### Steps to reproduce
1. npm run lint
2. failed to lint

![image](https://user-images.githubusercontent.com/1060733/41525202-c2ef6b2c-7312-11e8-9afc-7c9653a23049.png)

**Comment by jikkai** [comment] 2018-06-18 11:27
Duplicate of #11343

**Closed by jikkai** 2018-06-18 11:27 UTC
