### ISSUE TITLE
[Bug Report] type="week" does not select startDate of week.

### ISSUE THREAD

**Issue by zap-mueda** [ElemeFE/element#11206] opened 2018-05-17 05:13 UTC
### Element UI version
2.3.8

### OS/Browsers version
OS X 10.11.6 / google chrome 66.0.3359.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/ms50he6d/](https://jsfiddle.net/ms50he6d/)

### Steps to reproduce
1.click week date-picker
2. change other week
3. value become second date of week

### What is Expected?
to select start date of week.

### What is actually happening?
data-picker which type is week does not select start date of week.
please show Reproduction Link and select date of week data-picker.  when you select other week, v-modal's value is second date of week.

**Comment by Leopoldthecoder** [comment] 2018-05-17 05:32
Duplicate of #6754

**Closed by Leopoldthecoder** 2018-05-17 05:32 UTC
