### ISSUE TITLE
[Bug Report] DatePicker and DateTimePicker can not use when set it type to DateRange or DateTimeRage

### ISSUE THREAD

**Issue by carldai0106** [ElemeFE/element#7819] opened 2017-10-28 14:20 UTC
### Element UI version
2.0.1

### OS/Browsers version
Windows 10 / Chrome 57.0.2987.98 (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
When I check official demo I found it.
http://element-cn.eleme.io/2.0/#/zh-CN/component/datetime-picker
http://element-cn.eleme.io/2.0/#/zh-CN/component/date-picker
Scroll these pages to Date Range or Date Time Rage, then to pick date, you can find it is no use.

### What is Expected?
can pick a date range and date time range

### What is actually happening?
I can not pick a date range or date time range.

**Comment by wacky6** [comment] 2017-10-28 14:23
Possible duplicate of https://github.com/ElemeFE/element/issues/7539

**Comment by carldai0106** [comment] 2017-10-28 14:29
@wacky6 
I do not think it is a duplicate problem.
because the version 1.4.8 is can use. Just the newest version can not use.

**Comment by Leopoldthecoder** [comment] 2017-10-29 02:54
This is a dup of #7539 

Our website for 1.4.8 uses Vue 2.3.0, while 2.0 uses Vue 2.5.2. I believe they'll work if you downgrade Vue to 2.4.x in your project.

**Closed by Leopoldthecoder** 2017-10-29 02:54 UTC

**Comment by leeqqiang** [comment] 2017-11-15 07:16
@carldai0106 
你这个问题咋解决的

**Comment by leeqqiang** [comment] 2017-11-15 08:19
@carldai0106 哥们 我也遇到这个问题了 给控件加了个:key key值根据type变化就好了
