### ISSUE TITLE
[Bug Report] the el-uplaod drag component report an warn when the file upload success

### ISSUE THREAD

**Issue by Zohar727** [ElemeFE/element#5960] opened 2017-07-20 07:00 UTC
### Element UI version
1.3.7

### OS/Browsers version
mac/chrome 59.0.3071.115

### Vue version
2.3.3

### Reproduction Link
[http://jsrun.net/tcYKp?jsfiddle](http://jsrun.net/tcYKp?jsfiddle)

### Steps to reproduce
open console window, upload any pan file ,when the file upload success ,you will see the warn message on the console window

### What is Expected?
no warn message

### What is actually happening?
report warn message: vue.js:465 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in
 
### at last:
I have try to alter element source code (the file path: node_modules/element-ui/lib/element-ui.common.js) 
in the line 21187 : change code to :  " key : file   '' "  ,then this warn message will disappear, but I think it isn't the best solution

**Comment by Leopoldthecoder** [comment] 2017-07-20 07:06
Duplicate of #5868

**Closed by Leopoldthecoder** 2017-07-20 07:06 UTC
