### ISSUE TITLE
[Bug Report] Table tables cannot scroll horizontally within a fixed column area when they have fixed columns and aggregate columns

### ISSUE THREAD

**Issue by jjxy1213** [ElemeFE/element#14239] opened 2019-01-28 03:10 UTC
### Element UI version
2.5.2

### OS/Browsers version
win7/google

### Vue version
2.6.0-beta.2

### Reproduction Link
[https://jsfiddle.net/1r5wdgku/3/](https://jsfiddle.net/1r5wdgku/3/)

### Steps to reproduce
横向滚动条在左侧固定列内按住无法滚动，
横向滚动条在固定列外按住拖动可滚动。
（不加合计栏时可以滚动）

### What is Expected?
滚动条在固定列内拖动也可滚动

### What is actually happening?
滚动条在固定列内拖动无法滚动

**Comment by ziyoung** [comment] 2019-04-22 06:54
Duplicate of #12666

**Closed by ziyoung** 2019-04-22 06:54 UTC
