### ISSUE TITLE
Can [Feature Request] InputNumber support the formatting of the input numbers plus the semicolon?

### ISSUE THREAD

**Issue by cuivip** [ElemeFE/element#12361] opened 2018-08-14 11:41 UTC
### Existing Component
是

### Component Name
InputNumber 

### Description
将输入的数字格式化，类似于这个 https://www.iviewui.com/components/input-number 组件的数字格式化功能

**Comment by jikkai** [comment] 2018-08-14 11:45
Duplicate of #9961

**Closed by jikkai** 2018-08-14 11:45 UTC
