### ISSUE TITLE
[Bug Report] Tree component item loses checkmark and node-key is change after drag&drop 

### ISSUE THREAD

**Issue by zyt2016** [ElemeFE/element#12220] opened 2018-08-03 09:37 UTC
### Element UI version
2.4.0

### OS/Browsers version
win10-64/Chrome-68.0.3440.84

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/L5gm34jr/12/](https://jsfiddle.net/L5gm34jr/12/)

### Steps to reproduce
1、First check one item,
2、Drag & drop it to a different position.

### What is Expected?
1、The dragged item should stay checked state.
2、The node-key of the node-drop event parameter draggingNode not change.

### What is actually happening?
1、The dragged item losed checked state.
2、The node-key of the node-drop event parameter draggingNode has changed that can't reset the checked state.

**Comment by ziyoung** [comment] 2018-08-03 10:13
Duplicate of #11927

**Closed by ziyoung** 2018-08-03 10:13 UTC
