### ISSUE TITLE
[Bug Report] DatePicker in type=daterange, in the 360 browser can not pick the date, the impact is great

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#7839] opened 2017-10-30 07:35 UTC
### Element UI version
2.0.1

### OS/Browsers version
360Browser   v8.1.1.406 

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Lv6w8d1q/](https://jsfiddle.net/Lv6w8d1q/)

### Steps to reproduce
点击打开DatePicker > 点选时间段 > 无法点击和响应

### What is Expected?
选中日期并得出响应的时间段结果

### What is actually happening?
无法选中

**Comment by Leopoldthecoder** [comment] 2017-10-30 07:39
Duplicate of #7539. Please wait for our next release.

**Closed by Leopoldthecoder** 2017-10-30 07:39 UTC
