### ISSUE TITLE
[Bug Report] Cascader, when the three-level values of options are the same, does not display the selected results

### ISSUE THREAD

**Issue by zhuyuejianke** [ElemeFE/element#16619] opened 2019-07-18 09:44 UTC
### Element UI version
2.10.0

### OS/Browsers version
chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/voYZEp?editors=1111

### Steps to reproduce
选择 指南>设计原则>1致

### What is Expected?
选择成功，并且显示选中结果

### What is actually happening?
并未显示选中结果，而是显示为空白；

**Comment by boomler** [comment] 2019-07-18 12:19
It may caused by `packages/cascader-panel/src/store.js`，
It caches nodes here:
`  initNodes(data) {
    data = coerceTruthyValueToArray(data);
    this.nodes = data.map(nodeData => new Node(nodeData, this.config));
    this.flattedNodes = this.getFlattedNodes(false, false);
    this.leafNodes = this.getFlattedNodes(true, false);
  }`

And find matched nodes by `value`: 
`  getNodeByValue(value) {
    if (value) {
      value = Array.isArray(value) ? value[value.length - 1] : value;
      const nodes = this.getFlattedNodes(false, !this.config.lazy)
        .filter(node => node.value === value);
      return nodes && nodes.length ? nodes[0] : null;
    }
    return null;
  }`

**Comment by LeeeMooo** [comment] 2019-07-23 01:37
实际项目中,出现相同value的情况还是很多的

**Comment by SimonaliaChen** [comment] 2019-07-25 03:34
Fixed in #15935

**Closed by SimonaliaChen** 2019-07-25 03:34 UTC

**Comment by lianzhao** [comment] 2019-07-30 06:12
not fixed in 2.10.1
https://codepen.io/anon/pen/EqWXQN?editors=1111#anon-login

**Comment by SimonaliaChen** [comment] 2019-07-30 06:16
> not fixed in 2.10.1
> https://codepen.io/anon/pen/EqWXQN?editors=1111#anon-login

Fixed in 2.11
