### ISSUE TITLE
[Feature Request] tree component allow-drop parameter supplement

### ISSUE THREAD

**Issue by volvor** [ElemeFE/element#10782] opened 2018-04-19 06:37 UTC
### Existing Component
是

### Component Name
tree

### Description
1.allow-drop现在的参数无法区分是拖到指定元素的下方还是内部,需要参数被拖拽节点的放置位置（before、after、inner）
2.拖动无法在两个tree组件之间进行

**Comment by Leopoldthecoder** [comment] 2018-04-19 08:12
1. Duplicate of https://github.com/ElemeFE/element/issues/10687
2. We have no plan to support this feature

**Closed by Leopoldthecoder** 2018-04-19 08:13 UTC
