### ISSUE TITLE
The show-overflow-tooltip attribute in [Bug Report] el-table-column, where the tip in the view is on other lines, cannot copy the contents

### ISSUE THREAD

**Issue by Even-Lau** [ElemeFE/element#14199] opened 2019-01-24 06:55 UTC
### Element UI version
0.1.0

### OS/Browsers version
chrome 74

### Vue version
2.6.0-beta.1

### Reproduction Link
[http://www.jsfiddle.net](http://www.jsfiddle.net)

### Steps to reproduce
el-table-column中加上show-overflow-tooltip属性

### What is Expected?
光标可以移到tip中且复制tip中的内容

### What is actually happening?
光标无法移动到tip中，且无法复制tip中的内容

**Comment by proceduremonkey** [comment] 2019-01-29 01:56
Have you solved it?

**Comment by ziyoung** [comment] 2019-03-25 03:40
Duplicate of #13576

**Closed by ziyoung** 2019-03-25 03:40 UTC

**Comment by Even-Lau** [comment] 2019-03-28 01:37
Nope. I don't think the author realy understands what I am talking about. @Fight-for-Freedom2019 
I mean:
`<el-table-column
            prop="read_length"
            label="read_length"
            show-overflow-tooltip>
          </el-table-column>`,
not:
`<el-table-column
                          prop="i5_index"
                          label="i5_index"
                          min-width="120">
                          <template slot-scope="scope">
                            <el-tooltip effect="dark" :content="scope.row.i5_index"
                                        placement="top">
                              <span>{{ scope.row.i5_index }}</span>
                            </el-tooltip>
                          </template>
                        </el-table-column>`
Open the issue, please. @ziyoung
