### ISSUE TITLE
new ui component treeselect / select cascade

### ISSUE THREAD

**Issue by gendalf** [ElemeFE/element#1548] opened 2016-12-04 13:47 UTC
It would be very nice to see such components in the arsenal

https://fe-driver.github.io/vue-beauty/#!/components/treeSelect

https://fe-driver.github.io/vue-beauty/#!/components/cascader

**Comment by Leopoldthecoder** [comment] 2016-12-05 12:35
Duplicate of #76 and #271 , we'll update in those two issues.

**Closed by Leopoldthecoder** 2016-12-05 12:35 UTC
