### ISSUE TITLE
[Bug Report] In the IE browser，el-pagination can not change page number when  you use Enter key in the input tag of pagination for the second time

### ISSUE THREAD

**Issue by a2886015** [ElemeFE/element#13559] opened 2018-11-26 06:24 UTC
### Element UI version
2.4.11

### OS/Browsers version
win10 64bit

### Vue version
2.5.17

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
Use IE browser to enter  http://element-cn.eleme.io/#/zh-CN/component/pagination，focus on the taglabel of el-pagination, enter the new number, and press the enter key,  you can change the page number successfully the first time. However，then enter the new number,  press the enter key again, you can not modify the page number successfully

### What is Expected?
modify the issue,we can change the page number successfully everytime we press the Enter key

### What is actually happening?
we can change the page number successfully only the first time we press the Enter key

**Comment by ziyoung** [comment] 2018-11-26 09:00
Duplicate of #11710

**Closed by ziyoung** 2018-11-26 09:00 UTC
