### ISSUE TITLE
[Bug Report] Dynamically change the table column width, the table width calculation error

### ISSUE THREAD

**Issue by gusumuzhe** [ElemeFE/element#9542] opened 2018-01-30 02:46 UTC
### Element UI version
1.4.13

### OS/Browsers version
MacOS 10.12.6 / Chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/254/](https://jsfiddle.net/mmx38qxw/254/)

### Steps to reproduce
change the width 180 to 18

### What is Expected?
the second column width will be set to 18

### What is actually happening?
the table width was set to 1.80182e 07px

**Comment by furybean** [comment] 2018-01-30 04:11
This is a known issue. Add number modifier to v-model will make it work correctly. 
https://jsfiddle.net/mmx38qxw/255/

**Comment by furybean** [comment] 2018-01-30 04:21
Closed because of this issue is duplicate of #4331. Please track that issue's progress.

**Comment by furybean** [comment] 2018-01-30 04:21
Closed because of this issue is duplicate of #4331. Please track that issue's progress.

**Closed by furybean** 2018-01-30 04:21 UTC

**Comment by Oakerin** [comment] 2018-06-25 06:56
Sorry, but how can I read #4331 in Chinese?
