### ISSUE TITLE
[Bug Report] why new version（2.4.11）removed field url in el-upload “on-change” hook?

### ISSUE THREAD

**Issue by svenjia** [ElemeFE/element#13860] opened 2018-12-24 07:02 UTC
### Element UI version
2.4.11

### OS/Browsers version
Chrome  71.0.3578.80

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/gqxv53pr/1/](https://jsfiddle.net/gqxv53pr/1/)

### Steps to reproduce
1.change a local image ,
2.see the console of on-change hook,
3.the file didnt contain filed 'url',
4,change the version form 2.4.11 to 2.3.9,then repeat the above step，you can see the on-change file contain 'url' filed.

i have checked the releases logs,but there is nothing about this. i know i can use URL.createObjectURL(file.raw) ,but it's really not a good experience for me!
 can you guys explain why remove 'url' filed in file when on-change happen?

### What is Expected?
'url' filed can be finded in file

### What is actually happening?
file params dont contanin url field

**Comment by siberiadev** [comment] 2018-12-29 16:34
Yeah, this is a big problem for our project too. So we just can use old version.

**Comment by elfman** [comment] 2018-12-30 06:46
Duplicate of #12934

**Closed by elfman** 2018-12-30 06:46 UTC
