### ISSUE TITLE
[Bug Report] el-input-number when v-model="item" where item = 0, the value not show by default

### ISSUE THREAD

**Issue by douxc** [ElemeFE/element#10721] opened 2018-04-16 02:30 UTC
### Element UI version
2.3.4

### OS/Browsers version
windows10 /  65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/dofrk09z/18/](https://jsfiddle.net/dofrk09z/18/)

### Steps to reproduce
just open link

### What is Expected?
when open the link, el-input-number should show like  "- 0 \+"

### What is actually happening?
it just show "-  \+"
![image](https://user-images.githubusercontent.com/7553076/38787548-2eb2f0f6-4161-11e8-8568-2ca288e24246.png)

**Comment by Leopoldthecoder** [comment] 2018-04-16 02:32
Duplicate of #10713

**Closed by Leopoldthecoder** 2018-04-16 02:32 UTC
