### ISSUE TITLE
[Bug Report] el-date-picker cause DOM error in chrome

### ISSUE THREAD

**Issue by Nununene** [ElemeFE/element#10259] opened 2018-03-20 09:25 UTC
### Element UI version
2.2.2

### OS/Browsers version
windows8 chrome 64.0.3282.186

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/uepyfosd/22/](https://jsfiddle.net/uepyfosd/22/)

### Steps to reproduce
* Create 2 el-date-picker with el-input(type=password) at same page
* Error occurs

### What is Expected?
No warning or error message

### What is actually happening?
[DOM] Found 2 elements with non-unique id #:
![element_error](https://user-images.githubusercontent.com/7614818/37646064-8fcee196-2c63-11e8-9fa4-7cbb4deee33b.png)

**Comment by Leopoldthecoder** [comment] 2018-03-20 09:38
Duplicate of #8907

**Closed by Leopoldthecoder** 2018-03-20 09:38 UTC
