### ISSUE TITLE
When the [Bug Report] Select component is used in the dialog component, click the pop-up layer on the tab to shake the text down

### ISSUE THREAD

**Issue by luciy** [ElemeFE/element#4882] opened 2017-05-16 07:21 UTC
### Element UI version
1.3.3

### OS/Browsers version
macOS/windows 7    chrome 58

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/aLhftyq3/](https://jsfiddle.net/aLhftyq3/)

### Steps to reproduce
点击 “打开嵌套表单的 Dialog”  选择弹出层中的 select， 观察弹出层内文字内容会变模糊。

### What is Expected?
select 的选择不会影响 弹出层的展示。

### What is actually happening?
select 的选择会导致 弹出层内文字内容变模糊。

**Comment by luciy** [comment] 2017-05-16 08:48
更新啦！

**Comment by Leopoldthecoder** [comment] 2017-05-18 03:18
Duplicate of #2461. You can join the discussion there, and since we haven't found the cause for this problem, you're welcome to contribute.

**Closed by Leopoldthecoder** 2017-05-18 03:18 UTC
