### ISSUE TITLE
[Bug Report] el-select window wobble

### ISSUE THREAD

**Issue by cmlgzhang** [ElemeFE/element#13175] opened 2018-10-25 11:16 UTC
### Element UI version
2.4.6

### OS/Browsers version
win10 /QQ browser

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/6711/](https://jsfiddle.net/mmx38qxw/6711/)

### Steps to reproduce
Window shaking occurs when multiple candidates are selected.

### What is Expected?
No window wobble is required.

### What is actually happening?
window wobble

**Comment by ziyoung** [comment] 2018-10-25 12:06
Can't reproduce.

**Comment by ziyoung** [comment] 2018-10-25 12:07
Duplicate of #13173

**Closed by ziyoung** 2018-10-25 12:07 UTC
Labels: need: description
