### ISSUE TITLE
In the case of 500 rows * 5 columns of the [Bug Report] table, the input box in the table enters Carton

### ISSUE THREAD

**Issue by shrekjxf** [ElemeFE/element#15970] opened 2019-06-07 12:45 UTC
### Element UI version
2.9.1

### OS/Browsers version
谷歌浏览器

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/davisjiang/pen/byPOMe

### Steps to reproduce
节点多的情况下，500行*5列，表格内输入框输入卡顿，输入比较快的情况下

### What is Expected?
输入无卡顿

### What is actually happening?
节点多的情况下，500行*5列，表格内输入框输入卡顿，输入比较快的情况下

**Comment by ziyoung** [comment] 2019-06-10 02:39
Duplicate of #6089

**Closed by ziyoung** 2019-06-10 02:39 UTC
