### ISSUE TITLE
[Bug Report] el-tabs component style is problematic. There is no blue underside under the selected tab heading

### ISSUE THREAD

**Issue by sds0917** [ElemeFE/element#14235] opened 2019-01-28 01:34 UTC
### Element UI version
2.5.2

### OS/Browsers version
Windows 10/Chrome/71.0.3578.98

### Vue version
2.5.16

### Reproduction Link
[https://elementui.github.io/issue-generator](https://elementui.github.io/issue-generator)

### Steps to reproduce
el-tabs组件样式有问题，选中的tab标题下没有蓝色下边线，已验证整个2.5.x系列都有此问题，2.4.x等没有问题。

### What is Expected?
选中的tab标题下有蓝色下边线
![qq 20190128093017](https://user-images.githubusercontent.com/7779851/51809956-bd455600-22df-11e9-8f1e-8749c62a2f83.png)

### What is actually happening?
选中的tab标题下没有蓝色下边线
![qq 20190128092741](https://user-images.githubusercontent.com/7779851/51809950-b1f22a80-22df-11e9-851f-a3c4179ecd89.png)

**Comment by island205** [comment] 2019-01-28 02:03
Duplicate of #14236

**Closed by island205** 2019-01-28 02:03 UTC
