### ISSUE TITLE
[Bug Report] Safari OS X: once a Select's menu was opened only the Select's upper half remains interactive

### ISSUE THREAD

**Issue by jri** [ElemeFE/element#4555] opened 2017-04-30 15:58 UTC
### Element UI version
1.2.9

### OS/Browsers version
OS X 10.11.6 / Safari 10.1

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/c1amumsp/6/](https://jsfiddle.net/c1amumsp/6/)

### Steps to reproduce
The jsfiddle displays a Select component.

1. Click the Select to open its menu.

2. **Click it again to close the menu**.

3. Now hover with the mouse over the Select. You'll see the pointer cursor appearing only in the Select's upper half. The Select's lower half does not respond to mouse clicks anymore.

Note: the problem does not occur in Chrome or Firefox. It occurs only in Safari.

### What is Expected?
After closing the Select's menu the entire Select is still expected to react to mouse clicks.

### What is actually happening?
After closing the Select's menu only the Select's upper half can be used to open the menu again. The lower half does not respond to mouse clicks anymore. No pointer cursor appears.

**Comment by syn-zeta** [comment] 2017-04-30 18:09
Not reproducible on OS X 10.11.6 / Safari **9.1**

**Comment by jri** [comment] 2017-04-30 19:23
So, does this mean this bug will not be fixed?

Safari 10.1 is the up-to-date browser on OS X El Capitan. It is installed by App Store automatically.

**Comment by syn-zeta** [comment] 2017-05-01 01:05
No, I was just adding some extra information. Perhaps someone else with OS X 10.11.6 and Safari 10.1 will be able to comment if they're able to reproduce it.

**Comment by Leopoldthecoder** [comment] 2017-05-01 02:30
Didn't reproduce this in OS X 10.12.4 / Safari 10.1. Would you mind uploading a gif of this problem?

**Comment by jri** [comment] 2017-05-01 13:16
Thank you for the replies!

Hint: the problem occurs only (as I've described) if the Select's menu **was already opened/closed** at least once.

In the screenshot you can see that the `expand-trigger` element does *not* cover the entire `el-select` element. The el-select respond to mouse clicks only in the limited area (see arrow and blue area in the screenshot). The same applies to the `contract-trigger` element.

The clickable area is limited due to this rule (shown in the screenshot):
```css
.resize-triggers > div {
    overflow: auto;
}
```

`overflow: auto` causes Safari to reserve space for scrollbars at the elements right and bottom borders (see screenshot). That is the very space that is not available for mouse clicks to open the menu. This is the origin of the problem I describe in this ticket.

![element-ui- 4555](https://cloud.githubusercontent.com/assets/120337/25579963/e6435aba-2e7c-11e7-8da0-33eaf5ae0cc7.png)

**Comment by syn-zeta** [comment] 2017-05-02 00:23
I didn't notice it before, but now I do. Here's a GIF with two strange things:

- Even before the first click on the select, `.resize-triggers > div` are actually still half the height of the select, but the field responds to the first click on the lower half.
- Removing `overflow: auto` does seem to fix it, but this style does not affect the "hit-box" until after the first click.

![select](https://cloud.githubusercontent.com/assets/26761352/25599657/d2df3c6c-2e92-11e7-9a26-2d399d0e7ae0.gif)

**Comment by jri** [comment] 2017-05-02 12:58
@syn-zeta I appreciate your investigation very much, and that you've acknowledged the bug eventually.

I assume you've done the test in Safari 9.1 and thus have proven the bug applies to Safari 9.1 as well.

Due to the bug the user experience of the Select component is very bad on OS X. To the everyday user it feels like the Select component does react to mouse clicks only occasionally.

Hopefully the bug will be fixed.

Thank you for your effort!

**Comment by savokiss** [comment] 2017-05-11 10:15
Similar issue for me in the old Chrome(CEF 1650)，user can't trigger the `select` to open sometimes. Then I find out that it was because sometimes user clicked on the `.contract-trigger` div but the `.el-select`.
When I remove the `overflow: auto` on that div, it works as expected ~

**Comment by jri** [comment] 2017-06-06 13:51
In current Element UI 1.3.5 the Select component is still not fixed.

On OS X the Select component is seriously flawed and practically not usable in production.

Meanwhile the bug has been acknowledged on all recent Safari browsers by several users.

Is there a plan to fix it?

**Comment by Leopoldthecoder** [comment] 2017-06-06 15:04
@jri I'm now finally reproducing this. @savokiss thanks for your information, that is the correct fix. 

Fixed in #5226. Will be available in the next release.

**Closed by Leopoldthecoder** 2017-06-06 15:04 UTC

**Comment by jri** [comment] 2017-06-06 15:10
@Leopoldthecoder Thank you very much :-)
