### ISSUE TITLE
[Bug Report] The scroll bar below the fixed column cannot be selected when using both the fixed column and show-summary

### ISSUE THREAD

**Issue by fengylm** [ElemeFE/element#13165] opened 2018-10-25 06:46 UTC
### Element UI version
2.4.8

### OS/Browsers version
windows10 / chrome 68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/fraq4v6w/](https://jsfiddle.net/fraq4v6w/)

### Steps to reproduce
The scroll bar below the fixed column cannot be selected when using both the fixed column and show-summary

### What is Expected?
scroll bar can select and drag

### What is actually happening?
scroll bar cannot be selected

**Comment by ziyoung** [comment] 2018-10-25 12:13
Duplicate of #12666

**Closed by ziyoung** 2018-10-25 12:13 UTC

**Comment by Bigredorange** [comment] 2018-11-19 05:44
为啥这个issue 关了呀，element-ui 2.4.7  固定列区域最底部的滚动条不能拖动问题还是存在的，请大神们修复一下咯。
