### ISSUE TITLE
When the [Bug Report] form 200 rows and 30 columns have Caton, checkbox will later be selected

### ISSUE THREAD

**Issue by ruiyong-lee** [ElemeFE/element#10408] opened 2018-03-28 08:33 UTC
### Element UI version
2.3.0

### OS/Browsers version
win10 / chrome 66

### Vue version
2.5.11

### Reproduction Link
[https://jsfiddle.net/y4xg5y9b/7/](https://jsfiddle.net/y4xg5y9b/7/)

### Steps to reproduce
如示例

### What is Expected?
不卡顿

### What is actually happening?
卡顿

**Comment by Leopoldthecoder** [comment] 2018-03-28 09:33
Duplicate of #6089

**Closed by Leopoldthecoder** 2018-03-28 09:33 UTC
