### ISSUE TITLE
[Bug Report] el-table attribute height use 'calc' do not work

### ISSUE THREAD

**Issue by max512060925** [ElemeFE/element#15958] opened 2019-06-06 08:20 UTC
### Element UI version
2.9.1

### OS/Browsers version
Mac/Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/anon/pen/KLLRjR?&editable=true#anon-login

### Steps to reproduce
<el-table  :data="tableData" style="width: 100%" height="calc(100vh - 10px)">

### What is Expected?
height style 'calc(100vh - 10px)' can be used

### What is actually happening?
no style height

**Comment by ziyoung** [comment] 2019-06-10 02:41
Duplicate of #15858

**Closed by ziyoung** 2019-06-10 02:41 UTC
