### ISSUE TITLE
[Bug Report] select width custom trigonometric misplacement

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/element#8779] opened 2017-12-12 05:52 UTC
### Element UI version
2.0.7

### OS/Browsers version
mac os

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/Lb0aw3rt/](https://jsfiddle.net/Lb0aw3rt/)

### Steps to reproduce
自定义select组件宽度，三角标错位

### What is Expected?
自定义select组件宽度，三角标不错位

### What is actually happening?
自定义select组件宽度，三角标错位

**Comment by Leopoldthecoder** [comment] 2017-12-12 05:56
Duplicate of #8644

**Closed by Leopoldthecoder** 2017-12-12 05:56 UTC
