### ISSUE TITLE
[Bug, Report], Locale, Errors, on, el-date-picker - EN,, locale, loaded

### ISSUE THREAD

**Issue by adavie1** [ElemeFE/element#6216] opened 2017-08-02 03:16 UTC
### Element UI version
1.4.1

### OS/Browsers version
Chrome / Linux / Ubuntu 16.04

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/443/](https://jsfiddle.net/pj71jkyw/443/)
Couldn't configure the reproduction link to work, not sure how to add package dependencies. [edit: Partial fix on the fiddle- just don't know how to get the `import` keyword working.]

### Steps to reproduce
Previous to an upgrade to 1.4.1 at version 1.3.2 (I think) all was working OK.
This is my config for locale-
````
import 'element-ui/lib/theme-default/index.css'

import VueI18n from 'vue-i18n'

import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'

Vue.use(VueI18n)
Vue.use(Element, { enLocale })

Vue.config.lang = 'en'
locale.use(enLocale)
Vue.locale('en', enLocale)
`````

When I use `el-date-picker` with a format of `'dd MMM yyyy'` the month portion shows in Chinese.

Example: `09 八月 2017`

The locale is loading correctly, since on the el-select I see 'Select' in English.

### What is Expected?
Expect to see the month names in English.

### What is actually happening?
Chinese month names show up.

**Comment by Leopoldthecoder** [comment] 2017-08-04 09:52
@adavie1 @jaydubyasee You may have upgraded `vue-i18n` from 5.x to 6.x because Element has different i18n configurations for those two versions.

- `vue-i18n` 5.x: http://localhost:8085/#/en-US/component/i18n#compatible-with
- `vue-i18n` 6.x: http://localhost:8085/#/en-US/component/i18n#compatible-with-2

**Comment by Leopoldthecoder** [comment] 2017-08-04 09:57
Apart from Element, if you don't have other texts that need to be internationalized, we recommend using the Element built-in i18n directly instead of `vue-i18n`.

**Comment by adavie1** [comment] 2017-08-05 03:19
@Leopoldthecoder  thanks for the comment- I did check that- at least in the package.json it's still set at v5.XX. I also ran `yarn list` to check, and as far as I can tell, it's still at 5.xx. Did I miss anything?

Whilst I don't need internationalisation now, the project will need it in the next few months.

**Comment by Leopoldthecoder** [comment] 2017-08-05 05:55
@adavie1 I tested in a new project with element-ui@1.4.2 and vue-i18n@5.0.3 and it worked fine:
```JS
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'

Vue.use(VueI18n)
Vue.use(Element)

Vue.config.lang = 'en'
Vue.locale('en', enLocale)
```

**Comment by adavie1** [comment] 2017-08-06 01:00
Thanks for testing that @Leopoldthecoder 

Very odd: just did `yarn list vue-i18n` to confirm version:
```
yarn list v0.27.5
└─ vue-i18n@5.0.3
Done in 1.01s.
```
I've replaced my code with yours as given above. Same issue persists.

**Comment by Leopoldthecoder** [comment] 2017-08-06 01:44
@adavie1 Could you post your project on GitHub so I can take a look? You can remove irrelevant code before posting it.

**Comment by adavie1** [comment] 2017-08-06 02:58
it's quite a big project, so I've taken the relevant portions and put them here:
**App.vue** (_script porition_)
```
import Vue from 'vue'
import moment from 'moment'

import 'element-ui/lib/theme-default/index.css'

import VueI18n from 'vue-i18n'
import Element from 'element-ui'
import enLocale from 'element-ui/lib/locale/lang/en'

Vue.use(VueI18n)
Vue.use(Element)

Vue.config.lang = 'en'
Vue.locale('en', enLocale)

import LoginModal from '@/components/LoginModal'

export default {
  name: 'app',
  components: {
    LoginModal
  },
  data () {
    return {
      showLogin: !this.loggedIn(),
      year: moment(new Date()).format('YYYY')
    }
  }
}

```
I have a constants section where I set up frequently used things like text, formats and objects in Data.js
The relevant date portions:
**Data.js** (_constants and data types_)
```
// element-ui and moment.js clash on YYYY vs. yyyy
export const SELECT_DATE_FORMAT = 'd/MM/yyyy'
export const SELECT_DATETIME_FORMAT = 'd/MM/yyyy HH:mm'

// moment.js values used for static display
export const DATE_FORMAT = 'DD MMM YYYY'
export const DATETIME_FORMAT = 'dd MMM yyyy hh:mm a'

export const DATE_SQL_FORMAT = 'YYYY-MM-DD'
export const DATETIME_SQL_FORMAT = 'YYYY-MM-DD HH:mm:ss'

export const DATE_HUMAN_FORMAT = 'd MMM YYYY h:mm a'

```
And finally, the actual use of the datepicker- the roughly the same code is used through the application:
... import constants...
```
import {SELECT_DATE_FORMAT, CURRENCY,
  UTIL_LABEL,
  TAX_LABEL,
  UTIL_OVERDUE_LABEL,
  UTIL_AMOUNT_LABEL,
  UTIL_EXTRA_INPUT_LABEL,
  UTIL_EXTRA_INPUT_TOTAL} from '@/components/Data'
```

... define values in data() ...
```
  data () {
    return {
      format: SELECT_DATE_FORMAT,
      currency: CURRENCY,
      utilLabel: UTIL_LABEL,
      taxLabel: TAX_LABEL,
      overdueLabel: UTIL_OVERDUE_LABEL,
      amountLabel: UTIL_AMOUNT_LABEL,
      extraChargesLabel: UTIL_EXTRA_INPUT_LABEL,
      extraCalcTotal: UTIL_EXTRA_INPUT_TOTAL,
      localData: this.rowData,
      site: {},
      rates: []
    }
  },
```
.... template usage ....
```
<template>
...
         <el-form  :model="localData"  label-width="90px">
           <el-form-item label="Paid?">
             <el-switch  on-text="Yes" off-text="No" v-model="localData.paid" placeholder="Paid?"></el-switch>
           </el-form-item>

           <el-form-item label="Date Paid">
             <el-date-picker :format="format" v-model="localData.paidDate" placeholder="Paid Date" :disabled="!localData.paid"></el-date-picker>
           </el-form-item>

           <el-form-item label="Reference No.">
             <el-input v-model="localData.paidRef" placeholder="Paid Ref" :disabled="!localData.paid"></el-input>
           </el-form-item>

           <el-form-item label="Paid Amount">
             <el-input type="number" v-model="localData.paidAmount" :disabled="!localData.paid">
               <template slot="prepend">{{currency}}</template>
             </el-input>
           </el-form-item>

           <el-form-item label=" ">
             <el-button type="success" @click="onSubmit" disabled>Save</el-button>
           </el-form-item>
         </el-form>
...
</template>
```

**Comment by Leopoldthecoder** [comment] 2017-08-06 07:05
@adavie1 I have reproduced this bug. Trying to fix it.

**Comment by Timz** [comment] 2017-08-06 10:14
Me too reproduced this bug in Ru locale.

**Comment by Leopoldthecoder** [comment] 2017-08-07 02:50
Fixed in #6328

**Closed by Leopoldthecoder** 2017-08-07 02:50 UTC

**Comment by adavie1** [comment] 2017-08-08 02:42
Thanks @Leopoldthecoder for fixing this. I guess it will be in the next release?

**Comment by Leopoldthecoder** [comment] 2017-08-08 03:25
@adavie1 Yes
