### ISSUE TITLE
[Bug Report] Get an exception when use an el-input inside el-card

### ISSUE THREAD

**Issue by sazanow** [ElemeFE/element#7336] opened 2017-10-02 15:35 UTC
### Element UI version
2.0.0-alpha.1

### OS/Browsers version
Chrome (Version 60.0.3112.113)

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/vhgmtef2/](https://jsfiddle.net/vhgmtef2/)

### Steps to reproduce
Run the application and see console.

### What is Expected?
Use el-input inside an el-card.

### What is actually happening?
Get an exception when use el-input inside an el-card.

**Comment by Leopoldthecoder** [comment] 2017-10-03 00:27
Duplicate of #7324

**Closed by Leopoldthecoder** 2017-10-03 00:27 UTC
