### ISSUE TITLE
[Bug, Report], Table, component's, scroll, is, unavailable

### ISSUE THREAD

**Issue by monkeyWangs** [ElemeFE/element#5132] opened 2017-05-31 01:46 UTC
### Element UI version
1.3.4

### OS/Browsers version
safari 9.1.2

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/n5b0du9a/](https://jsfiddle.net/n5b0du9a/

### Steps to reproduce
1. Open safari
2. Open https://jsfiddle.net/n5b0du9a/

### What is Expected?
滚动横向滚动条

### What is actually happening?
滚动条无法滚动

**Comment by Leopoldthecoder** [comment] 2017-06-03 08:05
Duplicate of #3710

**Closed by Leopoldthecoder** 2017-06-03 08:05 UTC
