### ISSUE TITLE
[Bug Report] el-table Table header gray can be selected

### ISSUE THREAD

**Issue by beyondkqw** [ElemeFE/element#21332] opened 2021-09-20 02:39 UTC
### Element UI version
2.15.6

### OS/Browsers version
Windows 10 /  Chrome  93.0.4577.82

### Vue version
2.6.14

### Reproduction Link
https://codepen.io/pen/

### Steps to reproduce
Please directly use the official website online demo address to reproduce
①Select the checkbox form and open the online presentation address
②Delete all table data, and the table header is dimmed
③Check the gray header, although it is prohibited, but the header is checked  

### What is Expected?
The table header is not selected

### What is actually happening?
 the header is checked

**Comment by cs1707** [comment] 2021-09-24 06:14
Duplicate of #21267

**Closed by cs1707** 2021-09-24 06:14 UTC
