### ISSUE TITLE
Request: Collapsible

### ISSUE THREAD

**Issue by FranzSkuffka** [ElemeFE/element#1323] opened 2016-11-24 02:41 UTC
Hey there!

Element is pretty awesome!

I was wondering whether a collapsible like an accordion is on the roadmap / in the scope of element.

Regards

**Comment by Leopoldthecoder** [comment] 2016-11-24 02:49
Yes, we plan to add accordion in Element 1.1.
Duplicate of #627 .

**Closed by Leopoldthecoder** 2016-11-24 02:49 UTC

**Comment by FranzSkuffka** [comment] 2016-11-24 03:12
Sorry for the dupe.
