### ISSUE TITLE
[Bug Report] [table bug] the colum's order is wrong

### ISSUE THREAD

**Issue by narutowyh** [ElemeFE/element#5974] opened 2017-07-20 12:42 UTC
### Element UI version
1.4.0-beta.1

### OS/Browsers version
all browser

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/393/](https://jsfiddle.net/pj71jkyw/393/)

### Steps to reproduce
https://jsfiddle.net/pj71jkyw/393/

### What is Expected?
the col's order is right

### What is actually happening?
first col appears at the last table-head

**Comment by Leopoldthecoder** [comment] 2017-08-27 09:12
Duplicate of #4057

**Closed by Leopoldthecoder** 2017-08-27 09:12 UTC
