### ISSUE TITLE
When the [Bug Report] el-table has a lateral scrollbar, the aggregate line of the table appears under the scroll bar; and when there is a fixed column, the total line shows the dislocation.

### ISSUE THREAD

**Issue by AprilXtt** [ElemeFE/element#8923] opened 2017-12-20 16:09 UTC
### Element UI version
2.0.8

### OS/Browsers version
windows 10/chrome 62.0.3202.94

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/akjwa4ex/1/](https://jsfiddle.net/akjwa4ex/1/)

### Steps to reproduce
① el-table表格存在横向滚动条
② 表格添加合计行
结果：合计行在滚动条下方
① el-table表格存在横向滚动条且最后一列固定
② 表格添加合计行
结果：合计行在滚动条下方，且最后一列的合计单元格错位

### What is Expected?
1.合计行在滚动条上方，且样式可设置。
2.当存在固定列时，解决错位问题

### What is actually happening?
1.合计行在滚动条下方
2.当存在固定列时，合计行错位

**Comment by Leopoldthecoder** [comment] 2018-01-07 04:32
Duplicate of #5886

**Closed by Leopoldthecoder** 2018-01-07 04:32 UTC
