### ISSUE TITLE
[Bug Report] 表格中使用datePicker文字不显示

### ISSUE THREAD

**Issue by bboywulong** [ElemeFE/element#7456] opened 2017-10-12 10:19 UTC
### Element UI version
1.4.6

### OS/Browsers version
macOS / chrome

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
表格中使用slot="append"添加的datePicker文字不显示,v-model赋值成功的

### What is Expected?
datePicker文字显示

### What is actually happening?
datePicker文字不显示

**Comment by Leopoldthecoder** [comment] 2017-10-12 10:32
Duplicate of #6046

**Closed by Leopoldthecoder** 2017-10-12 10:32 UTC
