### ISSUE TITLE
[Bug Report] el-drawer does not have a scrollbar

### ISSUE THREAD

**Issue by lalalacampanella** [ElemeFE/element#17713] opened 2019-10-15 02:02 UTC
### Element UI version
2.12.0

### OS/Browsers version
win10 chrome 74

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mLvkb0f4/

### Steps to reproduce
just create a very long el-drawer, then it comes to have no slider

### What is Expected?
it show's slider as other components

### What is actually happening?
it has no slider

**Comment by tripflex** [comment] 2019-12-03 21:15
I had to add this CSS to mine to add the scrollbar:

```css
	.el-drawer__body {
		height: 100%;
		box-sizing: border-box;
		overflow-y: auto;
	}
```

Got it from https://github.com/ElemeFE/element/issues/17130#issuecomment-523778100

**Comment by Aceix** [comment] 2020-03-19 19:23
> I had to add this CSS to mine to add the scrollbar:
> 
> ```css
> 	.el-drawer__body {
> 		height: 100%;
> 		box-sizing: border-box;
> 		overflow-y: auto;
> 	}
> ```
> 
> Got it from [#17130 (comment)](https://github.com/ElemeFE/element/issues/17130#issuecomment-523778100)

Solved the issue

**Comment by vikaskedia** [comment] 2020-10-07 12:14
Please close this issue.

**Comment by liuchang111001** [comment] 2020-11-09 08:11
this css not work for me.

**Comment by zhanghao19920218** [comment] 2021-01-29 03:04
> this css not work for me.

same to me

**Comment by zhanghao19920218** [comment] 2021-01-29 03:22
> this css not work for me.

Add these codes to the main scss file

`.el-drawer__open .el-drawer.rtl{
  overflow: scroll;
}`

**Comment by cs1707** [comment] 2021-04-20 10:54
Duplicate of #20712

**Closed by cs1707** 2021-04-20 10:54 UTC
