### ISSUE TITLE
[Bug Report] table selection carries out the full selection meeting when the data is large.

### ISSUE THREAD

**Issue by masongzhi** [ElemeFE/element#12901] opened 2018-09-27 02:27 UTC
### Element UI version
2.4.7

### OS/Browsers version
10.13.6 / chrome 69

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/rfbu5jc2/2/](https://jsfiddle.net/rfbu5jc2/2/)

### Steps to reproduce
点击全选 => 取消全选

### What is Expected?
等待时间很短

### What is actually happening?
等待时间很长，因为全选是遍历表格元素执行toggleRowSelection函数，400条时相当于执行400次，能不能加上一个事件是全选事件

**Comment by masongzhi** [comment] 2018-09-28 14:18
this is the new link
https://jsfiddle.net/rfbu5jc2/2/

**Comment by ziyoung** [comment] 2018-09-29 07:28
Duplicate of #12697

**Closed by ziyoung** 2018-09-29 07:28 UTC

**Comment by ziyoung** [comment] 2018-09-30 02:55
@masongzhi toggleAllSelection 方法应该可以满足你的需求吧。https://jsfiddle.net/b5taLfjc/
