### ISSUE TITLE
[Bug Report] Validation for select field not working as expected when "trigger" is set to "blur"

### ISSUE THREAD

**Issue by yocheved** [ElemeFE/element#11904] opened 2018-07-08 08:05 UTC
### Element UI version
2.4.3

### OS/Browsers version
Windows 10 Chrome v67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/wjeLb04o/1/](https://jsfiddle.net/wjeLb04o/1/)

### Steps to reproduce
1. focus in and then out of the select box without choosing an option
2. submit form empty and once the error message is there, select an option

### What is Expected?
1. error message should show up
2. error message should get removed

### What is actually happening?
1. nothing
2. error message stays

**Comment by ziyoung** [comment] 2018-08-08 03:06
Duplicate of #12273

**Closed** 2018-08-08 03:07 UTC
Labels: component: select, type: bug
