### ISSUE TITLE
[Feature Request] input-number : let user use comma

### ISSUE THREAD

**Issue by sebastienroul** [ElemeFE/element#5760] opened 2017-07-07 15:56 UTC
### Existing Component
Yes

### Component Name
input-number

### Description
Hello,

The component input-number check if the user input is a number with JS function Number()

In many countries we use a comma to separate the decimal part, so it would be great to accept dot or comma.

https://github.com/ElemeFE/element/blob/afb6625d7c64c922539623c65200b73daac4b580/packages/input-number/src/input-number.vue#L115

`let newVal = Number(value)`

would be 

`let newVal = Number(value.replace(',','.'))`

Sorry for this demand, but I have many users which were not able to enter decimal numbers and they made lot of ticket to our support :)

Bye

**Comment by wacky6** [comment] 2017-07-07 16:35
@Leopoldthecoder 

Does element's i18n supports number formatting?

If not, JS Intl.NumberFormat works on modern browsers, except IE<11 and safari<10.

**Comment by wacky6** [comment] 2017-07-08 17:52
How about a somewhat "intelligent" method? https://jsfiddle.net/szd1vw0u/

**Comment by ericcgu** [comment] 2018-02-06 14:13
Can create custom component for this

https://gist.github.com/ericcgu/b4b16a6f7ce73c5329c4c395f02896c5

**Comment by csvwolf** [comment] 2018-11-06 10:55
I think a specified component is a good idea than support in input number.

Since the issue is open for a long time, I will close it. If you want a discussion later, you can reopen it.

**Closed by csvwolf** 2018-11-06 10:55 UTC
Labels: component: input-number
