### ISSUE TITLE
[Bug, Report], Table, summary, cells, in, fixed, wrong, position, column, when, horizon, scroll, appears

### ISSUE THREAD

**Issue by callmelex** [ElemeFE/element#5812] opened 2017-07-12 00:43 UTC
### Element UI version
1.3.7

### OS/Browsers version
Chrome V59

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/367/](https://jsfiddle.net/pj71jkyw/367/)

### Steps to reproduce
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/element-ui/lib/index.js"></script>
<div id="app">
<template>
  <el-table
    :data="tableData6"
    border
    show-summary
    style="width: 400px">
    <el-table-column
      prop="id"
      label="ID"
      width="180" fixed>
    </el-table-column>
    <el-table-column
      prop="name"
      label="姓名">
    </el-table-column>
    <el-table-column
      prop="amount1"
      sortable
      label="数值 1">
    </el-table-column>
    <el-table-column
      prop="amount2"
      sortable
      label="数值 2">
    </el-table-column>
    <el-table-column
      prop="amount3"
      sortable
      label="数值 3">
    </el-table-column>
  </el-table>
  
</div>
var Main = {
  data() {
     return {
        tableData6: [{
          id: '12987122',
          name: '王小虎',
          amount1: '234',
          amount2: '3.2',
          amount3: 10
        }, {
          id: '12987123',
          name: '王小虎',
          amount1: '165',
          amount2: '4.43',
          amount3: 12
        }, {
          id: '12987124',
          name: '王小虎',
          amount1: '324',
          amount2: '1.9',
          amount3: 9
        }, {
          id: '12987125',
          name: '王小虎',
          amount1: '621',
          amount2: '2.2',
          amount3: 17
        }, {
          id: '12987126',
          name: '王小虎',
          amount1: '539',
          amount2: '4.1',
          amount3: 15
        }]
      };
  }
}
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')

### What is Expected?
I have to append this code after VUE code :
	$(document).ready(function(){
		$('.el-table').each(function(){
			$('.el-table__fixed', this).height($(this).height());
			$('.el-table__fixed-right', this).height($(this).height());
		});
	});

### What is actually happening?
wrong cell position covered horizon scroll bar.

**Comment by Leopoldthecoder** [comment] 2017-07-12 01:45
Duplicate of #5415

**Closed by Leopoldthecoder** 2017-07-12 01:45 UTC
