### ISSUE TITLE
[Bug Report] DatePicker's week mode, after setting firstDayOfWeek, the date returned is not right.

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/element#11158] opened 2018-05-15 01:42 UTC
### Element UI version
2.3.8

### OS/Browsers version
Mac OS/Chrome 67

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/h4u00rot/1/](https://jsfiddle.net/h4u00rot/1/)

### Steps to reproduce
1. 打开重现链接
2. 选择日期, @change 返回的日期是选择周的第二个, 而不是第一个

### What is Expected?
正确返回日期

### What is actually happening?
返回的日期为, 实际日期   1

**Comment by Leopoldthecoder** [comment] 2018-05-15 02:52
Duplicate of #6754

**Closed by Leopoldthecoder** 2018-05-15 02:52 UTC
