### ISSUE TITLE
The [Bug Report] table totals rows. If multiple columns have horizontal scroll bars, the fixed column is out of order and the table is misaligned

### ISSUE THREAD

**Issue by xqsapper** [ElemeFE/element#6729] opened 2017-08-28 07:43 UTC
### Element UI version
1.4.3

### OS/Browsers version
windows10/chrome60

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/qm4z1rd8/](https://jsfiddle.net/qm4z1rd8/)

### Steps to reproduce
https://jsfiddle.net/qm4z1rd8/

### What is Expected?
能够完善表格合计行固定列的显示

### What is actually happening?
能够完善表格合计行固定列的显示

**Comment by Leopoldthecoder** [comment] 2017-08-28 08:25
Duplicate of #5415

**Closed by Leopoldthecoder** 2017-08-28 08:25 UTC
