### ISSUE TITLE
[Feature Request] Option to set position in Notification

### ISSUE THREAD

**Issue by goldsteinr** [ElemeFE/element#4915] opened 2017-05-17 16:32 UTC
### Existing Component
Yes

### Component Name
Notification

### Description
The Notification component could have a set position option.
 **position: 'top-left/top-right/bottom-left/bottom-right'**
Ex:  
```
this.$notify.success({
     title: 'Success',
     message: 'This is a success message',
     offset: 100,
     position: 'top-left/top-right/bottom-left/bottom-right'
});
```

Congratz on the project :) really great.

**Comment by Leopoldthecoder** [comment] 2017-07-30 09:07
Duplicate of #3529.

**Closed by Leopoldthecoder** 2017-07-30 09:07 UTC
