### ISSUE TITLE
[Bug Report] Safari browser, MessageBox after clicking confirmation, the MessageBox popped away, disappeared.

### ISSUE THREAD

**Issue by Emiya0306** [ElemeFE/element#11983] opened 2018-07-13 09:44 UTC
### Element UI version
2.4.4

### OS/Browsers version
MacOS 10.13.4 / Safari 11.1 (13605.1.33.1.2)

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/y5faLjxo/1/](https://jsfiddle.net/y5faLjxo/1/)

### Steps to reproduce
- 打开Safari浏览器，运行代码
- 点击使MessageBox弹窗出现
- 再点击MessageBox的确定

### What is Expected?
弹出下一个MessageBox弹框

### What is actually happening?
弹出下一个MessageBox弹框，并闪现消失

**Comment by ziyoung** [comment] 2018-07-14 09:11
Duplicate of #10839

**Closed** 2018-07-14 09:12 UTC
