### ISSUE TITLE
[Bug Report] The jumper of pagination can't work  correctly  for IE 11  

### ISSUE THREAD

**Issue by Richard2050** [ElemeFE/element#11710] opened 2018-06-22 07:52 UTC
### Element UI version
2.4.1

### OS/Browsers version
Windows 7 / IE 11

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2556/](https://jsfiddle.net/mmx38qxw/2556/)

### Steps to reproduce
The jsfiddle link can't work on IE 11. https://jsfiddle.net/mmx38qxw/2556/ 
We can test it  use this link: http://element-cn.eleme.io/#/en-US/component/pagination

1. Input 2 and press Enter in jumper, it works correctly 
2. Keep focus on the jumper and input 3 and press Enter, it can't work. (if you lose focus, it works correctly)

### What is Expected?
Hope it can work correctly to my page NO. changes every time.

### What is actually happening?
When you press Enter to change the page NO. that you want to jump to, the control only work for first time on Internet Explorer 11.

**Comment by Richard2050** [comment] 2018-07-09 03:55
I've already debugged this com, and find a way to fix this bug. I will commit a PR to this repository.
`   handleChange: function handleChange(value) {
          this.$parent.internalCurrentPage = this.$parent.getValidCurrentPage(value);
          this.$parent.emitChange();
          this.oldValue = this.$parent.internalCurrentPage;
          this.resetValueIfNeed(value);
        },`

**Comment by beidoufe** [comment] 2018-08-23 06:53
Same problem, when can I use this feature?

**Comment by ziyoung** [comment] 2018-10-29 09:56
@Richard2050 change event does'nt trigger in IE. https://stackoverflow.com/questions/38642802/input-change-event-on-enter-key-not-working-in-ie

Maybe it's not a bug of Element.

**Comment by ziyoung** [comment] 2018-11-26 09:00
fixed in #13471

**Closed by ziyoung** 2018-11-26 09:00 UTC
Labels: windows
