### ISSUE TITLE
[Bug Report] Cascader next level menu show up when children Array is empty

### ISSUE THREAD

**Issue by JeryLi** [ElemeFE/element#13758] opened 2018-12-13 12:10 UTC
### Element UI version
2.4.11

### OS/Browsers version
Chrome 71 64-bit

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/yjdnvu6m/](https://jsfiddle.net/yjdnvu6m/)

### Steps to reproduce
Sometimes some data objects have an empty Array  or even have no key named "child" or "children"(whatever, you konw what I mean)  from server.The next menu show up when children Array is a empty array.

### What is Expected?
The next menu shouldn't be showed when children Array is a empty array.

### What is actually happening?
The next menu show up when children Array is a empty array.

**Comment by ziyoung** [comment] 2018-12-29 09:39
Duplicate of #10027

**Closed by ziyoung** 2018-12-29 09:39 UTC
