### ISSUE TITLE
[Bug Report] table filter when set filter-multiple="false",has mant items,set height 300px,when click scroll bar，“ALL” Options has been hidden

### ISSUE THREAD

**Issue by yuanyuanshen** [ElemeFE/element#13438] opened 2018-11-16 02:54 UTC
### Element UI version
2.4.9

### OS/Browsers version
window10 chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/yyshen_11/rqau25fL/11/](https://jsfiddle.net/yyshen_11/rqau25fL/11/)

### Steps to reproduce
bug图片链接
http://img0.ph.126.net/qgmCH9BUjoOxKrpSqEN2mw==/6631565844471565101.png
（1）in table filter ，click scroll bar
（2）scrool to bottom then scrool back
（3）"ALL" option has been hidden

### What is Expected?
（1）in table filter ，click scroll bar
（2）scrool to bottom then scrool back
（3）"ALL" option should be shown normally

### What is actually happening?
（1）in table filter ，click scroll bar
（2）scrool to bottom then scrool back
（3）"ALL" option has been hidden

**Comment by yuanyuanshen** [comment] 2018-11-16 02:55
bug 图片地址
http://img1.ph.126.net/a6iY-FaXQn58GxPj6e1BZQ==/6632652161956654963.png

**Comment by ziyoung** [comment] 2018-11-16 02:58
Duplicate of #13421

**Closed by ziyoung** 2018-11-16 02:58 UTC
