### ISSUE TITLE
[Bug Report] Put an autocomplete element into a popover element then there's a bug

### ISSUE THREAD

**Issue by wujb123** [ElemeFE/element#8299] opened 2017-11-15 09:32 UTC
### Element UI version
2.0.4

### OS/Browsers version
Windows 10 / Chrome 61.0.3163.100 32bit

### Vue version
2.5.3

### Reproduction Link
[http://jsfiddle.net/mrttuL90/](http://jsfiddle.net/mrttuL90/)

### Steps to reproduce
click the button，popup appear 
and then auto disappear

### What is Expected?
dont expect the popup element disappear

### What is actually happening?
popup element disappear,it isn't expected

**Comment by Leopoldthecoder** [comment] 2017-11-15 10:25
Duplicate of #8186

**Closed by Leopoldthecoder** 2017-11-15 10:25 UTC

**Comment by wujb123** [comment] 2017-11-15 11:19
不只是点击一下消失，再次点击，然后点击autocomplete，popup又消失了，希望是能顺利填写autocomplete，这在1.4版本是正常的
