### ISSUE TITLE
[Feature Request] Is there any development plan for vue3?

### ISSUE THREAD

**Issue by FFFFof7** [ElemeFE/element#19618] opened 2020-06-11 05:33 UTC
### Existing Component
是

### Component Name
all components

### Description
Future versions will be rebuilt with vue3 or compatible with vue3？
What can I do for this?

**Comment by zazzaz** [comment] 2020-08-20 10:46
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment] 2020-12-26 04:58
Duplicate of #20375

**Closed by cs1707** 2020-12-26 04:58 UTC
