### ISSUE TITLE
When [Bug Report] el-dialog contains switch or radio for switching, the text flashes in dialog, and the dialog box is about to shake

### ISSUE THREAD

**Issue by SuperSL** [ElemeFE/element#6806] opened 2017-08-31 18:31 UTC
### Element UI version
1.4.3

### OS/Browsers version
win10 Chrome 59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/531/](https://jsfiddle.net/pj71jkyw/531/)

### Steps to reproduce
1.在el-dialog中添加switch或radio控件
2.点击按钮显示dialog
3.切换switch状态，或者选择不同的radio

### What is Expected?
dialog内除被点击的switch或radio外其他文字保持原样

### What is actually happening?
dialog内所有文字在switch或radio动画出现过程中有闪烁，dialog对话框左右震动一下
当dialog内放置大量控件后，尤其严重

**Comment by Leopoldthecoder** [comment] 2017-09-01 02:30
Duplicate of #2461

**Closed by Leopoldthecoder** 2017-09-01 02:30 UTC
