### ISSUE TITLE
[Bug Report] VUE WARN：The computed property "fields" is already defined in data

### ISSUE THREAD

**Issue by bestkj** [ElemeFE/element#4720] opened 2017-05-06 04:37 UTC
### Element UI version
1.3.0

### OS/Browsers version
Chrome latest

### Vue version
2.3.2

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
1、更新1.2.8版本到1.3.0后，所有的页面包含ElForm的组件，都出现了 vue 警告 The computed property "fields" is already defined in data.

### What is Expected?
希望修复

### What is actually happening?
希望修复

**Comment by Leopoldthecoder** [comment] 2017-05-06 05:11
Closing for lack of valid reproduction.

**Closed by Leopoldthecoder** 2017-05-06 05:11 UTC

**Comment by daggerjames** [comment] 2017-05-06 05:34
I encountered same error, and it turns out that element-ui is free for that.

I assume that the poster used a package called 'vee-validate', and what it (or similar packages) did, is mixing a computed property called 'fields' globally, which for el-form, was used in data filed. In vue 2.3.0, it treats name conflicts as an error.

if you used 'vee-validate', it could config fieldBagName to solve the conflict, see [here](http://vee-validate.logaretm.com/#configuration). If it caused by other packages, see theirs.

**Comment by jkhmnk** [comment] 2017-07-04 08:04
事实证明就是“vee-validate” 这个依赖组件的问题，名字冲突了， 关掉就好了。

**Comment by sylvaincaillot** [comment] 2017-12-04 04:03
I am facing this exact same problem  with el-form, no other packages involved, just Element-UI

`[Vue warn]: The computed property "fields" is already defined in data.`

Any solution to solve this?

S.

**Comment by diejsel** [comment] 2017-12-13 11:50
@sylvaincaillot change [here](http://vee-validate.logaretm.com/#configuration) field - fieldsBagName: 'fields',

**Comment by Ghostff** [comment] 2018-10-29 20:13
The url for the answers above(change fieldsBagName) was updated to [https://baianat.github.io/vee-validate/configuration.html](this)

**Comment by luatnd** [comment] 2019-03-01 12:18
? 
I'm using element-ui only and I've got this bug also, so how can I modify vee-validate?
Should I need to create new plugins to override it?

**Comment by a3246995** [comment] 2019-08-05 08:21
我这样解决了...
//表单验证
import VeeValidate, { Validator } from 'vee-validate'

// 表单验证配置
const config = {
  // 报错处理
  fieldsBagName: "fieldss",
}

**Comment by gech4me** [comment] 2020-06-21 08:50
The same error. I did not use any package other than element-ui.
![image](https://user-images.githubusercontent.com/53906251/85220583-66995a00-b3b5-11ea-8de1-f5a08949aedf.png)
