### ISSUE TITLE
[Bug Report] Popover would flash at first time existence

### ISSUE THREAD

**Issue by chenyiqiao** [ElemeFE/element#8318] opened 2017-11-16 07:25 UTC
### Element UI version
2.0.4

### OS/Browsers version
Windows 7/ Chrome 62.0.3202.94 | Windows 7 / Firefox 56.0  | Mac 10.12.4 / Chrome 62.0.3202.94 

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/chen1qiao_/2ht10oq5/1/](https://jsfiddle.net/chen1qiao_/2ht10oq5/1/)

### Steps to reproduce
click all three red buttons, the popover would render successfully in second click(flash in the first click).

### What is Expected?
el-popover pops out as normal.

### What is actually happening?
el-popover pops out successfully in second click(flash in the first click).  Tested in latest firefox and chrome on Window 7 and Mac,turns out firefox on mac is OK, and another three platforms(as in OS / Browser) is not.

**Comment by chenyiqiao** [comment] 2017-11-16 07:26
![test](https://user-images.githubusercontent.com/11814589/32878784-6922cc98-cae2-11e7-9c4c-ee420c888894.gif)

**Comment by wujb123** [comment] 2017-11-16 07:59
借楼说一下，不只是存在这个问题，当popup里面放进一个autocomplete元素，popup弹出的时候点击autocomplete准备填写时，popup会直接消失，正常点击popup以外的区域才消失。
昨天有发起这个问题，不过描述得不好，就不另起楼了。
https://jsfiddle.net/mrttuL90/

**Comment by Leopoldthecoder** [comment] 2017-11-16 08:05
Duplicate of #8186.

@wujb123 Same thing, will be fixed in the next release.

**Closed by Leopoldthecoder** 2017-11-16 08:05 UTC
