### ISSUE TITLE
[Bug Report] loaded ELEMENT, Will be re load Vue

### ISSUE THREAD

**Issue by Dd-ouni** [ElemeFE/element#12408] opened 2018-08-17 09:39 UTC
### Element UI version
2.4.6

### OS/Browsers version
谷歌浏览器

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/3370871708/q0kgfxns](https://jsfiddle.net/3370871708/q0kgfxns)

### Steps to reproduce
run jsfiddle  dome, observation Chrome tool network， loaded ELEMENT，Will be re load Vue, load Vue file directory and ELEMENT file directory，or else 404; Do not want to use vue cli.

### What is Expected?
loaded ELEMENT, not will be re load Vue

### What is actually happening?
loaded ELEMENT, will be re load Vue

**Comment by ziyoung** [comment] 2018-08-17 10:54
Duplicate of #1444

**Closed by ziyoung** 2018-08-17 10:54 UTC

**Comment by ziyoung** [comment] 2018-08-17 11:04
> "vue": "//unpkg.com/vue/dist/vue"

`vue` but not `Vue`.
https://jsfiddle.net/zhiyang/q0kgfxns/9/
