### ISSUE TITLE
[Bug Report] el-main increases the space of el-aside when the elements increase

### ISSUE THREAD

**Issue by levi1994** [ElemeFE/element#9906] opened 2018-02-27 05:10 UTC
### Element UI version
2.2.0

### OS/Browsers version
macos

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/L8dgs3hL/3/](https://jsfiddle.net/L8dgs3hL/3/)

### Steps to reproduce
1. 使用container布局，左边el-aside，右边el-main
2. el-main中增加float的div
3. 随着div的不断增多，el-main逐渐挤压el-aside的空间

### What is Expected?
el-main与el-aside的宽度不做变化

### What is actually happening?
随着div的不断增多，el-main逐渐挤压el-aside的空间

**Comment by Leopoldthecoder** [comment] 2018-02-27 09:51
Duplicate of #9865

**Closed by Leopoldthecoder** 2018-02-27 09:51 UTC
