### ISSUE TITLE
The total row of [Bug Report] table appears at the bottom of the table scroll bar.

### ISSUE THREAD

**Issue by topul** [ElemeFE/element#11222] opened 2018-05-18 03:40 UTC
### Element UI version
2.3.8

### OS/Browsers version
Windows 10/ chrome 66

### Vue version
2.5.16

### Reproduction Link
[ https://jsfiddle.net/ag1dz26g/](  https://jsfiddle.net/ag1dz26g/)

### Steps to reproduce
开启合计行，设置冻结前几列表格，让table出现滚动条
![image](https://user-images.githubusercontent.com/8213229/40214946-4f06987e-5a90-11e8-8f4f-9cd4399f0bde.png)

### What is Expected?
滚动条出现在合计行下方

### What is actually happening?
滚动条出现在合计行上方

**Comment by Leopoldthecoder** [comment] 2018-05-18 03:48
Duplicate of #7564

**Closed by Leopoldthecoder** 2018-05-18 03:48 UTC
