### ISSUE TITLE
[Bug Report] Select option's list is not closing on click (on clicking icon also) when set to multiple and filterable

### ISSUE THREAD

**Issue by akki-jat** [ElemeFE/element#11048] opened 2018-05-07 18:36 UTC
### Element UI version
2.3.7

### OS/Browsers version
Windows 7 / Chrome 66.0.3359.139

### Vue version
2.5.11

### Reproduction Link
[https://codepen.io/akki-jat/pen/GdEYyG](https://codepen.io/akki-jat/pen/GdEYyG)

### Steps to reproduce
Open it then try to close it by clicking on select element

### What is Expected?
Select option's list should be closed

### What is actually happening?
Select option's list is not closing

**Comment by akki-jat** [comment] 2018-05-12 14:45
Hey @Leopoldthecoder, what about this, is it suppose to work like that?

**Comment by leslieSie** [comment] 2018-05-23 08:43
I think you should remove the property of filterable or change another version,version on 2.3.9 fixed this problem

**Comment by leslieSie** [comment] 2018-05-23 08:44
@Leopoldthecoder  dalao close this problem

**Comment by akki-jat** [comment] 2018-05-28 14:43
Hi @leslieSie, I need the filter functionality and this issue is not solved either in 2.3.9 or 2.4.0.
In new version, on pc it is closed only first time and second time it does not close & on mobile it even not closes first time

**Comment by wacky6** [comment] 2018-06-04 11:21
The problem is that if you want `filterable`, there will be an input where you type things. Clicking on select's text area will focus the input, thus preventing dropdown from closing (because the component is expecting user to input something).

Suppose dropdown is closed as you requested, imagine the scenario where user is selecting inputted text with mouse, which triggers click thus closes the dropdown. I doubt this is an appropriate behavior for user-interaction.

If you do really need to do so, you can listen on native click event on select, then modify select's internal state.

---

The arrow (caret) implementation seems buggy now. I suppose you are talking about clicking that button fails to close dropdown?

**Comment by akki-jat** [comment] 2018-06-05 09:50
Hi @wacky6, I also thought that,
But in example on website, it is working fine.

### Take a look
[http://element.eleme.io/#/en-US/component/select#option-filtering](http://element.eleme.io/#/en-US/component/select#option-filtering)

**Comment by wacky6** [comment] 2018-06-05 11:57
Well, in your case `multiple` is also used. My guess would be `multiple` somehow interferes with caret's click handler.

**Comment by akki-jat** [comment] 2018-06-05 14:21
Yes, you are right @wacky6.

**Closed** 2019-04-02 07:32 UTC

**Comment by tripflex** [comment] 2020-01-16 19:08
For those coming here wondering how to CLOSE the dropdown when using `multiple` on a select element (since it stays open by default) when someone selects a value, add a `ref` to the `el-select` item, then on `@change` method call that ref with the `blur()` method:

Like this:

```vue
<el-select ref="mySelectRef" v-model="myModel" multiple="multiple" @change="$refs.mySelectRef.blur()">
...
</el-select>
```
