### ISSUE TITLE
[Bug Report] Notification component -> this.$notify position problem

### ISSUE THREAD

**Issue by Nbsaw** [ElemeFE/element#12417] opened 2018-08-19 15:27 UTC
### Element UI version
2.4.6

### OS/Browsers version
Window 10  / Chrome 67.0.3396.99

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5029/](https://jsfiddle.net/mmx38qxw/5029/)

### Steps to reproduce
Just click button then you can see .

### What is Expected?
[expected](https://jsfiddle.net/mmx38qxw/5030/)

### What is actually happening?
[Actually](https://jsfiddle.net/mmx38qxw/5029/)

**Comment by jikkai** [comment] 2018-08-19 16:57
Duplicate of #7389

**Closed by jikkai** 2018-08-19 16:57 UTC

**Comment by Nbsaw** [comment] 2018-08-20 00:47
@jikkai Hey is's not a duplicate issues . 

In actually demo i pass the same obj . Then work not good. 

But in expected demo i alaway pass a new obj , then work well .  

This issues is not due calls many times .
