### ISSUE TITLE
[Bug Report] el-table will display errors when using both show-summary and fixed

### ISSUE THREAD

**Issue by lyp256** [ElemeFE/element#6959] opened 2017-09-11 11:54 UTC
### Element UI version
1.4.4

### OS/Browsers version
chrome 61

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/75m4j2d2](https://jsfiddle.net/75m4j2d2)

### Steps to reproduce
el-table 同时使用固定列和合计时

### What is Expected?
合计显示在底部位置,与表格主体分开

### What is actually happening?
显示不正常

**Comment by Leopoldthecoder** [comment] 2017-09-11 12:29
Duplicate of #5415

**Closed by Leopoldthecoder** 2017-09-11 12:29 UTC
