### ISSUE TITLE
[Bug Report] Form component digital validation error

### ISSUE THREAD

**Issue by ZhijianZhang** [ElemeFE/element#11523] opened 2018-06-07 04:43 UTC
### Element UI version
2.4.0

### OS/Browsers version
win10 /  chrome 62

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2047/](https://jsfiddle.net/mmx38qxw/2047/)

### Steps to reproduce
 输入“222ss”之类的非数字类型

entering a non-numeric type such as "222ss" 

### What is Expected?
表单组件 提示 “请输入数字类型”

The form component prompts "please enter numeric type"

### What is actually happening?
表单组件不会提示 “请输入数字类型”

The form component does not prompt "please enter numeric type"

**Comment by jikkai** [comment] 2018-06-07 05:06
Duplicate of #11165

**Closed by jikkai** 2018-06-07 05:06 UTC
