### ISSUE TITLE
[Bug Report] When the table uses the aggregate attribute show-summary, the scrollbar below the column with the fixed attribute cannot be dragged and the unset behaves normally.

### ISSUE THREAD

**Issue by NBSeven** [ElemeFE/element#13757] opened 2018-12-13 11:55 UTC
### Element UI version
2.4.11

### OS/Browsers version
Google Chrome 71.0.3578.98（正式版本） （32 位）

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/NBSeven/7vg1q89b/1/](https://jsfiddle.net/NBSeven/7vg1q89b/1/)

### Steps to reproduce
直接拖动表格的滚动条

### What is Expected?
可以拖动fixed列的下方的滚动条

### What is actually happening?
无法拖动fixed列的下方的滚动条

**Comment by ziyoung** [comment] 2019-04-04 07:03
Duplicate of #5415

**Closed by ziyoung** 2019-04-04 07:03 UTC
