### ISSUE TITLE
[Bug Report] tree control deleted invalid

### ISSUE THREAD

**Issue by lixueninggg** [ElemeFE/element#12424] opened 2018-08-20 07:11 UTC
### Element UI version
2.4.6

### OS/Browsers version
windows 10 / chrom

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击删除无法删除

### What is Expected?
可以删除子节点

### What is actually happening?
无法删除子节点

**Comment by ziyoung** [comment] 2018-08-20 13:39
Duplicate of #12421

**Closed by ziyoung** 2018-08-20 13:39 UTC
