### ISSUE TITLE
[Bug Report] The DatePicker component default-value on the IE browser is browser

### ISSUE THREAD

**Issue by Tang1118** [ElemeFE/element#11184] opened 2018-05-16 04:16 UTC
### Element UI version
2.3.8

### OS/Browsers version
Windows / IE 10  

### Vue version
2.5.3

### Reproduction Link
[https://codepen.io/tang1118/pen/erLQPE](https://codepen.io/tang1118/pen/erLQPE)

### Steps to reproduce
1、:default-value='value1'
2、异步获取数据赋值'value1'：this.value1 = res.data.time
3、下拉框是有默认值和高亮的，input框里面为空

### What is Expected?
与其他浏览器一致

### What is actually happening?
IE浏览器有问题

**Comment by Leopoldthecoder** [comment] 2018-05-16 04:19
Duplicate of #8548

**Closed by Leopoldthecoder** 2018-05-16 04:19 UTC
