### ISSUE TITLE
[Bug Report] Cannot find module 'element-ui/lib/theme-chalk/fonts/element-icons.woff?t=1510834658947' 

### ISSUE THREAD

**Issue by Reechee88** [ElemeFE/element#9086] opened 2017-12-30 11:13 UTC
### Element UI version
2.0.10

### OS/Browsers version
Ubuntu 17.10

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
I have followed these steps:

http://element.eleme.io/#/en-US/component/custom-theme

I am using nuxt.js 1.0.0-rc11 with webapck 3

### What is Expected?
Working custom theme :)

### What is actually happening?
Hi,

I am tryin to customize the theme as it written here:
http://element.eleme.io/#/en-US/component/custom-theme

Content of my element-variables.scss:
`
$--collapse-border-color: #00A6EC;
$--collapse-header-color: #00A6EC;
$--collapse-header-height: 48px;
$--collapse-header-padding: 22px;
$--collapse-header-fill: white;
$--collapse-header-size: 18px;
$--collapse-content-fill: brown;
$--collapse-content-size: 20px;
$--collapse-content-color: orange;

$--font-path: '~element-ui/lib/theme-chalk/fonts';

@import "~element-ui/packages/theme-chalk/src/index";
`

When webpack compiles the scss, it gives me always this error:
Cannot find module 'element-ui/lib/theme-chalk/fonts/element-icons.woff?t=1510834658947'

I have checked and the element-icons.woff exists in the node_modules dir. I can't get rid of this annoying error.

What is the problem? How can I solve it?

Thanks,
Richard

**Comment by rudirocha** [comment] 2017-12-30 21:47
Hey. I'm having this also
These relative modules were not found:
```

* ./fonts/element-icons.ttf?t=1510834658947 in ./node_modules/css-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./src/assets/styles/main.scss
* ./fonts/element-icons.woff?t=1510834658947 in ./node_modules/css-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./src/assets/styles/main.scss
```
vue version is 2.9.1
element-ui version is 2.0.10

**Comment by Leopoldthecoder** [comment] 2017-12-31 01:47
@Reechee88 @rudirocha Please minify your project and upload it to GitHub.

**Comment by andreaschrist27** [comment] 2018-01-20 14:43
had same problem

**Comment by Leopoldthecoder** [comment] 2018-01-21 02:20
Closing for lack of reproduction.

**Closed by Leopoldthecoder** 2018-01-21 02:20 UTC

**Comment by yoyo837** [comment] 2018-01-23 10:58
@rudirocha @andreaschrist27 @Reechee88 

Do all of you use nuxt.js? This is part of the default webpack configuration from nuxt.js, which may be the cause of the problem:

**woff**

```js
{
  test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
  loader: "url-loader",
  options: {
    limit: 1000,
    name: "fonts/[name].[hash:7].[ext]"
  }
}
```

**Comment by yoyo837** [comment] 2018-01-23 11:11
Same problem...

custom theme [doc](http://element.eleme.io/#/en-US/component/custom-theme#update-scss-variables-in-your-project)

**Comment by yoyo837** [comment] 2018-01-23 11:36
If delete the font file query string, it works fine.
![e10c6111-42f4-4ad3-8288-9db9eb0fc490](https://user-images.githubusercontent.com/6134547/35273764-b3e6d2ac-0074-11e8-8a5b-61598b189140.jpeg)
![4526a91f-a3d9-4a79-abf3-afebf2163c3e](https://user-images.githubusercontent.com/6134547/35273766-b49f3d06-0074-11e8-8db4-977e88140b45.jpeg)

**Comment by alex-shamshurin** [comment] 2018-11-05 19:18
Same issue here

**Comment by Ramarti** [comment] 2019-01-03 16:13
vue-cli 3

* ~element-ui/lib/theme-chalk/fonts/element-icons.ttf in ../node_modules/css-loader??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-3-3!./src/assets/scss/element-variables.scss
* ~element-ui/lib/theme-chalk/fonts/element-icons.woff in ../node_modules/css-loader??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??ref--8-oneOf-3-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-3-3!./src/assets/scss/element-variables.scss

To install them, you can run: npm install --save ~element-ui/lib/theme-chalk/fonts/element-icons.ttf ~element-ui/lib/theme-chalk/fonts/element-icons.woff

**Comment by skray** [comment] 2019-01-08 19:04
I was getting this exact error and was able to resolve it.  I missed this important part of the [custom theme docs](https://element.eleme.io/#/en-US/component/custom-theme#update-scss-variables-in-your-project):

> Note that it is required to override icon font path to the relative path of Element's font files.

![2019-01-08 at 2 02 pm](https://user-images.githubusercontent.com/3921751/50852647-23c4fd00-134e-11e9-819d-85e05b01fdbf.png)

Adding `$--font-path: '~element-ui/lib/theme-chalk/fonts';` before importing the theme's index.scss fixed the error.

**Comment by summertian4** [comment] 2019-05-23 07:28
This is because  wrong path.
You should put your `style.css` in this path:
```
node_modules/element-ui/lib/theme-chalk
```
If you look at the style.css content, you will find out why

![image](https://user-images.githubusercontent.com/7870394/58233665-442aac80-7d6f-11e9-8772-24a5d49803e1.png)

**Comment by CracKerMe** [comment] 2020-06-22 15:34
> This is because wrong path.
> You should put your `style.css` in this path:
> 
> ```
> node_modules/element-ui/lib/theme-chalk
> ```
> 
> If you look at the style.css content, you will find out why
> 
> ![image](https://user-images.githubusercontent.com/7870394/58233665-442aac80-7d6f-11e9-8772-24a5d49803e1.png)

and then ? what should i do? i saw this before,and how to solve icon import ?????

**Comment by toramanlis** [comment] 2020-11-18 18:25
> I was getting this exact error and was able to resolve it. I missed this important part of the [custom theme docs](https://element.eleme.io/#/en-US/component/custom-theme#update-scss-variables-in-your-project):
> 
> > Note that it is required to override icon font path to the relative path of Element's font files.
> 
> ![2019-01-08 at 2 02 pm](https://user-images.githubusercontent.com/3921751/50852647-23c4fd00-134e-11e9-819d-85e05b01fdbf.png)
> 
> Adding `$--font-path: '~element-ui/lib/theme-chalk/fonts';` before importing the theme's index.scss fixed the error.

You are my best friend now
