### ISSUE TITLE
什么时候能升级到 Vue3+ 

### ISSUE THREAD

**Issue by zboboan** [ElemeFE/element#20365] opened 2020-11-03 02:28 UTC

**Comment by zazzaz** [comment] 2020-11-04 05:53
Element will stay with Vue 2.x

For Vue 3.0, we recommend using Element Plus from the same team

https://github.com/element-plus/element-plus

**Comment by cs1707** [comment] 2020-12-26 04:53
Duplicate of #20375

**Closed by cs1707** 2020-12-26 04:53 UTC
