### ISSUE TITLE
Is unique-opened set to false in [Bug Report] NavMenu or can only expand a sub menu at the same time?

### ISSUE THREAD

**Issue by zhangtaoBqteam** [ElemeFE/element#13491] opened 2018-11-20 10:09 UTC
### Element UI version
2.4.10

### OS/Browsers version
chorme 70.0.3538.102

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/batoug4d/](https://jsfiddle.net/batoug4d/)

### Steps to reproduce
我已经将menu中unique-opened属性设置成false，但是展开导航一，再展开导航二是，导航一会被收起来

### What is Expected?
展开导航一，再展开导航二时，导航一不要收起

### What is actually happening?
展开导航一，再展开导航二时，导航一收起

**Comment by ziyoung** [comment] 2018-11-20 11:42
Duplicate of #13452

**Closed** 2018-11-20 11:42 UTC
