### ISSUE TITLE
[Feature Request] Scroll lags with huge table data

### ISSUE THREAD

**Issue by mdsadique2** [ElemeFE/element#9862] opened 2018-02-23 08:31 UTC
### Existing Component
Yes

### Component Name
Element Table

### Description
I have a huge table with 50 columns and 100 rows. The table lags while scrolling, both horizontally and vertically.
Also, how to deactivate the parallax effect from fixed columns and rows?

**Comment by Leopoldthecoder** [comment] 2018-02-23 09:22
Duplicate of #4359 and #6089

**Closed by Leopoldthecoder** 2018-02-23 09:22 UTC
