### ISSUE TITLE
[Bug Report] In the table component, if there is a fixed column, the input component is displayed after changing to the edit state, and the focus method of calling the input component is invalid.

### ISSUE THREAD

**Issue by Asces** [ElemeFE/element#14093] opened 2019-01-16 03:06 UTC
### Element UI version
2.4.10

### OS/Browsers version
windows 7/chrome 71.0.3578.98(32)

### Vue version
2.5.20

### Reproduction Link
[https://jsfiddle.net/k19f6eo8/7/](https://jsfiddle.net/k19f6eo8/7/)

### Steps to reproduce
Delete the fixed attribute in the el-table-column tag. After double-clicking the line, the input component can focus.

### What is Expected?
In-row editing in the table component, in the edit state, call the focus method of the input component in the this.$nextTick event, input can focus, 

### What is actually happening?
if there is a fixed column in the table, it will not work.

**Comment by xuliangzhan** [comment] 2019-01-23 07:51
可以参考 [https://github.com/xuliangzhan/vue-element-extends](https://github.com/xuliangzhan/vue-element-extends)

**Comment by ziyoung** [comment] 2019-02-19 10:27
Duplicate of #10588

**Closed by ziyoung** 2019-02-19 10:27 UTC
