### ISSUE TITLE
Date selection is not available after [Feature Request] uses H5 full screen to enlarge API.

### ISSUE THREAD

**Issue by never51463** [ElemeFE/element#12641] opened 2018-09-06 03:26 UTC
### Existing Component
是

### Component Name
DatePicker

### Description
使用H5全屏放大API requestFullscreen之后日期选择不可用，修改过Z-index之后点击日期无法修改值

**Comment by island205** [comment] 2018-11-05 11:20
重现步骤提供一下？

**Comment by dyw934854565** [comment] 2019-02-28 02:37
components with dropdown has this issue

//code.h5jun.com/joye/edit?output

**Comment by goforward01** [comment] 2019-03-05 09:19
Actually, It seems like the old issue #12872。The issue does cover the components like dialog, message box etc. When exit full screen, the component mentioned above could have a similar issue.

**Comment by island205** [comment] 2019-03-06 07:47
Duplicate of #12872

**Comment by island205** [comment] 2019-03-06 08:51
@never51463 @dyw934854565 using  `document.body.requestFullscreen()` is a solution. https://code.h5jun.com/wozi/1/edit?output

**Closed by island205** 2019-03-06 08:51 UTC
Labels: component: date-picker, type: bug

**Comment by goforward01** [comment] 2019-03-06 09:21
Of course, Maybe the solutions above could solve others' problems.
In my case, one single DOM element part of the page could enter the full screen mode instead of the body，so **document.body.requestFullscreen** can't do the trick. By the way, neither do add **id="full"** to the body tag solve my problem. My suggestion is listening to the event of **fullscreenchange**, and do something when user trigger the **esc** event to quit full screen.

**Comment by island205** [comment] 2019-03-06 10:01
the root cause is https://github.com/ElemeFE/element/issues/12872#issuecomment-433699962.

mask and dropdown element are appended to body, if we move those element to the full element when `fullscreenchange` event fire, may workable, but more complex,  uncontrollable.

you also can use:

```html
el-dialog :modal-append-to-body="false"
el-select :popper-append-to-body="false"
```

**Comment by GitHdu** [comment] 2020-03-25 08:46
> the root cause is [#12872 (comment)](https://github.com/ElemeFE/element/issues/12872#issuecomment-433699962).
> 
> `mask` and `dropdown` element are appended to body, if we move those element to the full element when `fullscreenchange` event fire, may workable, but more complex, uncontrollable.
> 
> you also can use:
> 
> ```
> el-dialog :modal-append-to-body="false"
> el-select :popper-append-to-body="false"
> ```

how to fix it about `el-data-picker`

**Comment by longPanda** [comment] 2020-05-14 06:55
解决了吗？还真有这个问题~

**Comment by jawn-ha** [comment] 2020-07-27 01:27
这么大的问题不解决就直接close了？？？

**Comment by taojiujiu1986** [comment] 2021-01-11 03:43
I got this solution!!! pls Follow this blog, It can resolve your problem！
http://www.gudii.cn/post/22.html

**Comment by Sinosaurus** [comment] 2021-03-30 14:32
@GitHdu 解决了吗

**Comment by GitHdu** [comment] 2021-03-31 06:09
> @GitHdu 解决了吗
上面那篇文章有通用解决方案，之前是点击选择就直接退出全屏
