### ISSUE TITLE
[Bug Report] ElTooltip tabindex interferes with other elements

### ISSUE THREAD

**Issue by OsirisFrik** [ElemeFE/element#14405] opened 2019-02-19 02:12 UTC
### Element UI version
2.5.4

### OS/Browsers version
MacOs 10.14.1 / Chrome 72.0.3626.109

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/osirisfrik/kw9usbja/20/](https://jsfiddle.net/osirisfrik/kw9usbja/20/)

### Steps to reproduce
use a tooltip element before an input field, add to input field the attribute index tab in 0 and now try focus this in first place on tab button

### What is Expected?
if i set the index tab in tooltip to -1 and the input field on 0, i expected the first focus go to input field and ignore tooltip tabindex

### What is actually happening?
all time tooltip focus in first place and ignore my attribute tabindex when i sended on the element

**Comment by ziyoung** [comment] 2019-03-05 08:34
Duplicate of #11519

**Closed by ziyoung** 2019-03-05 08:34 UTC
