### ISSUE TITLE
[Bug Report] Upload multiple only callback once on-success?

### ISSUE THREAD

**Issue by cntaoyu** [ElemeFE/element#8343] opened 2017-11-17 02:33 UTC
### Element UI version
2.0.0

### OS/Browsers version
Mac OS X 10_13_1 Chrome/61.0.3163.100

### Vue version
2.5.2

### Reproduction Link
[https://zy62.com/upload/](https://zy62.com/upload/)

### Steps to reproduce
选择多张图片上传仅收到一个on-success回调，由于我上传的token有时效性，很抱歉没用jsfiddle的链接

### What is Expected?
收到多个on-success回调

### What is actually happening?
仅收到一个on-success回调

**Comment by Leopoldthecoder** [comment] 2017-11-17 02:59
Duplicate of #8047

**Closed by Leopoldthecoder** 2017-11-17 02:59 UTC
