### ISSUE TITLE
[Bug Report] NavMenu active item is changed after collapse and expand

### ISSUE THREAD

**Issue by limeng408** [ElemeFE/element#11751] opened 2018-06-26 03:38 UTC
### Element UI version
2.4.1

### OS/Browsers version
chrome 76

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/ejfqxy7n/](https://jsfiddle.net/ejfqxy7n/)

### Steps to reproduce
1 select a menu item in NavMenu expand status
2 collapse NavMenu
3 expand NavMenu

### What is Expected?
the active menu item is not changed

### What is actually happening?
the active menu item is changed

**Comment by Leopoldthecoder** [comment] 2018-06-26 03:45
Duplicate of #10622

**Closed by Leopoldthecoder** 2018-06-26 03:45 UTC
