### ISSUE TITLE
[Bug Report] Background tab enters loop untill it is focused

### ISSUE THREAD

**Issue by Erdboden** [ElemeFE/element#8295] opened 2017-11-15 08:23 UTC
### Element UI version
2.0.3

### OS/Browsers version
Fedora 25/Chrome 62.0.3202.75, Firefox 56.0

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/qrq3qdf4](https://jsfiddle.net/qrq3qdf4/3/)

### Steps to reproduce
1 - Open reproduction link

2 - Check console log

3 - Click on second tab

4 - Check console log

### What is Expected?
No loop for unfocused tabs

### What is actually happening?
Infinite re-rendering if tab is not pressed

**Comment by Leopoldthecoder** [comment] 2017-11-15 09:16
Duplicate of #8266

**Closed by Leopoldthecoder** 2017-11-15 09:16 UTC
