### ISSUE TITLE
The [Bug Report] tree component is cut off when the node name is very long, and there is no horizontal scroll bar.

### ISSUE THREAD

**Issue by showmethecode9527** [ElemeFE/element#11209] opened 2018-05-17 06:52 UTC
### Element UI version
2.3.8

### OS/Browsers version
windows

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Mathink/swvzfxd3/2/](https://jsfiddle.net/Mathink/swvzfxd3/2/)

### Steps to reproduce
当节点名称很长时即会重现，重现链接中的效果出现在「一级 3 > 二级 3-2」中

### What is Expected?
当节点名称很长时，整个 tree 自动出现水平滚动条

### What is actually happening?
当节点名称很长时，整个 tree 没有出现水平滚动条，节点名称没截断

**Comment by Leopoldthecoder** [comment] 2018-05-17 07:00
Duplicate of #4944

**Closed by Leopoldthecoder** 2018-05-17 07:00 UTC
