### ISSUE TITLE
[Bug Report] cascader show error in certain conditions

### ISSUE THREAD

**Issue by zymkoko** [ElemeFE/element#16517] opened 2019-07-11 06:19 UTC
### Element UI version
2.10.1

### OS/Browsers version
75.0.3770.100（正式版本） （64 位）

### Vue version
2.6.6

### Reproduction Link
https://codepen.io/yufengkoko/pen/QXYeqW

### Steps to reproduce
1. select the third menuitem (选中第三个资源的某一项)
2. select the  first/second menuitem (重新选择指南/组件)
3. open the cascader (再次打开级联器)

### What is Expected?
the third menuitem's panel is  close  and the text's color is normal( not '#409EFF') (面板正常显示)

### What is actually happening?
the third menuitem's panel is open and the text is active status (第三个资源的 panel 打开, 并且资源二字是蓝色状态)

**Comment by SimonaliaChen** [comment] 2019-07-25 02:02
Duplicate of #16665

**Closed by SimonaliaChen** 2019-07-25 02:02 UTC
