### ISSUE TITLE
The [Bug Report] Upload beforeUpload method changes header to not take effect

### ISSUE THREAD

**Issue by yiwuyu** [ElemeFE/element#10616] opened 2018-04-09 05:21 UTC
### Element UI version
2.1.0

### OS/Browsers version
mac/chrome

### Vue version
2.5.12

### Element UI Component
upload

### Reproduction Link
[https://jsfiddle.net/yiwuyu/hjp3wbre/](https://jsfiddle.net/yiwuyu/hjp3wbre/)

### Steps to reproduce
点击上传按钮

### What is Expected?
在beforeUpload 能对header进行修改

### What is actually happening?
requestHeader 里 xscf 为 1 ，没有在beforeUpload 方法里被修改为时间戳
![image](https://user-images.githubusercontent.com/25633994/38480562-c827f970-3bf8-11e8-8863-e25d43672174.png)

**Comment by Leopoldthecoder** [comment] 2018-04-09 05:29
Duplicate of https://github.com/ElemeFE/element/issues/10507

**Closed by Leopoldthecoder** 2018-04-09 05:29 UTC
