### ISSUE TITLE
[Feature Request] Slider used in vue, its value in watch will trigger twice automatically

### ISSUE THREAD

**Issue by xuqingxi** [ElemeFE/element#13090] opened 2018-10-18 10:19 UTC
### Existing Component
Yes

### Component Name
Slider

### Description
We send a request based on changes in the data, but its redundant triggers create more useless requests,and the data returned by the request is overlaid on the map
![qq 20181018175636](https://user-images.githubusercontent.com/38125259/47148045-30fbbe00-d302-11e8-9339-698126c9fd76.png)

**Comment by ziyoung** [comment] 2018-10-23 09:11
Duplicate of #13095

**Closed by ziyoung** 2018-10-23 09:11 UTC
