### ISSUE TITLE
[Feature Request] Traditional Column Auto Sizing

### ISSUE THREAD

**Issue by digipigeon** [ElemeFE/element#10062] opened 2018-03-07 19:56 UTC
### Existing Component
Yes

### Component Name
el-table

### Description
I am really missing the ability to allow table columns to be sized based on the (amount of) content of the cells, although this does not seem to be the fashion, traditional table widths can be very useful.

**Comment by Leopoldthecoder** [comment] 2018-03-08 04:06
Duplicate of #4159. And we have no plan to support this.

**Closed by Leopoldthecoder** 2018-03-08 04:06 UTC
