### ISSUE TITLE
[Bug Report] table with height setting cause horizontal scroll in ie11

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#6709] opened 2017-08-26 05:06 UTC
### Element UI version
1.4.3

### OS/Browsers version
win10

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/baks5159/](https://jsfiddle.net/baks5159/)

### Steps to reproduce
sorry,jsfiddle throw error in ie,but this bug exist only in ie.
you can open element office website in ie ,and can see this bug.
http://element.eleme.io/#/zh-CN/component/table
the fifth table demo can recurrent this bug.

### What is Expected?
has no useless  horizontal scroll in ie11

### What is actually happening?
has  useless  horizontal scroll in ie11

**Comment by lerit** [comment] 2017-08-26 05:07
![default](https://user-images.githubusercontent.com/4743467/29738771-7927f208-8a5f-11e7-8e86-a9c5362be660.png)

**Comment by arvidkahl** [comment] 2017-08-26 08:28
I have noticed the same problem in Chrome on a MacBook Pro with a mouse attached. The `fit` property will calculate a width that ignores the vertical scrollbar inserted by the browser, this making the content box bigger than the available space.

**Comment by arvidkahl** [comment] 2017-08-26 09:54
Resizing the browser window significantly will make the horizontal scrollbar go away, by the way.

**Comment by Leopoldthecoder** [comment] 2017-08-27 09:33
Duplicate of #2945

**Closed by Leopoldthecoder** 2017-08-27 09:33 UTC
