### ISSUE TITLE
[Bug Report]Table can not be displayed in IE 11 and firefox (the official website has a problem in the IE table display)

### ISSUE THREAD

**Issue by no-simple** [ElemeFE/element#10246] opened 2018-03-20 03:09 UTC
### Element UI version
2.2.2

### OS/Browsers version
window/ IE 11/firefox

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/1rLhxwnu/](https://jsfiddle.net/1rLhxwnu/)

### Steps to reproduce
①请在IE11 环境下打开  jsfiddle  网站链接。
②已在jsfiddle代码中放置官网的demo代码，在chome中显示正常，

### What is Expected?
在IE11和firefox中table正常显示，也变变形情况。

### What is actually happening?
在IE11和firefox中talbe  显示空白。

**Comment by Leopoldthecoder** [comment] 2018-03-20 03:28
Duplicate of #9916

**Closed by Leopoldthecoder** 2018-03-20 03:28 UTC
