### ISSUE TITLE
[Feature Request] rtl support

### ISSUE THREAD

**Issue by jelofen** [ElemeFE/element#9884] opened 2018-02-25 09:49 UTC
### Existing Component
Yes

### Component Name
all

### Description
Hello 
I wanted to know whether element ui supports rtl components or not.
If not, do you have any plan to support it? because I saw some rtl languages in your i18n feature, I asumed that you might have this support or plan to have it in future.

**Comment by QingWei-Li** [comment] 2018-02-26 07:37
Duplicate of #2037

**Closed by QingWei-Li** 2018-02-26 07:37 UTC
