### ISSUE TITLE
[Bug Report] el-table tree structure has no events

### ISSUE THREAD

**Issue by seadog16** [ElemeFE/element#15038] opened 2019-04-10 03:06 UTC
### Element UI version
2.7.0

### OS/Browsers version
Max

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/XQpQGq](https://codepen.io/anon/pen/XQpQGq)

### Steps to reproduce
展开和收起树形数据

### What is Expected?
提供展开树形展开事件，建议展开行和展开树形都用expand-change

### What is actually happening?
展开树形结构无事件

**Comment by ziyoung** [comment] 2019-05-07 08:00
Duplicate of #15170

**Closed by ziyoung** 2019-05-07 08:00 UTC
