### ISSUE TITLE
[Bug Report] Error position in clear suffix location in input component when it in a undisplay element

### ISSUE THREAD

**Issue by Zane0816** [ElemeFE/element#11664] opened 2018-06-19 06:40 UTC
### Element UI version
2.4.0

### OS/Browsers version
Windos 10 build 1803/ Chrome 67.0.3396.87

### Vue version
2.5.16

### Reproduction Link
[http://jsfiddle.net/mmx38qxw/2405/](http://jsfiddle.net/mmx38qxw/2405/)

### Steps to reproduce
click Show DIV and Enter text

### What is Expected?
 clear suffix in correct position

### What is actually happening?
clear suffix not in correct position

**Comment by Leopoldthecoder** [comment] 2018-06-25 08:56
Duplicate of #11441

**Closed by Leopoldthecoder** 2018-06-25 08:56 UTC
Labels: component: input
