### ISSUE TITLE
[Bug Report] tree dragged and dragged the mistake

### ISSUE THREAD

**Issue by hwf930308** [ElemeFE/element#10457] opened 2018-03-29 10:30 UTC
### Element UI version
2.3.2

### OS/Browsers version
window10/Google Chrome 65.0.3325.181（正式版本）

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/qpy5m6za/4/](https://jsfiddle.net/qpy5m6za/4/)

### Steps to reproduce
tree 组件拖拽不与任何tree元素接触
错误文件 tree.vue
原组件代码：
if (draggingNode && !dropNode) {
        this.$emit('node-drag-end', draggingNode.node, dropNode.node, dropType, event);
      }

### What is Expected?
js无报错

### What is actually happening?
'node' of null

**Comment by Leopoldthecoder** [comment] 2018-03-29 14:14
Duplicate of #10458

**Closed by Leopoldthecoder** 2018-03-29 14:14 UTC
