### ISSUE TITLE
[Bug Report] Draggable tree lost node's checked status when node was dropped

### ISSUE THREAD

**Issue by dongsuo** [ElemeFE/element#12612] opened 2018-09-04 04:58 UTC
### Element UI version
2.4.6

### OS/Browsers version
Win10/ Chrome 68.0.3440.106

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/xuxiaofei/x68pm5og/1/](https://jsfiddle.net/xuxiaofei/x68pm5og/1/)

### Steps to reproduce
1. Check any node.
2. Drag and drop checked node to another place.

### What is Expected?
Node that checked maintain it's checked status after dragged and dropped.

### What is actually happening?
Node that checked lost it's checked status after dragged and dropped.

**Comment by ziyoung** [comment] 2018-09-05 02:34
Duplicate of #11927

**Closed by ziyoung** 2018-09-05 02:34 UTC
