### ISSUE TITLE
[Bug Report] IE11 value not render when placeholder in traditional chinese

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#10512] opened 2018-04-02 05:41 UTC
### Element UI version
2.3.2

### OS/Browsers version
 Windows 7 / IE 11

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/1210/](https://jsfiddle.net/mmx38qxw/1210/)

### Steps to reproduce
1.set default data
2.set placeholder in traditional chinese
3.using vm.$set change value
4.if placeholder not in traditional chinese value render
   if placeholder in traditional chinese value not render
5.all element ui component with placeholder attribute not render correctly
### What is Expected?
value render on IE11

### What is actually happening?
value not render on IE11

**Comment by Leopoldthecoder** [comment] 2018-04-02 05:56
Duplicate of #8548

**Closed by Leopoldthecoder** 2018-04-02 05:56 UTC
