### ISSUE TITLE
[Bug Report] table horizontal scroll bar can't dragable

### ISSUE THREAD

**Issue by lu0371** [ElemeFE/element#11155] opened 2018-05-15 00:37 UTC
### Element UI version
2.3.8

### OS/Browsers version
windows 7/firefox 59.0.3 (64 bit),chrome 39.0.2171.95

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/jbrneutL/](https://jsfiddle.net/jbrneutL/)

### Steps to reproduce
1、set el-table width
2、make first column fixed，and Make the sum of column width is greater than the table width
3、set table data is empty []
then the horizontal scroll bar will show,but bad drag

### What is Expected?
then the horizontal scroll bar will show,and drag normal

### What is actually happening?
bad drag

**Comment by Leopoldthecoder** [comment] 2018-05-15 02:38
Duplicate of #5415

**Closed by Leopoldthecoder** 2018-05-15 02:38 UTC
