### ISSUE TITLE
[Bug Report] table component formatter event, table row hover repeatedly triggers all formatter events

### ISSUE THREAD

**Issue by aigenisi** [ElemeFE/element#14849] opened 2019-03-26 11:51 UTC
### Element UI version
2.6.3

### OS/Browsers version
mac 10.14.3  /  chrome 73

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/pen/](https://codepen.io/pen/)

### Steps to reproduce
1。在   <el-table-column:formatter=""    添加事件
2。当鼠标 在表格行内（非表头）移动时，会无限触发所有formatter事件

### What is Expected?
只在加载数据时执行格式方法

### What is actually happening?
hover重复触发

**Comment by ziyoung** [comment] 2019-03-27 07:09
Duplicate of #14729

**Closed by ziyoung** 2019-03-27 07:09 UTC
