### ISSUE TITLE
[Feature Request] The show-overflow-tooltip attribute can set multiple lines.

### ISSUE THREAD

**Issue by jinyanliang** [ElemeFE/element#16920] opened 2019-08-06 07:37 UTC
### Existing Component
是

### Component Name
table

### Description
I hope that the show-overflow-tooltip attribute can be set to multiple lines. By forcibly changing the css, it cannot be achieved. After the line break, the tooltip does not take effect.

**Comment by ziyoung** [comment] 2019-09-03 02:58
Duplicate of #13919

**Closed by ziyoung** 2019-09-03 02:58 UTC
