### ISSUE TITLE
[Bug Report] table incorporates data changes and dislocates them

### ISSUE THREAD

**Issue by l543227182** [ElemeFE/element#17087] opened 2019-08-19 09:41 UTC
### Element UI version
2.11.1

### OS/Browsers version
Chrome最新

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
1.普通表格,绑定数据变化(列增多,行增多)
2.没有重新链接

### What is Expected?
1. 不会错位

### What is actually happening?
数据错位(行错位)

**Comment by ziyoung** [comment] 2019-09-05 08:59
Duplicate of #17060

**Closed by ziyoung** 2019-09-05 08:59 UTC
