### ISSUE TITLE
The @active-item-change event in [Bug Report] el-cascader calls multiple times

### ISSUE THREAD

**Issue by liunewshine** [ElemeFE/element#8267] opened 2017-11-14 14:19 UTC
### Element UI version
2.0.4

### OS/Browsers version
win10

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/liunewshine/tskkjrk1/](https://jsfiddle.net/liunewshine/tskkjrk1/)

### Steps to reproduce
点击一次父级选项

### What is Expected?
每次点击只调用一次@active-item-change，并且返回值应该不只有value，还应该加上点击的object

### What is actually happening?
控制台多次（1次，两次或者三次）输出active item： xxxx

**Comment by Leopoldthecoder** [comment] 2017-11-15 02:40
Duplicate of #8240

**Closed by Leopoldthecoder** 2017-11-15 02:40 UTC
