### ISSUE TITLE
[Bug Report] Popover display bug

### ISSUE THREAD

**Issue by christophetrinh** [ElemeFE/element#8227] opened 2017-11-13 16:23 UTC
### Element UI version
2.0.4

### OS/Browsers version
Chrome

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
While clicking one time on the delete button, the popover is displaying quickly then it disappeared. 
Clicking on it a second time displayed it, but while clicking on Confirm button closed the popover instead of opening a new popover.

### What is Expected?
It should be expected to display directly the popover on click, and allow to click inside it without closing the popover.

### What is actually happening?
Clicking on popover closes it immediately

**Comment by ryantbrown** [comment] 2017-11-13 16:26
+1 - This is currently breaking every popover on our production website. Our code hasn't changed so it must be the CSS file loaded via the CDN?

**Comment by WangHansen** [comment] 2017-11-14 00:27
+1

**Comment by cqliulei** [comment] 2017-11-14 00:49
+1，2.03版本不会出现这个问题~~

**Comment by callmeDAY** [comment] 2017-11-14 02:36
+1

**Comment by Leopoldthecoder** [comment] 2017-11-14 02:37
Duplicate of #8186

**Closed by Leopoldthecoder** 2017-11-14 02:37 UTC
