### ISSUE TITLE
[Bug Report] tree structure filter node method, empty filter conditions, the return of the tree structure by default to expand all nodes

### ISSUE THREAD

**Issue by Angelsindevil** [ElemeFE/element#7852] opened 2017-10-30 10:35 UTC
### Element UI version
2.0.1

### OS/Browsers version
10.12.6／61.0.3163.100

### Vue version
2.3.3

### Reproduction Link
[https://codepen.io/zhengxiaowen/pen/wrLbQw](https://codepen.io/zhengxiaowen/pen/wrLbQw)

### Steps to reproduce
在树形结构过滤结点时，清空过滤条件，树形结构的所有结点默认展开了（初始化的时候，是不默认展开的）

### What is Expected?
清空过滤条件，应该要和初始化设置的状态一样，而并非默认展开所有结点

### What is actually happening?
清空过滤条件，默认展开了所有结点

**Comment by Leopoldthecoder** [comment] 2017-10-30 11:05
Fixed in #7853

**Closed by Leopoldthecoder** 2017-10-30 11:05 UTC

**Comment by AlexZhong22c** [comment] 2019-02-26 08:26
@Leopoldthecoder 

Are you sure that the problem was fixed?

I try his `Reproduction Link`，import `https://unpkg.com/element-ui@2.5.4/lib/index.js`，which is new version elementjs, and see the problem he described is still.
