### ISSUE TITLE
The el-input input input/delete text will automatically jump to the end of the text in [Bug Report] Sogou browser

### ISSUE THREAD

**Issue by visionding** [ElemeFE/element#14657] opened 2019-03-10 06:45 UTC
### Element UI version
2.4.6

### OS/Browsers version
Windows 10 / Sogou 8.5.7

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
在Input组件中输入任意文本，然后将光标移到中间，输入/删除任意文字

### What is Expected?
正常

### What is actually happening?
光标跳转到文本末尾

**Comment by arunbscmdu** [comment] 2019-03-13 11:59
I too facing the same issue on safari browser.

**Comment by ColorWolfKing** [comment] 2019-03-14 02:04
I found that version 2.3.9 was fine and version 2.4.11 had this problem, so I think it may be the compatibility problem of CompositionEvent.

**Comment by jlfenaux** [comment] 2019-03-19 07:54
Same issue on Safari. Indeed the official website works until 2.3.9. After that, the problem is present.

**Comment by wacky6** [comment] 2019-03-19 14:08
Should be fixed https://github.com/ElemeFE/element/pull/14572

Please verify this jsfiddle jsfiddle.net/da40mcgq . If the problem persist, comment below.

**Comment by jlfenaux** [comment] 2019-03-20 07:47
The jsfiddle does work properly.

**Closed** 2019-03-20 07:49 UTC
