### ISSUE TITLE
[Bug Report] Strange css style of active tab title in <el-tabs>

### ISSUE THREAD

**Issue by jwenjian** [ElemeFE/element#10452] opened 2018-03-29 08:22 UTC
### Element UI version
2.3.2

### OS/Browsers version
Win10 / Chrome 65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/2kah1n56/](https://jsfiddle.net/2kah1n56/)

### Steps to reproduce
1. click any of the tab titles
2. minimize your browser window
3. reactive your browser window

### What is Expected?
The active tab title has the same style with the one before the browser minimize

### What is actually happening?
The active tab title has a strange border(both top, left, bottom, right)

**Comment by Leopoldthecoder** [comment] 2018-03-29 08:26
Duplicate of #9981

**Closed by Leopoldthecoder** 2018-03-29 08:26 UTC

**Comment by jwenjian** [comment] 2018-03-29 08:34
@Leopoldthecoder 

No padding change issue on my side, just the style changes
