### ISSUE TITLE
[Bug Report] el-select with multiple and filterable property can not be closed by clicking the input area

### ISSUE THREAD

**Issue by Kol96** [ElemeFE/element#12305] opened 2018-08-09 06:56 UTC
### Element UI version
2.4.5

### OS/Browsers version
Chrome  68.0.3440.106

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4767/](https://jsfiddle.net/mmx38qxw/4767/)

### Steps to reproduce
click on select component and then click on the input area

### What is Expected?
el-select-dropdown component will be closed

### What is actually happening?
el-select-dropdown component is not closing

**Comment by ziyoung** [comment] 2018-08-09 06:58
Duplicate of #11846

**Closed by ziyoung** 2018-08-09 06:58 UTC
