### ISSUE TITLE
[Bug Report] Customize the header slot and the table uses fixed. When the popver is manually triggered by the V-model binding value, two instances are generated.

### ISSUE THREAD

**Issue by Fight-for-Freedom2019** [ElemeFE/element#14285] opened 2019-02-01 03:51 UTC
### Element UI version
2.5.3

### OS/Browsers version
windows 10 /chrome  71.0.3578.98

### Vue version
2.6.0-beta.3

### Reproduction Link
[https://jsfiddle.net/amxf3q59/12/](https://jsfiddle.net/amxf3q59/12/)

### Steps to reproduce
1.当table 用fixed属性时
2.自定义表头嵌套的是el-popover组件且v-model绑值 手动触发
3.点击表头按钮可以发现端倪

### What is Expected?
只生成一个实例 渲染出一个popover，这个bug不解决的话 项目中table就无法用fixed

### What is actually happening?
生成两个一样的popover

**Comment by lightning0016** [comment] 2019-02-12 00:14
i have the same question

**Comment by proceduremonkey** [comment] 2019-02-13 03:34
when i used render-header, i have taken element-ui function from source codes to solve this,but it  result that effectiveness loading too low. And then, use slot can solve the  effectiveness ,but generate two instances.So，i hope element teams can solve that

**Comment by ziyoung** [comment] 2019-03-05 03:51
Duplicate of #10588

**Closed by ziyoung** 2019-03-05 03:51 UTC
