### ISSUE TITLE
[Feature Request] wants the counter to increase the parameters to control the decimal point

### ISSUE THREAD

**Issue by DJinGo1201** [ElemeFE/element#9552] opened 2018-01-30 07:07 UTC
### Existing Component
是

### Component Name
inputNumber

### Description
希望可以控制数值保留几位小数点或可以自定义规则

**Comment by Leopoldthecoder** [comment] 2018-01-30 12:08
Duplicate of #8515

**Closed by Leopoldthecoder** 2018-01-30 12:08 UTC
