### ISSUE TITLE
[bug report] the content of the drawer is too high to scroll

### ISSUE THREAD

**Issue by houkunlin** [ElemeFE/element#18968] opened 2020-03-16 02:13 UTC
### Element UI version
2.13.0

### OS/Browsers version
Win10/Google Chrome 80.0.3987.132

### Vue version
2.6.11

### Reproduction Link
https://codepen.io/houkunlin/pen/WNvJRVM

### Steps to reproduce
给 Drawer 添加内容的高度超过屏幕的高度

### What is Expected?
内容超过高度能够自动显示滚动条

### What is actually happening?
不显示滚动条，内容超过高度无法显示内容

**Comment by zhanghao19920218** [comment] 2021-01-29 02:56
Need Now!!!

**Comment by cs1707** [comment] 2021-04-20 10:54
Duplicate of #20712

**Closed by cs1707** 2021-04-20 10:54 UTC
