### ISSUE TITLE
[Bug Report] There's something wrong with the "gutter" class

### ISSUE THREAD

**Issue by tonytangcn** [ElemeFE/element#6789] opened 2017-08-31 03:02 UTC
### Element UI version
1.4.3

### OS/Browsers version
win10 / Firefox, Edge, IE

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/9dr49jb8/5/](https://jsfiddle.net/9dr49jb8/5/)

### Steps to reproduce
please open the link in firefox or edge or IE

### What is Expected?
After you open the link, you would see the horizontal scrollbar reaches to the left side of right-fixed column, but you cannot scroll it. and there appears the vertical scrollbar, after you scroll it to the bottom, you would see the table body and the right-fixed column are misaligned. well, i didn't dig deep into the source code, but i found there a container with "gutter" class and the end of table row which has 1px wide solid border in browsers like FF, edge, ie, etc. however chrome interprets pretty ok. I modified the width of gutter in "index.css" from 1px to 0px, and the problem solved, so i suppose there's some tiny compatibility issues with the "gutter" class among different browsers.

### What is actually happening?
.el-table--fit th.gutter, .el-table--fit td.gutter {
    border-right-width: 1px;
}
==>
.el-table--fit th.gutter, .el-table--fit td.gutter {
    border-right-width: 0px;
}

**Comment by Leopoldthecoder** [comment] 2017-08-31 03:08
Duplicate of #5251

**Closed by Leopoldthecoder** 2017-08-31 03:08 UTC
