### ISSUE TITLE
[bug report] when El image is in El dialog, closing image viewer through ESC will close El dialog at the same time

### ISSUE THREAD

**Issue by takkiTang** [ElemeFE/element#20682] opened 2021-01-14 03:13 UTC
### Element UI version
2.14.1

### OS/Browsers version
mac os

### Vue version
2.6.12

### Reproduction Link
https://codepen.io/takkiTang/pen/XWjyjzM

### Steps to reproduce
1. 点击Button
2. 点击图片
3. 打开 el-viewer
4. ESC关闭 el-viewer

### What is Expected?
只关闭el-viewer

### What is actually happening?
同时关闭了el-dialog和el-viewer

**Comment by cs1707** [comment] 2021-03-19 08:45
fixed
Duplicate of #20847

**Closed by cs1707** 2021-03-19 08:45 UTC
Labels: component: image
