### ISSUE TITLE
[Bug Report] table title dislocation problem

### ISSUE THREAD

**Issue by cooliean** [ElemeFE/element#5257] opened 2017-06-08 11:47 UTC
### Element UI version
1.3.5

### OS/Browsers version
macOS 10.12.5   safari  10.1.1

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
直接运行就可以了，带边框表格

### What is Expected?
表头跟下面的列对齐

### What is actually happening?
表头跟下面的列不对齐

<img width="598" alt="qq20170608-194750 2x" src="https://user-images.githubusercontent.com/4754617/26927186-6ca9fd06-4c83-11e7-9b44-04c3d64f09aa.png">

**Comment by cooliean** [comment] 2017-06-08 12:23
Use this 
http://element.eleme.io/#/zh-CN/component/table

**Comment by Leopoldthecoder** [comment] 2017-06-09 02:13
Duplicate of #5251

**Closed by Leopoldthecoder** 2017-06-09 02:13 UTC
