### ISSUE TITLE
[Feature Request] element will rebuild by vue3.0 in future ,maybe in 4 months

### ISSUE THREAD

**Issue by zjxzjx54** [ElemeFE/element#19228] opened 2020-04-22 01:02 UTC
### Existing Component
Yes
### Component Name
all components in element-UI

### Description
element will rebuild by vue3.0 in future ,maybe in 4 months?

**Comment by zazzaz** [comment] 2020-08-20 10:50
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment] 2020-12-26 05:01
Duplicate of #20375

**Closed by cs1707** 2020-12-26 05:01 UTC
