### ISSUE TITLE
[Bug Report] [Bug Report] Autocomplete doesn't work properly in IE

### ISSUE THREAD

**Issue by fengqinglingyu** [ElemeFE/element#7533] opened 2017-10-17 04:21 UTC
### Element UI version
1.4.7

### OS/Browsers version
Windows 7 64bit / IE 10 and IE 11

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/qy6oteet/](https://jsfiddle.net/qy6oteet/)

### Steps to reproduce
In IE，Element UI can't select the matching value you want.
Once you select the item you want, the dropdown menu go away.
It workes properly in chrome and firefox. 
IE version 10, 11

### What is Expected?
Hope to repair this question , thus it can work properly in IE.

### What is actually happening?
in IE 10 and IE 11, I don't have earlier version IE, but I think it exists as well

**Comment by Leopoldthecoder** [comment] 2017-11-19 08:56
Duplicate of #4583

**Closed by Leopoldthecoder** 2017-11-19 08:56 UTC
