### ISSUE TITLE
[Bug Report] Select Component popup animation exception in Chrome 74

### ISSUE THREAD

**Issue by justyeh** [ElemeFE/element#15484] opened 2019-05-09 08:52 UTC
### Element UI version
2.8.2

### OS/Browsers version
win7/chrome74

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/pen/?&editable=true

### Steps to reproduce
click the select

### What is Expected?
正常的弹出动画

### What is actually happening?
这个是我在开发时发现的，包括官网也能复现；

表现：下拉框弹出时会反复跳动两次

[![GIF.gif](https://i.loli.net/2019/05/09/5cd3e7d0f1ded.gif)](https://i.loli.net/2019/05/09/5cd3e7d0f1ded.gif)

**Comment by ccy303** [comment] 2019-05-14 04:06
I know hao to deal it

**Comment by LebronLei** [comment] 2019-05-16 06:56
i have the same question

**Comment by yangyalu** [comment] 2019-05-22 08:24
I have the same question

**Comment by yangyalu** [comment] 2019-05-22 08:26
How to solve it?

**Comment by ChenErik** [comment] 2019-06-05 07:33
it's maybe chrome bug?

**Comment by island205** [comment] 2019-07-24 10:30
Duplicate of #15501

**Closed by island205** 2019-07-24 10:30 UTC
