### ISSUE TITLE
[Bug Report] win10 has its own browser select showing abnormal performance.

### ISSUE THREAD

**Issue by ElNinoT9** [ElemeFE/element#12488] opened 2018-08-24 04:01 UTC
### Element UI version
2.4.6

### OS/Browsers version
win10/自带浏览器

### Vue version
2.5.17

### Reproduction Link
[jsfiddle](jsfiddle)

### Steps to reproduce
点击select组件，进行选择，重复操作。

### What is Expected?
选中后正确显示，并能重复操作

### What is actually happening?
选中后，不定时会出现卡顿1~2秒现象，页面会自动刷新并跳到首页；element官网上会跳到刷新页面并跳到顶部。

**Comment by jikkai** [comment] 2018-08-24 04:07
Duplicate of #11629

**Closed by jikkai** 2018-08-24 04:07 UTC
