### ISSUE TITLE
the input component has bug in safari 

### ISSUE THREAD

**Issue by YuKaiChan** [ElemeFE/element#14744] opened 2019-03-18 08:01 UTC
### Element UI version
2.6.1

### OS/Browsers version
safari

### Vue version
2.6.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw](https://jsfiddle.net/mmx38qxw)

### Steps to reproduce

1、open the element ui website in safari.
2、find the input component，input the content，then edit the content not in the end.
3、the cursor will locate to the end when you put a character every time.

ps: the reproduction Link is not right that is why the above input cann't input  the element ui website. sorry !!!

### What is Expected?
the cursor wouldn't locate to the end when you put a character every time.

### What is actually happening?
 🤔️

**Comment by wacky6** [comment] 2019-03-18 12:10
duplicate of https://github.com/ElemeFE/element/issues/14540

**Closed by wacky6** 2019-03-18 12:10 UTC
