### ISSUE TITLE
[Bug Report] <el-dropdown> in <el-dialog> is shake when show

### ISSUE THREAD

**Issue by Senasiko** [ElemeFE/element#16401] opened 2019-07-04 07:15 UTC
### Element UI version
0.1.0

### OS/Browsers version
chrome 75.0.3770.100

### Vue version
2.6.10

### Reproduction Link
https://jsfiddle.net/b2q4v6uk/3/

### Steps to reproduce
鼠标放到【下拉菜单】

### What is Expected?
<el-dropdown-menu> enter 动画正常显示。

### What is actually happening?
<el-dropdown-menu> enter 动画会出现抖动。

**Comment by Senasiko** [comment] 2019-07-04 07:19
There is the gif
![dropdown](https://user-images.githubusercontent.com/14193002/60646724-a3033b80-9e6e-11e9-925f-871212d69d05.gif)

**Comment by island205** [comment] 2019-07-24 10:27
Duplicate of #15501

**Closed by island205** 2019-07-24 10:27 UTC
