### ISSUE TITLE
[Bug Report] el-select option label too long cause item text overflow box

### ISSUE THREAD

**Issue by sunchenguang** [ElemeFE/element#12418] opened 2018-08-20 02:32 UTC
### Element UI version
2.4.6

### OS/Browsers version
macOS 10.13.6 chrome68

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/5042/](https://jsfiddle.net/mmx38qxw/5042/)

### Steps to reproduce
it's easy to find this bug. or you use allow-create property, you create a long text option, then select it, you will see.
when el-select is multiple mode, and some option label is very long, you select it, then you can find it's text is overflow the box。
is there someway to make it change line

### What is Expected?
do not overflow box. item change line or text ellipsis

### What is actually happening?
overflow box

**Comment by ziyoung** [comment] 2018-08-20 02:49
Duplicate of #9352

**Closed by ziyoung** 2018-08-20 02:49 UTC

**Comment by wuyaoxing** [comment] 2018-08-23 09:28
我也遇到类似的问题。相关issues提供的解决方法是给 `.el-select` 设置一个固定宽，但是我需要select组件是自适应的。我使用的是 `Table` 嵌套 `Select` 组件，将 `popper-append-to-body` 属性设为 false 时存在不能显示问题。

**Comment by luanki** [comment] 2019-12-02 08:53
不知道这个能不能解决你们的问题：设置 `.el-select-dropdown` 的 `max-width` 属性为一个较小的值，因为组件会自动设置 `min-width` ;由于我们设置的`max-length`比较小，当 `max-width` 小于 `min-width` 时奇妙的现象就出现了https://jsfiddle.net/4u6b9tye/13/

**Comment by Lynnze-24** [comment] 2021-11-11 04:25
This will fix everything for you. Copy and paste  these styles in your css file. Cheers!

.el-select > .el-input {
  border: 0.1px solid #bfbfbf;
  border-radius: 3px;
  overflow: hidden;
}
.el-select > .el-input:hover {
  border-color: #595959;
}

.el-select > .el-input:active,
.el-select > .el-input:focus-within {
  border-color: #409eff;
}

.el-input__suffix {
  background-color: white;
  width: 40px;
  right: 0;
}
.el-input--medium .el-input__inner {
  width: 600px;  //should be bigger than your text
  border: none !important;
}
