### ISSUE TITLE
[Bug Report] DatePicker. disabledDate() checks each day from 2010.1.1, very low efficient 

### ISSUE THREAD

**Issue by qiulang** [ElemeFE/element#9423] opened 2018-01-23 09:33 UTC
### Element UI version
2.0.11

### OS/Browsers version
macOS/Chrome

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Just print out the time value in disabledDate() function call

disabledDate: time => { 
          console.log(time)
          return time.getTime() < ...
  }

### What is Expected?
Although it is not easy to implement an efficient disabledDate algorithm, there are  ways to improve the current implementation, e.g. only need to check each New Year's Day first to reduce check range

### What is actually happening?
check every day from 2010.1.1

**Comment by wacky6** [comment] 2018-01-23 10:30
duplicate of https://github.com/ElemeFE/element/issues/8763

**Closed** 2018-01-24 03:19 UTC
Labels: component: date-picker
