### ISSUE TITLE
[Feature Request] need table VirtualScrollView

### ISSUE THREAD

**Issue by lightning0016** [ElemeFE/element#11585] opened 2018-06-12 07:38 UTC
### Existing Component
否

### Component Name
 VirtualScrollView

### Description
1. no Pagination use
2.scoll bar is all data height
3 when scroll some position,loading from remote

**Comment by Leopoldthecoder** [comment] 2018-06-12 08:01
Duplicate of #9761

**Closed by Leopoldthecoder** 2018-06-12 08:01 UTC
