### ISSUE TITLE
[Bug Report] el-autocomplete cannot execute the focus event. It may be that the document does not specify, is it?

### ISSUE THREAD

**Issue by yemadu** [ElemeFE/element#5536] opened 2017-06-23 09:51 UTC
### Element UI version
1.3.7

### OS/Browsers version
Chrome

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/obyrvesg/1/](https://jsfiddle.net/obyrvesg/1/)

### Steps to reproduce
```focus``` 能够重现 

https://jsfiddle.net/obyrvesg/1/

### What is Expected?
el-autocomplete 中能够 focus 事件, 

### What is actually happening?
el-autocomplete 中不能够 focus 事件,

**Comment by Leopoldthecoder** [comment] 2017-06-23 09:58
Duplicate of #2544. We'll fix this in the next major version.

**Closed by Leopoldthecoder** 2017-06-23 09:58 UTC
