### ISSUE TITLE
[Feature Request] Consider adding an HTML editor component

### ISSUE THREAD

**Issue by jesse51076008** [ElemeFE/element#13291] opened 2018-11-04 03:08 UTC
### Existing Component
否

### Component Name
Editor

### Description
Consider adding an HTML editor component

**Comment by csvwolf** [comment] 2018-11-05 07:03
Can you give us a reason why you need this?

Otherwise we won't add this.

Emmm, and by  the way, I don't agree to add the component since there is lots of mature projects like: [CodeMirror](https://codemirror.net/) or [monaco](https://github.com/Microsoft/monaco-editor)

**Comment by ziyoung** [comment] 2018-11-05 09:44
Duplicate of #11841

**Closed by ziyoung** 2018-11-05 09:44 UTC
