### ISSUE TITLE
[Bug Report] el-select doesn't work with vue 2.2.6 correctly

### ISSUE THREAD

**Issue by zzzgit** [ElemeFE/element#4499] opened 2017-04-27 10:01 UTC
### Element UI version
1.2.9

### OS/Browsers version
all 

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/3e9gdeyc/](https://jsfiddle.net/3e9gdeyc/)

### Steps to reproduce
1.try to select an option
2.you can't select it successfully

### What is Expected?
nothing

### What is actually happening?
element is not compatible with vue 2.2.6 which is released on April 27 13:00

**Comment by zzzgit** [comment] 2017-04-27 10:02
![image](https://cloud.githubusercontent.com/assets/1060733/25478451/aef2a0ea-2b73-11e7-8c79-4c1ba5ff0b33.png)

**Comment by Leopoldthecoder** [comment] 2017-04-27 13:32
Duplicate of #4498

**Closed by Leopoldthecoder** 2017-04-27 13:32 UTC
