### ISSUE TITLE
[Bug Report] There are problems in the number check in the form

### ISSUE THREAD

**Issue by miaoihan** [ElemeFE/element#11733] opened 2018-06-24 08:50 UTC
### Element UI version
2.4.1

### OS/Browsers version
mac os

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/ST_Lighter/zoj971xj/1/](https://jsfiddle.net/ST_Lighter/zoj971xj/1/)

### Steps to reproduce
When you input the value like '123abc', The 'v-model.number' will not work in the inputfield. And I find the v-model value and input value are not synchronized.

### What is Expected?
I expected the bug can be fixed 

### What is actually happening?
hope it

**Comment by jikkai** [comment] 2018-06-24 11:12
Duplicate of #7945

**Closed by jikkai** 2018-06-24 11:12 UTC
