### ISSUE TITLE
When [Bug Report] table height = 100%, table data is loaded asynchronously and the total rows cannot be displayed

### ISSUE THREAD

**Issue by xuefei007** [ElemeFE/element#17188] opened 2019-08-27 08:57 UTC
### Element UI version
2.11.0

### OS/Browsers version
macOS 10.14.3 (18D42) /Google Chrome 76.0.3809.100

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/xuefei007/pen/MWgmwOW

### Steps to reproduce
表格 height=100%
show-summary=true
表格 data异步请求
详见重现链接

### What is Expected?
表格数据异步请求，合计行能正常显示

### What is actually happening?
表格数据异步请求，合计行不能正常显示

**Comment by ziyoung** [comment] 2019-09-06 07:20
Duplicate of #16602

**Closed by ziyoung** 2019-09-06 07:20 UTC
