### ISSUE TITLE
Want to add SelectTree components

### ISSUE THREAD

**Issue by mengxianghan** [ElemeFE/element#16763] opened 2019-07-26 09:27 UTC
### Existing Component
否

### Component Name
SelectTree

### Description
Some businesses require data in the form that chooses tree structures, such as menus.

**Comment by yangyangzuo** [comment] 2019-07-26 15:13
good questions,i need it to.

**Comment by ziyoung** [comment] 2019-07-31 07:28
Duplicate of #11795

**Closed by ziyoung** 2019-07-31 07:29 UTC
