### ISSUE TITLE
[Bug Report] tree bug when set data as empty array

### ISSUE THREAD

**Issue by xyhxyw** [ElemeFE/element#8236] opened 2017-11-14 02:31 UTC
### Element UI version
2.0.4

### OS/Browsers version
windows server2008 r2 /Chrome61

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/xyhxyw/za7aww4v/](https://jsfiddle.net/xyhxyw/za7aww4v/)

### Steps to reproduce
1 set the tree props data as an empty array,like [],
2 open chrome devTool,check then console dashboard,you'll find out the error msg.
'Error in mounted hook: "TypeError: Cannot read property 'setAttribute' of undefined" found in ElTree

### What is Expected?
no errors

### What is actually happening?
errors happen

**Comment by Leopoldthecoder** [comment] 2017-11-14 03:36
Duplicate of #8209

**Closed by Leopoldthecoder** 2017-11-14 03:36 UTC
