### ISSUE TITLE
The width of the [Bug Report] Select box is less than 110px, and the arrows in the drop-down list are not all displayed in the drop-down box

### ISSUE THREAD

**Issue by leeyinglee** [ElemeFE/element#8714] opened 2017-12-07 07:34 UTC
### Element UI version
2.0.7

### OS/Browsers version
MAC chrome 62

### Vue version
2.5.7

### Reproduction Link
[https://jsfiddle.net/sct67bk3/](https://jsfiddle.net/sct67bk3/)

### Steps to reproduce
https://jsfiddle.net/sct67bk3/

### What is Expected?
箭头完全显示在下拉框内

### What is actually happening?
箭头并非完全显示在下拉框内

**Comment by Leopoldthecoder** [comment] 2017-12-10 08:37
Duplicate of #8644

**Closed by Leopoldthecoder** 2017-12-10 08:37 UTC
