### ISSUE TITLE
[Bug Report] IE Edge Sogou input method, in the input component, under certain circumstances, can not input Chinese

### ISSUE THREAD

**Issue by zhujz** [ElemeFE/element#6471] opened 2017-08-14 08:49 UTC
### Element UI version
1.4.2

### OS/Browsers version
windows 10 IE Edge

### Vue version
2.4.2

### Reproduction Link
![image](https://user-images.githubusercontent.com/11346779/29264602-577f022a-8110-11e7-83df-12e89a16105e.png)
不用去jsfiddle，体验官方示例即可
http://element.eleme.io/#/zh-CN/component/input
[https://jsfiddle.net/tptumz26/](https://jsfiddle.net/tptumz26/)

### Steps to reproduce
需要windows 10 IE Edge浏览器 搜狗输入法
http://element.eleme.io/#/zh-CN/component/input
带输入建议->输入后匹配输入建议（右侧示例）

### What is Expected?
可以任意输入中文

### What is actually happening?
特定情况下不能输入中文

**Comment by Leopoldthecoder** [comment] 2017-08-15 02:28
Duplicate of #5813

**Closed by Leopoldthecoder** 2017-08-15 02:28 UTC
