### ISSUE TITLE
[Bug Report] default-time attribute only works with date range picker, not date picker

### ISSUE THREAD

**Issue by dak** [ElemeFE/element#10078] opened 2018-03-08 14:56 UTC
### Element UI version
2.2.1

### OS/Browsers version
All browsers

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/535/](https://jsfiddle.net/mmx38qxw/535/)

### Steps to reproduce
1. Create a datetime picker with the default-time attribute
2. Choose a date
3. The time will be set by default to the current time, rather than the default-time

### What is Expected?
The default-time attribute should work with datetime picker the same way it works with datetimerange picker. When selecting a date, the time should be set to the value defined by the default-time attribute.

### What is actually happening?
The time is being set by default to the current time on the datetime picker.

**Comment by Leopoldthecoder** [comment] 2018-03-15 04:27
This not a bug. `default-time` only works in range mode.

@wacky6 Do you think we can get it to work in non-range mode?

**Comment by wacky6** [comment] 2018-03-15 06:36
Sounds ok to me. Should not be a huge problem.

I'd say PR welcome for this issue. I'm too busy recently to implement this myself.

**Comment by Leopoldthecoder** [comment] 2018-03-15 06:52
@wacky6 Got it.

**Comment by gnijuohz** [comment] 2018-03-21 04:54
@Leopoldthecoder I would like to work on this issue if no one is currently working on it :)

**Comment by wacky6** [comment] 2018-03-21 05:10
@gnijuohz Thanks for contribution. Just remember to write tests and update the documentation.

**Comment by Leopoldthecoder** [comment] 2018-04-02 03:59
Resolved in https://github.com/ElemeFE/element/pull/10321 .

**Closed by Leopoldthecoder** 2018-04-02 03:59 UTC
Labels: component: date-picker, component: datetime-picker, good first issue, type: enhancement
