### ISSUE TITLE
[Bug Report] el-input - cursor goes to the end of the text

### ISSUE THREAD

**Issue by samjo-lendit** [ElemeFE/element#10611] opened 2018-04-09 02:40 UTC
### Element UI version
2.3.3

### OS/Browsers version
macOS 10.13.3 / Chrome 65.0.3325.181

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/samjo/eywraw8t/23427/](https://jsfiddle.net/samjo/eywraw8t/23427/)

### Steps to reproduce
1. Input some **Korean** text in the el-input (ex: 한글)
2. Try to add **Korean** text between the text (ex: try to input 고양이 between 한글)

Note that copy and pasting cannot reproduce this bug - you need to type by yourself!

### What is Expected?
한고양이글 (고양이 successfully added between 한 and 글)

### What is actually happening?
한고글양이 (cursor goes to the end of the text after the first letter (고) was added)

**Comment by douxc** [comment] 2018-04-09 03:02
i tried but everything seems ok(English & Chinese)

**Comment by samjo-lendit** [comment] 2018-04-09 04:32
@douxc Then I thinks that this problem only happens in Korean...

**Comment by Leopoldthecoder** [comment] 2018-04-09 04:37
Can you reproduce this in https://jsfiddle.net/leopoldthecuber/eywraw8t/23569/ and https://jsfiddle.net/leopoldthecuber/eywraw8t/23570/ respectively?

**Comment by samjo-lendit** [comment] 2018-04-09 06:36
@Leopoldthecoder Nope, I cannot reproduce this bug in both of them.

**Comment by Leopoldthecoder** [comment] 2018-04-09 07:01
I've verified this bug does exist.

Since the team has zero experience dealing with Korean IME, we may need the Korean community's help.

**Comment by xuzaixian** [comment] 2018-04-10 09:30
There is one more bug with Korean.
Type ‘dkd’ on Korean keyboard so that the resulting character be ‘앙’.Without focus move, type ‘k’ so that the resulting word shoud be ‘아아’.
But the last character will be missing. The Input element will show '아'.
After all this, press Space Button or Right Arrow Button,the missing character '아' will show.

And then ,I found out maybe it's not a good idea to not fire input event during composition when typing  Korean ? (Maybe this bug will come out again when tyeping Japanese)

I found out that if i call handleInput function everytime in handleComposition function can fix this ;)

**Comment by Leopoldthecoder** [comment] 2018-04-15 07:58
Fixed in https://github.com/ElemeFE/element/pull/10648

**Closed by Leopoldthecoder** 2018-04-15 07:58 UTC
Labels: component: input, status: help wanted

**Comment by wacky6** [comment] 2018-04-15 15:07
I tried macOS's "2-Set Korean" on element 2.3.3, the input seems fine. macOS's Hiragana and Chinese Pinyin are both fine. Tested on Chrome 65, macOS 10.13.4.

Could this be a problem of a particular IME, instead of an element problem?

![qq20180416-010628](https://user-images.githubusercontent.com/9319556/38779919-7490304c-4112-11e8-8b95-d15bc3d2fadf.gif)

@Leopoldthecoder I suggest further investigation.

**Comment by jlfenaux** [comment] 2019-03-15 17:42
I have the same issue (cursor moving to the end of line on each keystroke) in the latest version of element-ui 2.6.1. 
![Enregistrement de l’écran 2019-03-15 à 18 37 48](https://user-images.githubusercontent.com/22522/54451000-16632f00-4752-11e9-99f4-8eabbf29bf89.gif)

**Comment by franciscolourenco** [comment] 2019-03-21 14:53
2.6.3 is still affected

**Comment by jhlee8804** [comment] 2019-04-18 06:06
+1

**Comment by mikemand** [comment] 2020-01-18 04:46
This is still a problem in 2.13. Does anyone have a fix?
