### ISSUE TITLE
[Bug Report] Input type password not hiding password

### ISSUE THREAD

**Issue by ainzz** [ElemeFE/element#10419] opened 2018-03-28 11:03 UTC
### Element UI version
2.3.0

### OS/Browsers version
Ubuntu 14.04 / Chrome 65.0.3325.162

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/L9pc7zmd/](https://jsfiddle.net/L9pc7zmd/)

### Steps to reproduce
Enter any text in the password field.

### What is Expected?
Display asterisks instead of plain text.

### What is actually happening?
Plain text is displayed. The type attribute is not set.

**Comment by Leopoldthecoder** [comment] 2018-03-28 11:05
Duplicate of #10407 . Will release a patch soon.

**Closed by Leopoldthecoder** 2018-03-28 11:05 UTC
