### ISSUE TITLE
[Feature Request] El-Table when there's a large amount of data need to display, the scrolling performance is getting unsatisfactory

### ISSUE THREAD

**Issue by CalvinVon** [ElemeFE/element#12626] opened 2018-09-05 06:53 UTC
### Existing Component
是

### Component Name
el-table

### Description
El-Table: when there's large amount of data need to display, the scrolling performance is getting unsatisfactory.
So, it is recommended that VIRTUAL scroll can be built in to improve this situation.

**Comment by ziyoung** [comment] 2018-09-07 02:48
Duplicate of #6089

**Closed by ziyoung** 2018-09-07 02:48 UTC
