### ISSUE TITLE
[Feature Request]  How about tree component supports dblclick on node?

### ISSUE THREAD

**Issue by Glenfiddish** [ElemeFE/element#11803] opened 2018-06-29 08:33 UTC
### Existing Component
Yes

### Component Name
Tree

### Description
Add dblclick event

**Comment by jikkai** [comment] 2018-06-29 08:59
Duplicate of #6679

**Closed by jikkai** 2018-06-29 08:59 UTC

**Comment by Leopoldthecoder** [comment] 2018-06-29 09:19
Actually you can use `scoped slot` to add whatever event listeners you need.
