### ISSUE TITLE
[Bug Report] uses the tab key, and the cursor focus can penetrate into the interface below the dialog, and whether the tab key can only control the focus of the current dialog

### ISSUE THREAD

**Issue by hearain** [ElemeFE/element#8694] opened 2017-12-06 06:14 UTC
### Element UI version
1.4.12

### OS/Browsers version
windows 10 / chrome 61.0.3163.100

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/dhddhsnk/](https://jsfiddle.net/dhddhsnk/)

### Steps to reproduce
点击dialog，然后多次按下tab键，焦点会从dialog上跑到dialog外的元件上

### What is Expected?
在dialog中，多次按下tab，焦点只在该dialog中循环

### What is actually happening?
在dialog中，多次按下tab，焦点在整个页面元素中循环

**Comment by Leopoldthecoder** [comment] 2018-02-20 07:42
Duplicate of #5838

**Closed by Leopoldthecoder** 2018-02-20 07:42 UTC
