### ISSUE TITLE
[Bug Report] Table's data set contains a collection of child fields, which can cause errors that cannot be compiled

### ISSUE THREAD

**Issue by 2yllll** [ElemeFE/element#15009] opened 2019-04-08 09:28 UTC
### Element UI version
2.6.3

### OS/Browsers version
win 10  chrome73

### Vue version
2.6.10

### Reproduction Link
[https://codepen.io/anon/pen/zXKeYQ?editors=1111](https://codepen.io/anon/pen/zXKeYQ?editors=1111)

### Steps to reproduce
使用table组件的时候，不使用reserve-selection 功能与显示树形数据时，拉取的数据集中的Object带有children字段，并且是一个集合，这时候会报 ** 'if there's nested data, rowKey is required.'** 错误，无法通过编译

### What is Expected?
顺利通过编译，不会报错

### What is actually happening?
无法通过编译  提示 ** 'if there's nested data, rowKey is required.'**  错误

**Comment by 2yllll** [comment] 2019-04-11 11:21
![image](https://user-images.githubusercontent.com/9345667/55953475-c8791280-5c8e-11e9-880d-5c297596c73b.png)
![image](https://user-images.githubusercontent.com/9345667/55953502-de86d300-5c8e-11e9-8f96-2cf1a9b628b7.png)
When using remote and filterable, the suffix icon is empty.

**Comment by ziyoung** [comment] 2019-05-07 07:26
Duplicate of #15170

**Closed by ziyoung** 2019-05-07 07:26 UTC
