### ISSUE TITLE
[Bug Report] unexpected horizontal scroll bar due to <el-row> and <el-col>

### ISSUE THREAD

**Issue by YuyangGong** [ElemeFE/element#8881] opened 2017-12-18 14:45 UTC
### Element UI version
2.0.8

### OS/Browsers version
win7(32bit) / chrome62

### Vue version
2.5.2

### Reproduction Link
[https://codepen.io/YuyangGong/pen/NXxYKe](https://codepen.io/YuyangGong/pen/NXxYKe)

### Steps to reproduce
1. use \<el-row\> and \<el-col\> (使用\<el-row\>和\<el-col\>组件)
2. set gutter in \<el-row\> (在\<el-row\>中设置了gutter)
3. induce the unexpected horizontal scroll bar, the extra horizontal distance is in direct proportion to the size of gutter (导致了预期以外的横向滚动条, 其额外的横向距离与我所设置的gutter成正比)
4. you can preview this issue in the [demo](https://codepen.io/YuyangGong/pen/NXxYKe)  (可以在这个网站浏览问题的demo)

### What is Expected?
extra horizontal scroll bar not appear when I set gutter to \<el-row\>.  (当我使用\<el-row\>，并给其设置gutter的时候不再出现横向滚动条)

### What is actually happening?
unexpected horizontal scroll bar appear indeed

**Comment by Leopoldthecoder** [comment] 2018-02-04 07:29
Duplicate of #8573

**Closed by Leopoldthecoder** 2018-02-04 07:29 UTC
Labels: component: col
