### ISSUE TITLE
[Bug Report] table highlight-current-row attribute invalid invalid example in official website.

### ISSUE THREAD

**Issue by yiling-e0** [ElemeFE/element#11671] opened 2018-06-19 14:18 UTC
### Element UI version
2.4.1

### OS/Browsers version
mac

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
点击行  会高亮   

### What is Expected?
设置highlight-current-row false  后 不高亮当前行

### What is actually happening?
默认为false  重新设置了highlight-current-row false   依然无效

**Comment by jikkai** [comment] 2018-06-20 03:15
Duplicate of #11560

**Closed by jikkai** 2018-06-20 03:15 UTC
Labels: component: table, type: bug
