### ISSUE TITLE
[Bug Report] el-popover is copied in the fixed column of el-table.

### ISSUE THREAD

**Issue by skiller008** [ElemeFE/element#10984] opened 2018-05-03 06:30 UTC
### Element UI version
2.3.7

### OS/Browsers version
IE/Chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[http://jsfiddle.net/xv88jn83/](http://jsfiddle.net/xv88jn83/)

### Steps to reproduce
1.点击表格操作列中的“删除”按钮，弹出el-popover提示
2.拖动横向滚动条即可见

### What is Expected?
只出现一个el-popover提示

### What is actually happening?
出现了两个el-popover提示

**Comment by Leopoldthecoder** [comment] 2018-05-03 08:01
Duplicate of https://github.com/ElemeFE/element/issues/10588

**Closed by Leopoldthecoder** 2018-05-03 08:01 UTC
