### ISSUE TITLE
[Bug Report] Grouping table head CAN'T CLOSE

### ISSUE THREAD

**Issue by KaKarenLin** [ElemeFE/element#9129] opened 2018-01-04 10:10 UTC
### Element UI version
2.0.10

### OS/Browsers version
windows/chrome 63.0.3239.84

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/suL178sv/1/](https://jsfiddle.net/suL178sv/1/)

### Steps to reproduce
1. just open 'https://jsfiddle.net/suL178sv/1/' and check
2. when you use el-table-column in Multi-level, it could not actually close

### What is Expected?
null

### What is actually happening?
when you use el-table-column in Multi-level, it could not actually close

**Comment by Leopoldthecoder** [comment] 2018-01-05 06:50
Duplicate of #9042

**Closed by Leopoldthecoder** 2018-01-05 06:50 UTC
