### ISSUE TITLE
When the [Bug Report] table data is empty, the mouse slides to the blank form, and the console starts to report wrong.

### ISSUE THREAD

**Issue by LuckyTaoTao** [ElemeFE/element#11174] opened 2018-05-15 10:48 UTC
### Element UI version
2.3.8

### OS/Browsers version
window10 

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/j85myqww/](https://jsfiddle.net/j85myqww/)

### Steps to reproduce
后台返回的某个字段为空时，页面渲染完成以后，鼠标滑动到表格为空上方，控制台开始报错
 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
    at VueComponent.handleCellMouseEnter

### What is Expected?
修复此bug

### What is actually happening?
尽快修复此bug

**Comment by Leopoldthecoder** [comment] 2018-05-15 10:52
Duplicate of #11171

**Closed by Leopoldthecoder** 2018-05-15 10:52 UTC
