### ISSUE TITLE
[Bug Report] el-pagination meet a critical bug

### ISSUE THREAD

**Issue by acerDebugman** [ElemeFE/element#7458] opened 2017-10-12 12:32 UTC
### Element UI version
2.0.0-alpha.2

### OS/Browsers version
chrome Version 59.0.3071.104 (Official Build) (64-bit)

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
just use it, then it happened

### What is Expected?
I just want it work properly

### What is actually happening?

webpack-internal:///1:477 [Vue warn]: Injection "elFormItem" not found

found in

---> <ElInput>
       <ElSelect>
         <Sizes>
           <ElPagination>
             <ElCol>... (1 recursive calls)
               <Brand> at src/views/brand/brand.vue
                 <ElContainer>
                   <Home> at src/components/layout/Home.vue
                     <App> at src/App.vue
                       <Root>

**Comment by Leopoldthecoder** [comment] 2017-10-13 02:42
Duplicate of #7324

**Closed by Leopoldthecoder** 2017-10-13 02:42 UTC
