### ISSUE TITLE
[Bug Report] ie9下，input输入框，后退按键监控忽略，input在ie9下完全没法用！！！！！！！

### ISSUE THREAD

**Issue by suzi404** [ElemeFE/element#4180] opened 2017-04-13 08:30 UTC
### Element UI version
1.2.8

### OS/Browsers version
win7 ie9

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/](https://jsfiddle.net/pj71jkyw/)

### Steps to reproduce
ie9下，包裹在表单中时，如：`<el-form-item label="资产类型">
					    	<el-input class="assetType" v-model="form.assetType" ></el-input>
					  	</el-form-item>`
在用后退键删除input输入框的内容时，v-model的值不变化，也不触发input本身的change事件。

### What is Expected?
能正常删除

### What is actually happening?
删除功能无效

**Comment by lwfyiwei** [comment] 2017-04-17 07:51
IE9的BUG不处理了吗

**Comment by itdepartament** [comment] 2017-04-17 19:37
ie 11 have this problem, no ie 9

**Comment by baiyaaaaa** [comment] 2017-04-27 00:55
I can't not reproduct your problem, please provide an online demo.
Aso, el-from-item must use with el-form

**Comment by itdepartament** [comment] 2017-04-28 19:47
i can place demo problem in demo site. it`s ok?
===
do you know, that new version vue.js break element-select?
https://jsfiddle.net/api/post/library/pure/

not possible choose item from select, how fix it?
with previsios version vue work is correct

2017-04-27 3:55 GMT+03:00 baiyaaaaa <notifications@github.com>:

**Comment by itdepartament** [comment] 2017-04-28 20:28
http://1c8.online/


​
​

2017-04-28 22:47 GMT+03:00 1c <itdepartament@gmail.com>:

**Comment by Leopoldthecoder** [comment] 2017-04-30 11:19
I've tried in both IE11 and IE9, and cannot reproduce your problem. Closing this issue for lack of reproduction.

**Closed by Leopoldthecoder** 2017-04-30 11:19 UTC
Labels: need repro, windows

**Comment by itdepartament** [comment] 2017-05-01 07:02
ok

2017-04-30 14:19 GMT+03:00 杨奕 <notifications@github.com>:

**Comment by liangyj021** [comment] 2017-05-11 07:58
我是把Input.vue源码复制到项目中，添加了一个和@input一样的@change监听，就能监听删除键修改的内容了（IE9）。如下，不知道是什么原理。并不是一个好的办法。

<input
        v-if="type !== 'textarea'"
        class="el-input__inner"
        :type="type"
        :name="name"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        :maxlength="maxlength"
        :minlength="minlength"
        :autocomplete="autoComplete"
        :autofocus="autofocus"
        :min="min"
        :max="max"
        :step="step"
        :form="form"
        :value="currentValue"
        ref="input"
        @input="handleInput"
        **_@change="handleInput"_**
        @focus="handleFocus"
        @blur="handleBlur"
      >

**Comment by lambeter** [comment] 2018-06-20 09:21
今天也遇到了，请问怎么解决的
