### ISSUE TITLE
When the [Bug Report] table has a horizontal scroll bar and the column is fixed to the left, the total rows are not aligned

### ISSUE THREAD

**Issue by ystyle** [ElemeFE/element#6915] opened 2017-09-07 09:56 UTC
### Element UI version
1.4.4

### OS/Browsers version
windows10 /chrome 60.0.3112.113

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/556/](https://jsfiddle.net/pj71jkyw/556/)

### Steps to reproduce
- 固定列到左边
- 添加多个列到超出表格宽度
- 启用合计功能
> 这时可以看到合计行与固定列之间没有对齐

### What is Expected?
正确显示合计行

### What is actually happening?
合计行与固定列之间没有对齐
![](http://osloqpukl.bkt.clouddn.com/201717071746-n.png)

**Comment by Leopoldthecoder** [comment] 2017-09-07 13:00
Duplicate of #5415

**Closed by Leopoldthecoder** 2017-09-07 13:00 UTC
