### ISSUE TITLE
[Bug Report] Popover flashes when it appears from time to time and popover area disappears when click itself

### ISSUE THREAD

**Issue by HymanShi** [ElemeFE/element#8315] opened 2017-11-16 06:33 UTC
### Element UI version
2.0.4

### OS/Browsers version
chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/Lqh3d6w6/](https://jsfiddle.net/Lqh3d6w6/)

### Steps to reproduce
1.click the button.
2.click the popover area.

### What is Expected?
1.The popover area appears 
2.Click the popover area successfully and it will not disappear.

### What is actually happening?
1.The popover area flashed from time to time(or when first click the button)
2.when click the popover area ,the popover area disappears unexpectedly

**Comment by Leopoldthecoder** [comment] 2017-11-16 06:40
Duplicate of #8186

**Closed by Leopoldthecoder** 2017-11-16 06:40 UTC
