### ISSUE TITLE
[Bug Report] select and dropdown control clicks on lost animation or jump animation problem in chrome browers sometimes

### ISSUE THREAD

**Issue by LebronLei** [ElemeFE/element#15574] opened 2019-05-16 07:21 UTC
### Element UI version
2.4.4

### OS/Browsers version
windows 10

### Vue version
2.5.20

### Reproduction Link
https://codepen.io/lebronlei/pen/pmeKLX

### Steps to reproduce
Clicking the click or dropdown box occasionally causes a flashing problem

### What is Expected?
Fix this serious bug in chrome

### What is actually happening?
no jump animation

**Comment by claviska** [comment] 2019-05-22 15:53
Possible duplicate of #15501

**Comment by websanova** [comment] 2019-06-15 10:17
Yes, it's duplicate of my issue: https://github.com/ElemeFE/element/issues/15501

**Closed** 2019-07-08 09:37 UTC

**Comment by LebronLei** [comment] 2019-07-19 07:41
> Possible duplicate of #15501
Thank you , i get it.
