### ISSUE TITLE
[Bug Report] header dislocation

### ISSUE THREAD

**Issue by a346721573** [ElemeFE/element#5804] opened 2017-07-11 08:22 UTC
### Element UI version
1.3.7

### OS/Browsers version
chrome 59.0.3071.115

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/m4nL807z/](https://jsfiddle.net/m4nL807z/)

### Steps to reproduce
使用表格组件时出现多余横向纵向滚动条，拖动横向滚动条时，表头与内容错位
![image](https://user-images.githubusercontent.com/14291277/28059186-e53900be-6655-11e7-8a7b-b4ac947dbe7f.png)

### What is Expected?
如何去掉多余的滚动条，拖动横向表头时错位解决

### What is actually happening?
展示错误

**Comment by a346721573** [comment] 2017-07-11 08:33
Hi,I edit this issue again

**Comment by Leopoldthecoder** [comment] 2017-07-12 01:46
Duplicate of #5251

**Closed by Leopoldthecoder** 2017-07-12 01:46 UTC
