### ISSUE TITLE
[Bug Report] Fixed column rows no longer align well when the table is scrolled all the way to the bottom

### ISSUE THREAD

**Issue by smares** [ElemeFE/element#5648] opened 2017-06-30 11:31 UTC
### Element UI version
1.3.7

### OS/Browsers version
Ubuntu 17.04 / Firefox 54.0

### Vue version
2.3.4

### Reproduction Link
[https://jsfiddle.net/dv173xse/](https://jsfiddle.net/dv173xse/)

### Steps to reproduce
1. Visit https://jsfiddle.net/dv173xse/ using Firefox 54.0 under Ubuntu 17.04
2. Scroll the table all the way to the bottom

### What is Expected?
The fixed column rows should align with the rest of the rows when the table is scrolled all the way to the bottom

### What is actually happening?
The fixed column rows are misaligned (see https://pasteboard.co/kSMR13vo.png)

This problem does not occur with Chrome that uses non-styled scrollbars

**Comment by Leopoldthecoder** [comment] 2017-07-01 11:29
Duplicate of #3708

**Closed by Leopoldthecoder** 2017-07-01 11:29 UTC
