### ISSUE TITLE
[Bug Report] InputNumber when default value is 0, view not show the value

### ISSUE THREAD

**Issue by Braised-Cakes** [ElemeFE/element#10734] opened 2018-04-16 08:24 UTC
### Element UI version
2.3.4

### OS/Browsers version
mac10.12.6/ chrome 65

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/braisedcakes/mmx38qxw/1710/](https://jsfiddle.net/braisedcakes/mmx38qxw/1710/)

### Steps to reproduce
InputNumber when default value is 0, view not show the value

### What is Expected?
show 0

### What is actually happening?
show ''

**Comment by Leopoldthecoder** [comment] 2018-04-16 08:38
Duplicate of #10713

**Closed by Leopoldthecoder** 2018-04-16 08:38 UTC
