### ISSUE TITLE
After [Bug Report] select changes width, inverted triangle is dislocated

### ISSUE THREAD

**Issue by pz25925** [ElemeFE/element#8369] opened 2017-11-17 12:37 UTC
### Element UI version
2.0.5

### OS/Browsers version
window64 / chrome

### Vue version
2.5.4

### Reproduction Link
[https://jsfiddle.net/36uwtqr7/](https://jsfiddle.net/36uwtqr7/)

### Steps to reproduce
1. 更改 select 宽度
2. 展开 select

### What is Expected?
倒三角在合适的位置

### What is actually happening?
倒三角偏左

**Comment by Leopoldthecoder** [comment] 2017-11-19 08:32
Duplicate of #8210

**Closed by Leopoldthecoder** 2017-11-19 08:32 UTC
