### ISSUE TITLE
[Bug Report] Input value never set

### ISSUE THREAD

**Issue by sebastiaanluca** [ElemeFE/element#9820] opened 2018-02-15 02:25 UTC
### Element UI version
2.2.0

### OS/Browsers version
Chrome / any

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/278/](https://jsfiddle.net/mmx38qxw/278/)

### Steps to reproduce
Use any component that uses a form input internally.

### What is Expected?
The form input's `value` attribute is set when initialized, changed, or manually set.

### What is actually happening?
The form input `value` attribute is never set nor added. This makes using any such component in an actual (non-JS async submitted) form impossible.

An attempt at a workaround would be to wrap every Element UI component in another Vue component (which we're doing now), but not every element allows setting the value manually and it's very, very redundant. Could add a second hidden input field, but collides with some components as they do set values (date picker).

![screen shot 2018-02-15 at 03 20 59](https://user-images.githubusercontent.com/711940/36237919-70493f66-11ff-11e8-952b-63fb1269f25a.png)
<img width="1046" alt="screen shot 2018-02-15 at 03 16 26" src="https://user-images.githubusercontent.com/711940/36237921-73020e2c-11ff-11e8-937b-e45c6d0d69ad.png">

**Comment by sebastiaanluca** [comment] 2018-02-15 02:27
Somewhat related: a component cannot be used outside another custom wrapper Vue component? Like, just in my HTML view. I _have_to set the v-model? Doesn't seem to do anything otherwise.

**Comment by Leopoldthecoder** [comment] 2018-02-15 03:01
The `value` attribute of the native input element does update every time you type in the input box: https://jsfiddle.net/leopoldthecuber/mmx38qxw/286/

**Comment by sebastiaanluca** [comment] 2018-02-15 03:07
Is that a dynamic thing only? There is no input nor values when submitting that form and reading it out in the back-end with e.g. Laravel. Inspecting the component with Chrome dev tools doesn't show the value attribute either. And those are shown dynamically, so if it's not there, it's not really set IMO.

**Comment by Leopoldthecoder** [comment] 2018-02-15 03:10
> There is no input nor values when submitting that form and reading it out in the back-end with e.g. Laravel

You need to write a demo about this.

**Comment by wacky6** [comment] 2018-02-15 12:33
I'm not sure what you are trying to accomplish. Native input element's value is updated.

`v-model` and `value` should **not** be used together. In Vue, v-model is essentially a `:value`+`@input` syntax sugar.

See: https://jsfiddle.net/tk0rx6gu/

**Comment by sebastiaanluca** [comment] 2018-02-15 15:06
Simple example:

```html
<form method="POST" action="myurl">
    <el-input name="myinput" value="random value"></el-input>
    <input type="text" name="workinginput" value="123" />
</form>
```

Catch it in the back-end:

```php
<?php

var_dump($_POST);
```

`$_POST` variable does not contain `'myinput' => 'random value'` as one would expect. At the moment I'm not sure why it's not received. A non-element input field works fine, `workinginput` has a value of `123`.

Is there a simple way I can create a demo for this without having to set up and deploy a Laravel application? A PHP fiddle doesn't really allow me to set up a form post example.

**Comment by sebastiaanluca** [comment] 2018-02-15 15:27
Any reason why the input number component doesn't work on its own btw? Goes -1 and 1, that's all. That's what I also meant with the wrapping part. I have to create a custom parent Vue component that uses an Element component for it to work, which introduced the form value submit issue.

https://jsfiddle.net/tk0rx6gu/3/

**Comment by dymen1** [comment] 2018-02-15 20:16
When resetting a form, it should revert to the value attribute on the HTML input:
https://jsfiddle.net/mmx38qxw/300/
Currently this attribute isn't present on form inputs.

**What is Expected:**
A form input, that has a default value, is reset to it's default value on form reset.
**What is actually happening:**
A form input, that has a default value, is emptied on form reset.

This can be resolved by adding a value attribute with the default value to the HTML element.

If this should be in a separate issue, please let me know.

**Comment by wacky6** [comment] 2018-02-15 23:40
@sebastiaanluca just write a js fiddle with the form that posts to any URL. As long as the browser fires the request, we can inspect the form payload.

You must bind v-model to input-number. All element components are controlled by its value (stored in JS environment, not HTML/DOM).

**Comment by wacky6** [comment] 2018-02-15 23:42
@dymen1 You need to set the value in Vue way.
Just assign to component's bounded value with whatever you want.

Also read vue document's custom component section, which gives a pretty clear explanation about value / v-model mechanism.

**Comment by Leopoldthecoder** [comment] 2018-02-16 13:18
> The `value` of the el-input element remains empty when typing e.g. "20" in the input. Shouldn't this be updated? This is the default form value that needs to be set for it to work.

@sebastiaanluca First of all, the `value` of el-input is just a prop of that Vue component, it's not the `value` of the native `<input>` element which is sent with the form.

Secondly, the `value` of el-input does get updated as you type:
![untitled1](https://user-images.githubusercontent.com/10095631/36309224-be8acbee-135e-11e8-9936-fa05dbcfb2bd.gif)

**Comment by dymen1** [comment] 2018-02-16 15:38
@wacky6 you are right, this issue isn't caused by the element-ui code.
https://jsfiddle.net/vzns7us7/35/
Has the same issue and demonstrates that this is caused by Vue.

Thanks for this amazing UI library!

**Closed** 2018-02-24 12:00 UTC
Labels: component: input, need: repro
