### ISSUE TITLE
[Feature Request] Drag-n-drop trees?

### ISSUE THREAD

**Issue by lk-geimfari** [ElemeFE/element#6424] opened 2017-08-11 10:30 UTC
### Existing Component
Yes

### Component Name
drag-n-drop tree

### Description

It would be cool to be able to create drag-n-drop trees (with automatically node updates), like in example below:

![](https://raw.githubusercontent.com/shuiRong/vue-drag-tree/master/static/vue-drag-tree2.gif)

**Comment by Leopoldthecoder** [comment] 2017-08-13 03:10
Duplicate of #1940

**Closed by Leopoldthecoder** 2017-08-13 03:10 UTC

**Comment by lk-geimfari** [comment] 2017-08-13 09:23
@Leopoldthecoder Well, so what's your decision? In #1940 i don't find nothing about decision.
