### ISSUE TITLE
When [Bug Report] el-table-column is set show-overflow-tooltip, the tooltip cannot be displayed under ie at the literal length of more than 1-3 characters

### ISSUE THREAD

**Issue by zimplexing** [ElemeFE/element#6821] opened 2017-09-01 12:25 UTC
### Element UI version
1.4.3

### OS/Browsers version
win10 ie11

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/zimplexing/hLyacfzg/](https://jsfiddle.net/zimplexing/hLyacfzg/)

### Steps to reproduce
cell的宽度被设置为180px；文字的实际长度也为180px；这是会出现... ，但是在ie下，cell的scrollWidth和offsetWidth是相同的，无法显示tooltip。在chrome下scrollWidth是大于offsetWidth的

### What is Expected?
在ie下能正常显示

### What is actually happening?
在ie下无法显示tooltip

**Comment by Leopoldthecoder** [comment] 2017-09-02 12:32
Duplicate of #5049

**Closed by Leopoldthecoder** 2017-09-02 12:32 UTC
