### ISSUE TITLE
[bug report] empty data prompt set by cascade component does not take effect: slot = empty '

### ISSUE THREAD

**Issue by lmfuture** [ElemeFE/element#20613] opened 2020-12-25 03:27 UTC
### Element UI version
2.14.1

### OS/Browsers version
谷歌

### Vue version
2.6.12

### Reproduction Link
https://github.com/PanJiaChen/vue-element-admin

### Steps to reproduce
234234234

### What is Expected?
21312313

### What is actually happening?
13123123

**Comment by cs1707** [comment] 2021-01-04 12:22
Duplicate of #20612

**Closed by cs1707** 2021-01-04 12:22 UTC
