### ISSUE TITLE
[Bug Report] Table with fixed columns and summary row causes the scroll bar to not click

### ISSUE THREAD

**Issue by breezelives** [ElemeFE/element#13952] opened 2019-01-02 02:56 UTC
### Element UI version
2.4.11

### OS/Browsers version
wind7/chrome 71

### Vue version
2.5.21

### Reproduction Link
[https://codepen.io/Breezzle/pen/zypvEw](https://codepen.io/Breezzle/pen/zypvEw)

### Steps to reproduce
1.use the table component with fixed columns and summary row;
2.add multiple columns to show the horizontal scrollbar
3.click the scroll bar under the fixed columns

### What is Expected?
 the horizontal scrollbar is work

### What is actually happening?
the horizontal scrollbar is not work

**Comment by breezelives** [comment] 2019-01-02 02:58
![image](https://user-images.githubusercontent.com/7886661/50579144-4d2ce700-0e7d-11e9-9215-61bbbf33a2f8.png)

**Comment by ziyoung** [comment] 2019-02-18 07:35
Duplicate of #5415

**Closed by ziyoung** 2019-02-18 07:35 UTC
