### ISSUE TITLE
How to show/hide elements based on breakpoints?

### ISSUE THREAD

**Issue by dimirc** [ElemeFE/element#2902] opened 2017-02-19 08:11 UTC
For example if screen is "lg", we would like to show some extra info to the users since we know they'll have more space available. Is there any class to hide/show based on screen dimension?

**Comment by syn-zeta** [comment] 2017-04-20 00:24
Duplicate of #2732

**Comment by baiyaaaaa** [comment] 2017-05-11 15:23
now, el-col is support to set span to 0 and hide the col

**Closed by baiyaaaaa** 2017-05-11 15:23 UTC
