### ISSUE TITLE
[Bug Report] Set firstDayOfWeek to 1, but get a value of Tuesday;

### ISSUE THREAD

**Issue by MrZhouZh** [ElemeFE/element#11601] opened 2018-06-13 02:53 UTC
### Element UI version
2.0.10

### OS/Browsers version
chrome@latest

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/element/issues/11599](https://github.com/ElemeFE/element/issues/11599)

### Steps to reproduce
date-picker: {
    type: 'week',
    picker-option: {
       firstDayOfWeek: 1
    }
    v-model: 'weekTime'
}

@change: weekTime => 'Tuesday'

why Tuesday? Shouldn't it be Monday?

### What is Expected?
Solve this problem. and give me a explain, thanks!

### What is actually happening?
Set firstDayOfWeek to 1, but get a value of Tuesday;

**Comment by jikkai** [comment] 2018-06-13 03:13
Duplicate of #6754

**Closed by jikkai** 2018-06-13 03:13 UTC
