### ISSUE TITLE
[Bug Report]Blur is invalid in Select Events of Select component

### ISSUE THREAD

**Issue by JerrySir** [ElemeFE/element#15146] opened 2019-04-17 05:25 UTC
### Element UI version
2.7.0

### OS/Browsers version
macOS 10.14.4

### Vue version
2.5.17

### Reproduction Link
https://jsfiddle.net/mmx38qxw/

### Steps to reproduce
```
<template>
  <el-select
    v-model="tagSelectedValue"
    multiple
    filterable
    allow-create
    default-first-option
    @blur="handleBlur"
  >
    <el-option
      v-for="item in tagList"
      :key="item.value"
      :label="item.label"
      :value="item.value"/>
  </el-select>
</template>
```

### What is Expected?
移出input焦点时有回调

### What is actually happening?
移出input焦点时没有回调, 将@blur 改为visible-change 就有回调

**Comment by ziyoung** [comment] 2019-05-08 03:40
Duplicate of #14260

**Closed by ziyoung** 2019-05-08 03:40 UTC
