### ISSUE TITLE
[Bug Report] NavMenu selects the status disappear after switching the value of collapse.

### ISSUE THREAD

**Issue by fabin5** [ElemeFE/element#10971] opened 2018-05-02 12:56 UTC
### Element UI version
2.3.7

### OS/Browsers version
macOS/Chrome 65

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/fabin5/575o34eu/](https://jsfiddle.net/fabin5/575o34eu/)

### Steps to reproduce
1、点击“展开”按钮
2、菜单栏展开后点击“导航二”
3、点击“收起”按钮
4、再次点击“展开”按钮

### What is Expected?
导航二的高亮效果消失。

### What is actually happening?
导航二的高亮效果不消失。

**Comment by wacky6** [comment] 2018-05-02 13:10
Duplicate of https://github.com/ElemeFE/element/issues/10622

**Closed by wacky6** 2018-05-02 13:10 UTC

**Comment by qingwufengyang** [comment] 2018-05-14 08:56
请问怎么解决的
