### ISSUE TITLE
[Feature, Request], select, the, maximum, minimum, values, when, and, the, calendar, is,, set, to, type='daterange'support, settings.

### ISSUE THREAD

**Issue by proshuai** [ElemeFE/element#5954] opened 2017-07-20 02:55 UTC
### Existing Component
Yes

### Component Name
el-date-picker

### Description
like this:
<el-date-picker v-model="value1" type="daterange" align="right" placeholder="选择日期范围" format="yyyy/MM/dd"  minDate="ms" maxDate="ms数"></el-date-picker>

**Comment by Leopoldthecoder** [comment] 2017-07-20 03:07
Duplicate of #5953

**Closed by Leopoldthecoder** 2017-07-20 03:07 UTC
