### ISSUE TITLE
[Bug Report] select dropdown can't follow scroll in table scope

### ISSUE THREAD

**Issue by jinan5694** [ElemeFE/element#8278] opened 2017-11-15 02:45 UTC
### Element UI version
2.0.4

### OS/Browsers version
win8.1/chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/jinan5694/mr59p7df/4/](https://jsfiddle.net/jinan5694/mr59p7df/4/)

### Steps to reproduce
click selects show dropdown menu, scroll page

### What is Expected?
dropdown menu follow the scroll

### What is actually happening?
dropdown menu not follow the scroll when select in the table scope

**Comment by Leopoldthecoder** [comment] 2017-11-15 03:23
Duplicate of #7098

**Closed by Leopoldthecoder** 2017-11-15 03:23 UTC
