### ISSUE TITLE
[Bug Report] NavMenu components (side bar) click anywhere else on the page, and the sub menus will fold up.

### ISSUE THREAD

**Issue by tiasen** [ElemeFE/element#13475] opened 2018-11-20 01:52 UTC
### Element UI version
2.4.10

### OS/Browsers version
Chrome 版本 70.0.3538.67（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/v6e53tsb/](https://jsfiddle.net/v6e53tsb/)

### Steps to reproduce
1.点击展开菜单
2.在非菜单区域点击

### What is Expected?
除非路由变化或者手动折叠菜单，点击空白处不应该折叠菜单

### What is actually happening?
点击非菜单区域会折叠菜单

**Comment by ziyoung** [comment] 2018-11-20 03:31
Duplicate of #13452

**Closed by ziyoung** 2018-11-20 03:31 UTC
