### ISSUE TITLE
[Bug Report] will have a flicker screen when the tab is first clicked when the tab is under the table.

### ISSUE THREAD

**Issue by athena0304** [ElemeFE/element#9185] opened 2018-01-09 04:40 UTC
### Element UI version
2.0.11

### OS/Browsers version
macos 10.12.6 / chrome 63.0.3239.132

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/athena0304/ztey5L41/1/](https://jsfiddle.net/athena0304/ztey5L41/1/)

### Steps to reproduce
第一次点击未显示的tab的内容时，会有闪屏现象
当都点开过以后，再次点击就好了

### What is Expected?
第一次点击也不会出现闪动的效果

### What is actually happening?
第一次点击会出现闪屏效果

**Comment by Leopoldthecoder** [comment] 2018-01-09 08:00
Duplicate of #9008

**Closed by Leopoldthecoder** 2018-01-09 08:00 UTC
