### ISSUE TITLE
[Bug Report] el-switch's V-model is incorrect when it is introduced into int type.

### ISSUE THREAD

**Issue by linxiaojialin** [ElemeFE/element#11698] opened 2018-06-21 04:00 UTC
### Element UI version
2.4.1

### OS/Browsers version
win10 / Chrome 66.0.3359.117

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/esn7rfo3/3/](https://jsfiddle.net/esn7rfo3/3/)

### Steps to reproduce
1.将左下栏目的js代码增加
    mounted() {
      let val = 100;
      this.value5 = val;
    }

即，整体修改为
var Main = {
    data() {
      return {
        value5: '100'
      }
    },
    mounted() {
      let val = 100;
      this.value5 = val;
    }
  };
var Ctor = Vue.extend(Main)
new Ctor().$mount('#app')
2.点击左上角运行，发现右侧switch按钮为关闭

3.将 let val = 100; 改为 let val = ‘100’; 
4.点击左上角运行，发现右侧switch按钮为开启

### What is Expected?
无论v-model的值为 '100' 或 100 ，只要值等于el-switch的active-value，switch按钮为开启

### What is actually happening?
左上栏目的html代码中，无论el-switch标签的active-value属性为 active-value="100" 或 active-value=100 ，当value5为 '100'(string) 时皆为开启，当value5 为 100(int) 时皆为关闭。
故，应是对v-model的值为int时判断有误吧

**Comment by jikkai** [comment] 2018-06-21 04:07
Duplicate of #11381

**Closed by jikkai** 2018-06-21 04:07 UTC
