### ISSUE TITLE
[Feature Request] Lazy Repeat on lists and tables

### ISSUE THREAD

**Issue by fergardi** [ElemeFE/element#10036] opened 2018-03-06 15:20 UTC
### Existing Component
No

### Component Name
ElVirtualList

### Description
If there are so much rows in a table or li in a list, the performance of the framework suffers a lot. This is due to VueJS DOM rendering behaviour, but some other frameworks offer solutions in different ways. This is NOT an infinite scroll component, which already exists. This component only renders a subset of elements, no matter how big is the original set. When the user scrolls down, it load and renders more items, but removes some of the previous one, the final number remainig the same. And when he scrolls ups, the other way around.

Added links for demonstration purposes:

https://onsen.io/v2/api/angular1/ons-lazy-repeat.html

https://codepen.io/onsen/pen/EaQKrK

https://framework7.io/docs/virtual-list.html

This could be very useful in large (hundreds or thousands) datasets. It would be a perfect addition to the existing ElTable.

Thank you in advance.

**Comment by Leopoldthecoder** [comment] 2018-03-07 05:19
Duplicate of #9761

**Closed by Leopoldthecoder** 2018-03-07 05:19 UTC
