### ISSUE TITLE
[Bug Report] modify the value of el-select does not trigger validation

### ISSUE THREAD

**Issue by changexbc** [ElemeFE/element#11548] opened 2018-06-08 12:11 UTC
### Element UI version
2.4.0

### OS/Browsers version
macOS / Chrome 67.0.3396.62

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/64wjqbLc/5/](https://jsfiddle.net/64wjqbLc/5/)

### Steps to reproduce
首先点击「校验」按钮触发form的validate方法，如果此时表单数据如果为空，会显示请选择和请填写的提示。
然后点击「设置为浙江」按钮修改表单中el-select和el-input绑定的值，这时因为el-input因为值被修改所以再次触发了校验，因为符合校验规则所以错误提示消失了，但是el-select却没有触发校验规则，如果此时在点击「校验」按钮则再次触发表单所有校验el-select的错误提示也消失。

### What is Expected?
因为在实际开发中经常会有动态修改el-select值的情况，所以希望el-select 也可以像 el-input一样在动态修改的时候可以触发校验。

### What is actually happening?
el-select 在动态修改的时候没有触发校验。

**Comment by atilkan** [comment] 2018-06-08 21:30
This is not a bug. But can be a feature request for a public method. 
I am guessing; when you clear the select value it doesn't know if the value changed. Because it is value-key pair. I made a few update to your [example](https://jsfiddle.net/64wjqbLc/6/). If you make it clearable and clear it, it works. I think **clear** method should be exposed.

**Comment by Leopoldthecoder** [comment] 2018-06-10 12:35
This indeed is something we should work on. We definitely don't want this kind of inconsistent behavior.

**Comment by changexbc** [comment] 2018-06-11 03:29
@atilkan looks like it doesn't work for me.
And I don't just need to check the form when it is empty, but I need to check the form every time I modify the form item.

**Comment by wacky6** [comment] 2018-06-13 14:55
Well. Currently, form validation change event is the same as 'change' event.

If we ignore complicated cases (for example, using multi), this issue can be addressed by emitting validation change event whenever the value changes. (That's basically what el-input is doing).

**Comment by changexbc** [comment] 2018-06-14 07:19
I hope that each time the value of the modification can trigger validation, because this is very useful in complex forms, if you need to manually trigger form validation every time, that would be very difficult in projects with complex forms, I hope Even if you really want to remove the auto-verification, at least provide a switch to let me turn on auto-calibration, because this function is really very important in actual use.

**Comment by wacky6** [comment] 2018-06-14 07:55
I will look into a fix soon. Most likely it will auto validate similarly to el-input.

**Closed** 2018-06-25 08:57 UTC
Labels: component: select, type: enhancement

**Comment by Lynn-cc** [comment] 2019-03-28 02:56
> I will look into a fix soon. Most likely it will auto validate similarly to el-input.

The 'blur' event on the select component seems not work same as the 'input' ?
