### ISSUE TITLE
After the [Bug Report] menu is expanded, the current activation menu becomes the default value of the settings.

### ISSUE THREAD

**Issue by hhuangxm** [ElemeFE/element#10833] opened 2018-04-23 03:28 UTC
### Element UI version
2.3.4

### OS/Browsers version
macos 10.12.6/ chrome  65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/y2jg9872/](https://jsfiddle.net/y2jg9872/)

### Steps to reproduce
1. 点击‘展开’按钮
2. 单机菜单‘导航四’
3. 点击‘收起’按钮

### What is Expected?
当前激活菜单应该是‘导航四’，而不是‘导航二’

### What is actually happening?
当前激活菜单变成了‘导航二’

**Comment by Leopoldthecoder** [comment] 2018-04-23 03:41
Duplicate of https://github.com/ElemeFE/element/issues/10622

**Closed by Leopoldthecoder** 2018-04-23 03:41 UTC
