### ISSUE TITLE
ElPagination

### ISSUE THREAD

**Issue by kim-king-rong** [ElemeFE/element#20566] opened 2020-12-12 09:35 UTC
Extraneous non-emits event listeners (beforeEnter) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option.

**Comment by CriztianiX** [comment] 2020-12-16 21:56
Same issue here

**Comment by cs1707** [comment] 2020-12-31 09:09
It looks like it's using Vue 3.0

**Comment by cs1707** [comment] 2020-12-31 09:10
Duplicate of #20375

**Closed by cs1707** 2020-12-31 09:10 UTC

**Comment by iamkun** [comment] 2021-01-02 12:28
Vue@3.0.5 have fixed this issue, you can upgrade and have a try @kim-king-rong
