### ISSUE TITLE
[Bug Report] popover组件trigger="hover"模式下,内嵌checkbox-group组件,change checkbox,会触发popover的显示隐藏,导致闪烁

### ISSUE THREAD

**Issue by zhouxinnana** [ElemeFE/element#12146] opened 2018-07-27 08:45 UTC
### Element UI version
2.4.5

### OS/Browsers version
win10,chrome 69

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/dfne2m95/4/](https://jsfiddle.net/dfne2m95/4/)

### Steps to reproduce
change checkbox,会触发父组件的显示隐藏,导致闪烁,只有在popover在hover模式下回触发,click模式下不会

### What is Expected?
popover在hover模式下.change checkbox禁止触发popover组件的显示隐藏

### What is actually happening?
会触发popover组件的显示隐藏

**Comment by YanwuSenlu** [comment] 2018-07-27 09:50
same problem to me

**Comment by ziyoung** [comment] 2018-07-27 10:00
Duplicate of #12127

**Closed** 2018-07-27 10:00 UTC
