### ISSUE TITLE
[Feature Request] vue 3.0 support

### ISSUE THREAD

**Issue by wxs77577** [ElemeFE/element#19587] opened 2020-06-08 06:52 UTC
### Existing Component
是

### Component Name
all

### Description
Will element ui support vue.js 3.0?
Element UI 什么时候支持 vue.js 3.0？

**Comment by dmix** [comment] 2020-07-23 05:04
I understand this is still coming, but just for the record `element-ui` does not yet load with `vue-3.0.0-rc.4` the breaking error are references to `_vue2.default.prototype` as noted here: https://github.com/ElemeFE/element/issues/19449

Not sure if there is any planned work on this. Allegedly vue 3 is maintaining backwards compatibility. All my other vue plugins seem to support it without any problems at the moment after I ported my app to the composition-api. Just waiting out `element-ui`.

**Comment by zazzaz** [comment] 2020-08-20 10:47
YES!  🎉🎉🎉 Element Plus - A Vue.js 3.0 UI library 🎉🎉🎉 

https://github.com/element-plus/element-plus/issues/147

**Comment by cs1707** [comment] 2020-12-30 14:20
Duplicate of #20375

**Closed by cs1707** 2020-12-30 14:20 UTC
