### ISSUE TITLE
DatetimePicker readonly=true时仍可以通过点击图标清除

### ISSUE THREAD

**Issue by initial-wu** [ElemeFE/element#1383] opened 2016-11-26 12:07 UTC
![qq 20161126200634](https://cloud.githubusercontent.com/assets/17722900/20640261/e2bab25a-b413-11e6-9932-37c152cf9e35.jpg)

**Comment by QingWei-Li** [comment] 2016-11-26 12:47
Duplicate of #1238,   fixed in https://github.com/ElemeFE/element/pull/1326

**Closed by QingWei-Li** 2016-11-26 12:47 UTC
