### ISSUE TITLE
[Bug Report] For Multiple select, the long text didn't been handled properly: 1. The tick is overlapped with options  2. The selected text exceed the text box area

### ISSUE THREAD

**Issue by zhaoyu0810** [ElemeFE/element#9590] opened 2018-01-31 22:06 UTC
### Element UI version
2.1.0

### OS/Browsers version
windows 10 (repro in all browsers)

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/zhaoyu/tuzvry7y/](https://jsfiddle.net/zhaoyu/tuzvry7y/)

### Steps to reproduce
1. Open fiddle link
2. Select "Option1 long name long name long name"

### What is Expected?
The long text should been handled properly

### What is actually happening?
1. The tick is overlapped with options
2. The selected text exceed the textbox area
![image](https://user-images.githubusercontent.com/1256778/35650097-f11f3c06-068f-11e8-8647-363de30c1651.png)

**Comment by Leopoldthecoder** [comment] 2018-02-01 02:24
Duplicate of #9352

**Closed by Leopoldthecoder** 2018-02-01 02:24 UTC
