### ISSUE TITLE
[Bug Report] el-select with 'remote', 'filterable' (but not 'multiple') attributes won't open keyboard on iOS

### ISSUE THREAD

**Issue by mrf00** [ElemeFE/element#14039] opened 2019-01-10 07:50 UTC
### Element UI version
2.4.11

### OS/Browsers version
iOS 12.1.1, Chrome and Safari

### Vue version
2.5.21

### Reproduction Link
[https://jsfiddle.net/ecqpn0gk/](https://jsfiddle.net/ecqpn0gk/)
(This is the example fiddle for el-select with remote search, the only change is to remove the "multiple" keyword)

### Steps to reproduce
Touch on input area of el-select with attributes "remote", "filterable".

### What is Expected?
Keyboard should pop up and allow text entry to search on remote server.

### What is actually happening?
Keyboard does not appear, therefore no text can be entered and component does not work. Note that when the attribute "multiple" is also specified, the keyboard appears as expected.

**Comment by ziyoung** [comment] 2019-02-18 10:26
Duplicate of #12563

**Closed by ziyoung** 2019-02-18 10:26 UTC
