### ISSUE TITLE
The problem of [Bug Report] Tabs style

### ISSUE THREAD

**Issue by monkeyWie** [ElemeFE/element#10490] opened 2018-03-30 13:40 UTC
### Element UI version
2.3.2

### OS/Browsers version
win7 64位 Chrome 62

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/59yp5oh1/](https://jsfiddle.net/59yp5oh1/)

### Steps to reproduce
删除已选中的左边一个tab

### What is Expected?
tab不出现蓝色边框

### What is actually happening?
tab出现蓝色边框

**Comment by Leopoldthecoder** [comment] 2018-03-31 07:28
Duplicate of #9981

**Closed by Leopoldthecoder** 2018-03-31 07:28 UTC
