### ISSUE TITLE
[Bug Report] el-select dropdown does not closes the caret is if the "filterable" option is enabled

### ISSUE THREAD

**Issue by fergardi** [ElemeFE/element#11822] opened 2018-07-02 08:48 UTC
### Element UI version
2.4.2

### OS/Browsers version
Google Chrome 67.0.3396.99 64bits

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/0qmvu8e6/](https://jsfiddle.net/0qmvu8e6/)

### Steps to reproduce
1. Open a select dropdown with the "filterable" option enabled by clicking in the "down" caret.
2. Try to close the dropdown by clicking in the "up" caret.

I know you can close the dropdown by clicking outside or by pressing ESC, but this is a strange behaviour it only occurs when there is an input box to filter the options, which is causing to not lose the focus.

### What is Expected?
The select dropdown should close if I click in the caret.

### What is actually happening?
The select dropdown does not close if I click in the caret.

**Comment by cfasol** [comment] 2018-08-07 10:56
I have the same problem, possible solution is adding handling click on the caret. currently hiding drop-down is managed by click on the input which does not work when in filterable mode

**Comment by ziyoung** [comment] 2018-08-07 11:17
Duplicate of #11048

**Closed by ziyoung** 2018-08-07 11:17 UTC
Labels: component: select
