### ISSUE TITLE
[Bug Report] el-select single filterable select don't fire filter-methods when key-in chinese word in chrome but mutiple filterable select does

### ISSUE THREAD

**Issue by luon08** [ElemeFE/element#12179] opened 2018-07-31 03:49 UTC
### Element UI version
2.4.5

### OS/Browsers version
Win 7/Chrome 67.0.3396.99

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/4390/](https://jsfiddle.net/mmx38qxw/4390/)

### Steps to reproduce
1.key-in chinese words in single filterable select field
2.filter-methods not fired and lists not filtered
3.key-in chinese words in multiple filterable select field
4.filter-methods fired and lists filtered
5.key-in number in single filterable select field
6.filter-methods fired and lists filtered

test in firefox and IE all works fine
only chrome got problem

### What is Expected?
key-in chinese word then filter-methods fired and lists filtered

### What is actually happening?
key-in chinese word then filter-methods not fired and lists not filtered

**Comment by jikkai** [comment] 2018-07-31 05:01
Which input tools are you using?

**Comment by luon08** [comment] 2018-07-31 05:35
Windows build-in chinese input
![image](https://user-images.githubusercontent.com/29967255/43439581-68f90fbc-94c6-11e8-9f04-095ac156aea3.png)

**Comment by luon08** [comment] 2018-07-31 05:49
test in chrome
![gif](https://user-images.githubusercontent.com/29967255/43439961-1e9c7f38-94c8-11e8-89fd-788be5d44ac0.gif)

test in firefox
![gif2](https://user-images.githubusercontent.com/29967255/43440063-759ef568-94c8-11e8-92df-719da6fdecc6.gif)

**Comment by ziyoung** [comment] 2018-07-31 06:48
跟特定的输入法有关系吗？会不会是 composition 的问题？
https://github.com/ElemeFE/element/blob/2bb9fd64818dd108635e7fa91214f908f8b3dbb1/packages/select/src/select.vue#L61-L63

**Comment by luon08** [comment] 2018-07-31 07:03
use windows build-in pinyin input 
got same result
![image](https://user-images.githubusercontent.com/29967255/43443159-ab836704-94d2-11e8-9f64-bb72805e0866.png)


test in chrome lists not filtered
![gif3](https://user-images.githubusercontent.com/29967255/43443190-c1ef715e-94d2-11e8-8199-1d636ec7fd9d.gif)

test in firefox lists filtered
![gif4](https://user-images.githubusercontent.com/29967255/43443227-db0ced24-94d2-11e8-9269-9e5305baae58.gif)

**Comment by jikkai** [comment] 2018-07-31 08:08
Duplicate of #11844

**Closed by jikkai** 2018-07-31 08:08 UTC
Labels: windows

**Comment by luon08** [comment] 2018-08-02 06:25
it's availablein version 2.0.11
i think it's not window  compatibility problem
plz fix it
![gif](https://user-images.githubusercontent.com/29967255/43566078-c5ca2f74-965f-11e8-8b6e-2ab22ce88232.gif)

**Comment by ziyoung** [comment] 2018-08-02 06:48
@luon08 can't reproduce. I am using 2.4.5 version.

![select1](https://user-images.githubusercontent.com/12947422/43566996-f1071df2-9662-11e8-8698-fc720eae4e59.gif)

**Comment by luon08** [comment] 2018-08-02 06:58
@ziyoung did you test in chrome
it only happen in chrome and only single select

**Comment by ziyoung** [comment] 2018-08-02 07:11
@luon08 yes. I am using Sogou Chinese IME. Try other IME?
