### ISSUE TITLE
[Bug Report] [Bug Report] component - popoper - Invalid first click

### ISSUE THREAD

**Issue by heroljy** [ElemeFE/element#8310] opened 2017-11-16 03:34 UTC
### Element UI version
2.0.4

### OS/Browsers version
win10 And the latest chrome version

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
http://element.eleme.io/2.0/#/en-US/component/popover

click the button "Click to activate"

### What is Expected?
click once to open it as elementUI 1.4.9

### What is actually happening?
click twice

**Comment by Acen** [comment] 2017-11-16 03:41
Actual reproducible link: https://jsfiddle.net/mmx38qxw/1/

**Comment by Leopoldthecoder** [comment] 2017-11-16 03:43
Duplicate of #8186

**Closed by Leopoldthecoder** 2017-11-16 03:43 UTC
