### ISSUE TITLE
[Bug Report] Incorrect data in compositionend event when typing Korean on IE11

### ISSUE THREAD

**Issue by jhlee8804** [ElemeFE/element#11665] opened 2018-06-19 06:47 UTC
### Element UI version
2.4.1

### OS/Browsers version
Windows 10 / Internet Explorer 11

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
* IE11 (on Win7 or Win10)
* Switch to the Microsoft Korean IME (standard settings) and switch to Korean input.
* Put the cursor in the input tag and type "한글" (on a QWERTY keyboard this is typed as "gksrmf".).

### What is Expected?
The value of the input tag should appear as "한글".

### What is actually happening?
The value of the input tag appears as "한".  
  
#### Test Screenshot
**Chrome**
![on_chrome](https://user-images.githubusercontent.com/8110371/41581022-1affb2ac-73d8-11e8-8784-9fd36f9ee6ff.gif)

**IE**
![on_ie](https://user-images.githubusercontent.com/8110371/41581027-2063eca4-73d8-11e8-9082-d790a77f639d.gif)
  
#### Console Log Screenshot
**Chrome**
![image](https://user-images.githubusercontent.com/8110371/41581060-38164964-73d8-11e8-8b43-adeee92e7c3d.png)

**IE**
![image](https://user-images.githubusercontent.com/8110371/41581068-3e1ce804-73d8-11e8-9557-0ee54d0c2513.png)

**Comment by jhlee8804** [comment] 2018-06-19 07:04
Editing the code works as follows.

```js
// https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue#L264
handleComposition(event) {
  if (event.type === 'compositionend') {
    this.isOnComposition = false;
    //this.currentValue = this.valueBeforeComposition; // <-- Remove current line!!!
    this.valueBeforeComposition = null;
    this.handleInput(event);
  } else {
    const text = event.target.value;
    const lastCharacter = text[text.length - 1] || '';
    this.isOnComposition = !isKorean(lastCharacter);
    if (this.isOnComposition && event.type === 'compositionstart') {
      this.valueBeforeComposition = text;
    }
  }
}
```

**Comment by jhlee8804** [comment] 2018-06-20 05:53
Type "한글테스트입니다." (on a QWERTY keyboard this is typed as "gksrmfxptmxmdlqslek.")

Chrome)
![on_chrome](https://user-images.githubusercontent.com/8110371/41639648-9f2073e8-7499-11e8-95a8-3ab6c1397107.gif)

IE)
![on_ie](https://user-images.githubusercontent.com/8110371/41639651-a22c6916-7499-11e8-93d8-cebf80eafb79.gif)

**Comment by LoveMeWithoutAll** [comment] 2018-08-06 13:36
+1

**Comment by wacky6** [comment] 2018-11-22 10:12
Please help verify that pr https://github.com/ElemeFE/element/pull/13471 in https://jsfiddle.net/t7j02udc/ fixes this issue. I do not have the knowledge with Korean language.

**Comment by LoveMeWithoutAll** [comment] 2018-11-23 04:33
@wacky6 I am korean user. It seems to be fixed.

 https://jsfiddle.net/t7j02udc/1/

**Comment by cheolhow** [comment] 2019-02-13 06:15
@wacky6 
Hi.
This issue seems to occur again in the latest version.
It has been fixed in version 2.5.2, but it seems to have a problem again in the latest version.

**Comment by wacky6** [comment] 2019-02-14 01:56
This is strange, el-input receives no change after 2.5.0 release.

**Comment by roseforyou** [comment] 2019-02-19 03:30
@wacky6 
Version 2.5.4, not only **`<el-input>`** has IE Korean entry bug, The **`<el-transfer>`**, **`<el-select>`**, if there is a **_filterable_** attribute, this bug will also occur, but **`<el-select>`** if When there are **_filterable_** and **_remote_** attributes, will no problem. hope to reopen this issue

**Comment by wacky6** [comment] 2019-02-19 04:25
Then please provide your OS, browser, Korean IME name and version. And the step to reproduce.

We will reopen this if it is common. If only one IME is buggy, we won’t fix it.

**Comment by roseforyou** [comment] 2019-02-20 01:21
@wacky6 
Hi~
### Element UI version: 
2.5.4, 2.4.4, 2.3.9 _(2.2.2 no this issue)_
### OS/Browsers version
windows 7 & windows 10/ IE 11 
### IME
Microsoft Korean IME of windows system
### Reproduction Link:
http://element-cn.eleme.io/2.5/#/zh-CN/component/input
### Steps to reproduce
Steps to reproduce and Test Screenshot same as @jhlee8804 said 
* Put the cursor in the input tag and type "한글" (on a QWERTY keyboard this is typed as "gksrmf".).
Thanks!

**Comment by jhlee8804** [comment] 2019-04-02 01:56
It is still happening in version 2.7.

**Comment by jhlee8804** [comment] 2019-04-18 02:07
See: https://github.com/ElemeFE/element/pull/15069

**Closed** 2019-04-18 02:08 UTC
Labels: component: input

**Comment by LoveMeWithoutAll** [comment] 2019-06-20 01:37
It is still occurring on v2.9.1
