### ISSUE TITLE
The original color of the [Bug Report] color-picker component is red (expressed in either of  F00 / ff0000 / red / RGB (255, 0, 0) / RGBA (255, 0, 0, 1)), opens the pickup panel, and cannot fill in the current color value in the input box

### ISSUE THREAD

**Issue by rosesky** [ElemeFE/element#12995] opened 2018-10-09 07:02 UTC
### Element UI version
2.4.7

### OS/Browsers version
win7(64位)/chrome  65.0.3325.181

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
①打开element-ui官网拾色器组件地址，地址：http://element-cn.eleme.io/2.4/#/zh-CN/component/color-picker#colorpicker-yan-se-xuan-ze-qi；
②打开第一个基础用法示例的在线运行，页面新建标签地址为：https://jsfiddle.net/api/post/library/pure/；
③在线运行页面修改js部分代码,修改data数据color1属性为字符串"#f00"、"#ff0000"、"red"、"rgb(255,0,0)"、"rgba(255,0,0,1)"中的任意一个,点击页面左上角Run按钮，右下角预览区域对应的拾色器组件颜色变为红色；
④点击右下角预览区与color1对应的组件打开拾色器面板，观察面板左下角的输入框中是否能够回填当前颜色值

### What is Expected?
拾色器面板左下角输入框能够正确回填#f00、#ff0000、red、rgb(255,0,0)、rgba(255,0,0,1)中的一个

### What is actually happening?
拾色器面板左下角输入框显示为空

**Comment by ziyoung** [comment] 2018-10-09 08:06
Duplicate of #12995

**Closed by ziyoung** 2018-10-09 08:06 UTC
